import Link from "next/link";
import {candidateAPI} from "@/lib/candidate-server";
import {CandidateReferralList,referralStatuses} from "@/lib/candidate-referrals";
import {WorkspaceError} from "@/components/candidate/workspace-error";
import {Surface} from "@/components/ui/surface";
export const dynamic="force-dynamic";
export const metadata={title:"My Referrals | SapienWorx"};
export default async function MyReferralsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const params=await searchParams;const single=(k:string)=>typeof params[k]==="string"?params[k] as string:"";
 const q=single("q").slice(0,120),status=single("status"),page=Math.max(1,Math.min(10000,parseInt(single("page")||"1",10)||1));
 const query=new URLSearchParams({q,status,page:String(page),limit:"25"});let data:CandidateReferralList;
 try{data=await candidateAPI<CandidateReferralList>(`/api/v1/candidate/referral-invitations?${query}`)}catch{return <WorkspaceError title="We couldn’t load your referrals."/>}
 const href=(p:number)=>{const v=new URLSearchParams(query);v.set("page",String(p));return `/candidate/referrals?${v}`};
 return <div className="grid min-w-0 gap-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-indigo">Your recommendations</p><h1 className="mt-2 text-3xl font-bold text-navy">My Referrals</h1><p className="mt-2 text-sm leading-7 text-ink-muted">People you’ve recommended for opportunities. Their application remains their choice.</p></header>
 <form method="GET" className="flex min-w-0 flex-wrap items-end gap-3"><label className="grid min-w-0 flex-[2_1_15rem] gap-2 text-sm font-semibold text-ink">Search referrals<input type="search" name="q" defaultValue={q} maxLength={120} placeholder="Person, job or company" className="min-h-11 w-full rounded-xl border border-line bg-white px-3 text-sm font-normal"/></label><label className="grid flex-[1_1_12rem] gap-2 text-sm font-semibold text-ink">Status<select aria-label="Status" name="status" defaultValue={status} className="min-h-11 rounded-xl border border-line bg-white px-3 text-sm font-normal"><option value="">All statuses</option>{Object.entries(referralStatuses).map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label><button className="min-h-11 rounded-xl bg-indigo px-5 text-sm font-semibold text-white">Search</button>{(q||status)&&<Link className="inline-flex min-h-11 items-center text-sm font-semibold text-indigo" href="/candidate/referrals">Clear filters</Link>}</form>
 <p className="text-xs text-ink-muted">{data.total} matching referral{data.total===1?"":"s"}. Only broad progress is shared; hiring feedback and private details stay private.</p>
 {data.items.length?<div className="grid gap-3">{data.items.map(x=><Surface key={x.id} className="p-5"><div className="flex min-w-0 flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h2 className="break-words text-lg font-semibold text-navy">{x.candidate_name}</h2>{x.job_id?<Link href={`/candidate/jobs/${x.job_id}`} className="mt-1 inline-flex min-h-11 items-center text-sm font-medium text-indigo hover:underline">{x.job_title}</Link>:<p className="mt-2 text-sm text-ink">{x.job_title||"Opportunity"}</p>}<p className="text-sm text-ink-muted">{x.company_name}</p><p className="mt-3 text-xs text-ink-muted">Referred {new Date(x.created_at).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata",dateStyle:"medium"})}</p></div><span className="rounded-full border border-line bg-mint/35 px-3 py-2 text-xs font-semibold text-ink">{referralStatuses[x.status]||"Progress unavailable"}</span></div></Surface>)}</div>:<Surface className="p-8"><h2 className="text-lg font-semibold text-navy">{q||status?"No referrals match these filters":"No referrals yet"}</h2><p className="mt-3 text-sm leading-7 text-ink-muted">Find an opportunity and choose “Refer someone” on Job Details to invite a person you know.</p><Link className="mt-4 inline-flex min-h-11 items-center font-semibold text-indigo" href="/candidate/jobs">Explore jobs →</Link></Surface>}
 {data.total>data.limit&&<nav aria-label="Referrals pagination" className="flex flex-wrap items-center justify-between gap-3"><Link href={href(Math.max(1,page-1))} aria-disabled={page<=1} tabIndex={page<=1?-1:undefined} className={`min-h-11 content-center text-sm font-semibold text-indigo ${page<=1?"pointer-events-none opacity-40":""}`}>← Previous</Link><span className="text-xs text-ink-muted">Page {page} of {Math.ceil(data.total/data.limit)}</span><Link href={href(page+1)} aria-disabled={page*data.limit>=data.total} tabIndex={page*data.limit>=data.total?-1:undefined} className={`min-h-11 content-center text-sm font-semibold text-indigo ${page*data.limit>=data.total?"pointer-events-none opacity-40":""}`}>Next →</Link></nav>}
 </div>
}
