import Link from "next/link";
import {requireAdminWorkspace} from "@/lib/admin-access-server";
import {adminAPI,AdminBackendError} from "@/lib/admin-server";
import {canAdmin} from "@/lib/admin-access";
import type {AdminAccountSummary} from "@/lib/admin";
import {adminSurface} from "@/components/admin/recruitment-workspace";
import {recruitmentDate} from "@/lib/admin-recruitment";
const date=(value?:string)=>value?recruitmentDate(value):"Not recorded";
function Fields({items}:{items:[string,string|number][]}) { return <dl className="mt-5 grid gap-5 sm:grid-cols-2">{items.map(([label,value])=><div className="min-w-0" key={label}><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-2 break-all text-sm font-semibold text-slate-900">{value}</dd></div>)}</dl>; }
export default async function AccountSummaryPage({params}:{params:Promise<{userID:string}>}) {
  const {access}=await requireAdminWorkspace("users.read");const {userID}=await params;
  let data:AdminAccountSummary;
  try {data=await adminAPI(`/api/v1/admin/users/${encodeURIComponent(userID)}/summary`);} catch(error) {if(error instanceof AdminBackendError&&(error.status===400||error.status===404)) return <section className={adminSurface}><h1 className="text-2xl font-bold">Account summary unavailable</h1><p className="mt-3 text-sm text-slate-500">The ID is invalid or does not exist. No account information has been inferred.</p><Link className="mt-4 inline-block font-bold text-indigo-600" href="/swx-command-centre/users">Back to accounts</Link></section>;throw error;}
  const c=data.candidate,r=data.recruiter;
  return <section className="min-w-0 space-y-5"><header className={adminSurface+" sm:p-8"}><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Read-only account evidence</p><h1 className="mt-3 text-3xl font-bold text-slate-950">Account summary</h1><p className="mt-3 break-all font-mono text-xs text-slate-600">{data.id}</p><Fields items={[["Account role",data.role.replaceAll("_"," ")],["Account status",data.status.replaceAll("_"," ")],["Joined",date(data.created_at)],["Last successful login",date(data.last_login_at)],["Unrevoked, unexpired sessions",data.active_sessions],["Snapshot",date(data.computed_at)]]}/><Link className="mt-5 inline-block text-sm font-bold text-indigo-600" href="/swx-command-centre/users">Back to account governance →</Link></header>
    {c&&<article className={adminSurface}><h2 className="text-lg font-bold">Candidate onboarding</h2><Fields items={[["Recorded onboarding state",c.onboarding.replaceAll("_"," ")],["Onboarding method",c.method.replaceAll("_"," ")],["Stored profile completion",`${c.profile_completion}%`],["Discoverable to recruiters",c.discoverable?"Enabled":"Not enabled"],["Contact sharing preference",c.contact_sharing?"Enabled":"Not enabled"],["Resume upload recorded",c.resume_uploaded?"Yes — not a scan verdict":"Not recorded"],["Profile updated",date(c.updated_at)],["Submitted applications",c.applications]]}/><p className="mt-4 text-xs leading-6 text-slate-500">Older accounts may have no onboarding state. Stored completion and sharing preferences are not verification, consent-validity or malware-scan certifications. No CV content or profile document is displayed.</p></article>}
    {r&&<article className={adminSurface}><h2 className="text-lg font-bold">Recruiter activity</h2><Fields items={[["Organization",r.company_id||"Not assigned"],["Recruiter verification",r.verification],["Jobs owned",r.jobs_owned],["Active jobs owned",r.active_jobs_owned],["Applications to owned jobs",r.applications_to_owned_jobs],["Recorded stage changes",r.stage_changes],["Recorded interview changes",r.interview_changes],["Last recorded workflow change",date(r.last_recorded_workflow)]]}/><p className="mt-4 text-xs leading-6 text-slate-500">Job ownership is not a complete job-edit ledger. Workflow activity covers retained stage/interview change records only; missing history does not mean no activity occurred.</p></article>}
    {(data.role==="candidate"&&!c||data.role==="recruiter"&&!r)&&<p role="note" className={adminSurface+" text-sm text-amber-800"}>No role profile record is available. Profile details have not been fabricated.</p>}
    <article className={adminSurface}><h2 className="text-lg font-bold">Consent register summary</h2><Fields items={[["Recorded events",data.consent.events],["Purposes with a latest record",data.consent.latest_purposes],["Latest granted, not withdrawn",data.consent.latest_granted],["Latest denied or withdrawn",data.consent.latest_denied_or_withdrawn],["Last event recorded",date(data.consent.last_recorded_at)]]}/><p className="mt-4 text-xs leading-6 text-slate-500">Each purpose uses its latest retained event. These are stored preferences, not a legal determination. No consent metadata, browser fingerprint, policy text or private content is returned. Full privacy casework is a separate permissioned workflow.</p></article>
    {canAdmin(access,"audit.read")&&<Link className="inline-block text-sm font-bold text-indigo-600" href={`/swx-command-centre/audit?target_type=user&target_id=${data.id}`}>Review this account’s administrative audit →</Link>}
  </section>;
}
