import {expect,test} from "@playwright/test";
import fs from "node:fs/promises";
import {login,resetE2E,recordedRequests,waitForRecordedRequest,MOCK_API} from "./helpers";
const jobID="60000000-0000-4000-8000-000000000001";
const sample=(status="applied",name="Leena Rao")=>({id:"83000000-0000-4000-8000-000000000001",candidate_name:name,job_id:jobID,job_title:"Senior Go Platform Engineer",company_name:"Sapien Labs India",status,created_at:"2026-10-07T09:00:00Z",expires_at:"2026-10-14T09:00:00Z"});
test.beforeEach(async({request})=>resetE2E(request));
test("Candidate Job Details sends one governed invitation with no account or application",async({page,request})=>{
 await login(page,"candidate");await page.goto(`/candidate/jobs/${jobID}`);
 await page.getByRole("button",{name:"Refer someone",exact:true}).click();const drawer=page.getByRole("dialog",{name:"Refer someone",exact:true});
 await expect(drawer.getByRole("button",{name:"Close Refer someone"})).toBeFocused();await page.keyboard.press("Shift+Tab");expect(await drawer.evaluate(n=>n.contains(document.activeElement))).toBeTruthy();await expect(drawer.locator("footer")).toBeInViewport();
 await drawer.getByLabel("Full name",{exact:true}).fill("Leena Rao");await drawer.getByLabel("Email",{exact:true}).fill("leena@example.test");await drawer.getByLabel("Relationship (optional)").selectOption("Former colleague");await drawer.getByLabel("Personal message (optional)").fill("I thought this opportunity might suit you.");
 await drawer.getByRole("button",{name:"Send invitation",exact:true}).click();expect((await recordedRequests(request)).filter(r=>r.path==="/api/v1/candidate/referral-invitations"&&r.method==="POST")).toHaveLength(0);
 await drawer.getByRole("checkbox",{name:/I confirm that I know/}).check();await drawer.getByRole("button",{name:"Send invitation",exact:true}).click();
 const call=await waitForRecordedRequest(request,r=>r.method==="POST"&&r.path==="/api/v1/candidate/referral-invitations");expect(call.body).toMatchObject({full_name:"Leena Rao",email:"leena@example.test",job_id:jobID,knows_person:true});for(const field of ["candidate_id","referrer_name","source","cv","salary","skills"])expect(call.body).not.toHaveProperty(field);
 await expect(drawer.getByRole("heading",{name:"Referral invitation queued"})).toBeVisible();await expect(drawer.getByText(/No account or application is created/)).toBeVisible();
 expect((await recordedRequests(request)).filter(r=>r.method==="POST"&&["/api/v1/auth/candidate/register","/api/v1/candidate/applications"].includes(r.path))).toHaveLength(0);
 await drawer.getByRole("button",{name:"Done",exact:true}).click();await expect(page.getByRole("button",{name:"Refer someone",exact:true})).toBeFocused();await page.getByRole("button",{name:"Candidate account"}).click();await page.getByRole("link",{name:"My Referrals",exact:true}).click();await expect(page.getByRole("heading",{name:"My Referrals"})).toBeVisible();await expect(page.getByRole("heading",{name:"Leena Rao"})).toBeVisible();await expect(page.locator("main span").filter({hasText:/^Invitation queued$/})).toBeVisible();
});
test("Share remains a plain public job link; Cancel and Escape preserve the original job",async({page,request})=>{
 await login(page,"candidate");await page.goto(`/candidate/jobs/${jobID}`);await page.getByRole("button",{name:"Share",exact:true}).click();await expect(page.getByRole("status")).toContainText(/Job link copied|Share this job link/);
 await page.getByRole("button",{name:"Refer someone",exact:true}).click();await page.getByRole("dialog").getByLabel("Full name",{exact:true}).fill("Unsent Person");await page.keyboard.press("Escape");await expect(page.getByRole("dialog",{name:"Refer someone"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Refer someone",exact:true})).toBeFocused();expect((await recordedRequests(request)).filter(r=>r.path==="/api/v1/candidate/referral-invitations"&&r.method==="POST")).toHaveLength(0);
});
test("Referral failures stay visible, retain input and do not announce sent",async({page})=>{
 await page.route("**/api/v1/candidate/referral-invitations",route=>route.request().method()==="POST"?route.fulfill({status:429,contentType:"application/json",body:JSON.stringify({error:{message:"You can invite up to 10 people in 24 hours. Please try later."}})}):route.continue());
 await login(page,"candidate");await page.goto(`/candidate/jobs/${jobID}`);await page.getByRole("button",{name:"Refer someone",exact:true}).click();const drawer=page.getByRole("dialog",{name:"Refer someone"});await drawer.getByLabel("Full name",{exact:true}).fill("Leena Rao");await drawer.getByLabel("Email",{exact:true}).fill("leena@example.test");await drawer.getByRole("checkbox").check();await drawer.getByRole("button",{name:"Send invitation"}).click();await expect(drawer.getByRole("alert")).toContainText("10 people");await expect(drawer.getByLabel("Full name",{exact:true})).toHaveValue("Leena Rao");await expect(drawer.getByRole("heading",{name:/invitation queued|invitation sent/})).toHaveCount(0);await drawer.getByRole("button",{name:"Cancel",exact:true}).click();
});
test("My Referrals searches safe statuses and only real activity appears on Home",async({page,request})=>{
 await login(page,"candidate");await expect(page.getByRole("heading",{name:"Your referrals",exact:true})).toHaveCount(0);await request.post(`${MOCK_API}/__e2e/candidate-referrals`,{data:{items:[sample("applied"),{...sample("in_process","Neha Iyer"),id:"83000000-0000-4000-8000-000000000002"}]}});await page.goto("/candidate");await expect(page.getByRole("heading",{name:"Your referrals",exact:true})).toBeVisible();await page.getByRole("link",{name:"View referrals →"}).click();await page.getByLabel("Search referrals",{exact:true}).fill("Neha");await page.getByLabel("Status",{exact:true}).selectOption("in_process");await page.getByRole("button",{name:"Search",exact:true}).click();await expect(page).toHaveURL(/q=Neha.*status=in_process/);await expect(page.getByRole("heading",{name:"Neha Iyer"})).toBeVisible();await expect(page.getByRole("heading",{name:"Leena Rao"})).toHaveCount(0);await expect(page.locator('select[name="status"]')).not.toContainText(/Technical|Feedback|Salary|Rejected/);
});
test("Invitation exposes job description before login; existing applications require history consent",async({page,request})=>{
 await page.goto("/referrals#token=qa-referral-token");await expect(page.getByRole("heading",{name:"About the role",exact:true})).toBeVisible();await expect(page.getByText("Build recruitment infrastructure.", {exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"View complete job description →"})).toHaveAttribute("href",`/jobs/${jobID}`);expect(page.url()).not.toContain("token");await login(page,"candidate");
 await page.goto("/referrals#token=qa-referral-token");await page.getByRole("button",{name:"Save opportunity",exact:true}).click();await waitForRecordedRequest(request,r=>r.path===`/api/v1/candidate/saved-jobs/${jobID}`&&r.method==="PUT");await page.getByRole("link",{name:"View complete job description →"}).click();await expect(page.getByRole("link",{name:"Review referral invitation",exact:true})).toBeVisible();await page.getByRole("link",{name:"Review referral invitation",exact:true}).click();await expect(page.getByRole("button",{name:"Accept invitation"})).toBeVisible();
 await page.route("**/api/v1/candidate/referrals",async route=>{const inData=route.request().postDataJSON();await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({job_id:jobID,job_title:"Senior Go Platform Engineer",company_name:"QA Company",referrer_name:"Synthetic Referrer",expires_at:"2026-10-14T00:00:00Z",status:inData.action==="acknowledge"?"application_submitted":"already_applied",missing:[]})})});
 await page.goto("/referrals#token=qa-referral-token");const button=page.getByRole("button",{name:"Acknowledge recommendation"});await expect(button).toBeDisabled();await page.getByRole("checkbox",{name:/I agree to record this recommendation/}).check();await button.click();await expect(page.getByRole("heading",{name:"Recommendation acknowledged"})).toBeVisible();expect((await recordedRequests(request)).filter(r=>r.path==="/api/v1/candidate/applications"&&r.method==="POST")).toHaveLength(0);
});
test("Candidate referral pages and native drawer fit seven widths in System Light and Dark",async({page,request})=>{
 test.setTimeout(300000);const root="visual-artifacts/candidate-referrals";await fs.mkdir(root,{recursive:true});await login(page,"candidate");const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 for(const [width,height] of [[1920,1080],[1440,900],[1366,768],[1024,768],[768,1024],[428,926],[360,800]]){await page.setViewportSize({width,height});for(const colorScheme of ["light","dark"] as const){await page.emulateMedia({colorScheme});await page.evaluate(()=>{sessionStorage.removeItem("swx.pending.referral");sessionStorage.removeItem("swx.pending.referral.job")});await page.goto(`/candidate/jobs/${jobID}`);await expect(page.getByRole("heading",{name:"Senior Go Platform Engineer",exact:true})).toBeVisible();
 const capture=async(name:string)=>{expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name} ${width} ${colorScheme}`).toBeTruthy();await page.screenshot({path:`${root}/${name}-${width}-${colorScheme}.png`,fullPage:(await page.getByRole("dialog").count())===0,animations:"disabled"})};
 await capture("job-details");await page.getByRole("button",{name:"Refer someone",exact:true}).click();const drawer=page.getByRole("dialog",{name:"Refer someone"});await expect(drawer).toBeVisible();await expect(drawer.locator("footer")).toBeInViewport();expect(await drawer.evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBeTruthy();await capture("referral-drawer");await drawer.getByLabel("Full name",{exact:true}).fill("Leena Rao");await drawer.getByLabel("Email",{exact:true}).fill("leena@example.test");await drawer.getByRole("checkbox").check();await drawer.getByRole("button",{name:"Send invitation"}).click();await expect(drawer.getByRole("heading",{name:"Referral invitation queued"})).toBeVisible();await capture("referral-queued");await drawer.getByRole("button",{name:"Done"}).click();
 await request.post(`${MOCK_API}/__e2e/candidate-referrals`,{data:{items:Object.keys({invitation_queued:1,invitation_sent:1,viewed:1,joined:1,applied:1,in_process:1,successful:1,not_proceeding:1,expired:1}).map((status,i)=>({...sample(status,["Leena Rao","Priya Sharma","Neha Iyer"][i%3]),id:`83000000-0000-4000-8000-${String(i+1).padStart(12,"0")}`}))}});
 await page.goto("/candidate/referrals");await expect(page.getByRole("heading",{name:"My Referrals"})).toBeVisible();await capture("my-referrals");await page.goto("/candidate/referrals?q=no-such-person");await expect(page.getByRole("heading",{name:"No referrals match these filters"})).toBeVisible();await capture("referrals-empty");await page.goto("/referrals#token=qa-referral-token");await expect(page.getByRole("heading",{name:"About the role",exact:true})).toBeVisible();const theme=await page.locator("main>div>section").evaluate(n=>({bg:getComputedStyle(n).backgroundColor,ink:getComputedStyle(n.querySelector("p.text-ink")||n).color}));if(colorScheme==="dark")expect(theme.bg).not.toBe("rgb(255, 255, 255)");const luminance=(value:string)=>{const rgb=(value.match(/[\d.]+/g)||[]).slice(0,3).map(Number).map(v=>v/255<=0.04045?v/3294.6:((v/255+0.055)/1.055)**2.4);return rgb[0]*0.2126+rgb[1]*0.7152+rgb[2]*0.0722};const a=luminance(theme.ink),b=luminance(theme.bg);expect((Math.max(a,b)+0.05)/(Math.min(a,b)+0.05)).toBeGreaterThanOrEqual(4.5);await capture("recipient-review");}}
 expect(errors).toEqual([]);
});
test("System tracks live appearance on referrals and explicit choices stay fixed",async({page})=>{
 await page.emulateMedia({colorScheme:"light"});await login(page,"candidate");await page.goto("/candidate/referrals");await expect(page.locator("html")).not.toHaveClass(/swx-dark/);await page.emulateMedia({colorScheme:"dark"});await expect(page.locator("html")).toHaveClass(/swx-dark/);await page.emulateMedia({colorScheme:"light"});await expect(page.locator("html")).not.toHaveClass(/swx-dark/);
 for(const mode of ["Dark","Light"] as const){await page.getByLabel(/Appearance:/).click();await page.getByRole("button",{name:mode,exact:true}).click();await page.emulateMedia({colorScheme:mode==="Dark"?"light":"dark"});if(mode==="Dark")await expect(page.locator("html")).toHaveClass(/swx-dark/);else await expect(page.locator("html")).not.toHaveClass(/swx-dark/)}
});
