export const companyFixtureID="40000000-0000-4000-8000-000000000001";
const ownerID="20000000-0000-4000-8000-000000000001";
const profile={about:"A synthetic employer used only for local company administration tests. We build thoughtful software and support clear hiring processes.",industry:"Technology",size:"51–200 employees",headquarters:"Pune",website:"https://example.test",logo_url:"",banner_url:"",locations:["Pune","Bengaluru"],benefits:["Flexible work","Learning budget"],culture:"A collaborative environment with a focus on clear communication.",social_links:[]};
export function companyFixture(){const setup={profile,structure:{departments:["Engineering","Product"],locations:["Pune","Bengaluru"]},hiring:{timezone:"Asia/Kolkata",referral_policy:"Refer people you know with their permission.",interview_guidance:"Share expectations and provide prompt feedback.",approval_required:false},privacy:{notice_url:"https://example.test/privacy",retention_days:0,acknowledged:true},completed_steps:["profile","structure"],completed_at:null};const member={company_id:companyFixtureID,user_id:ownerID,name:"Synthetic Company Owner",email:"recruiter@example.com",role:"primary_admin",status:"active",scope:{all:true,departments:[],locations:[],job_ids:[]},talent_seat:true};const policy={company_id:companyFixtureID,managed:true,plan_name:"Synthetic Talent",state:"active",period_start:"2026-10-01T00:00:00Z",period_end:"2026-11-01T00:00:00Z",cancel_at_end:false,features:Object.fromEntries(["discovery","smart_pools","alerts","outreach","analytics","intelligence"].map(k=>[`talent.${k}`,true])),capacity:{recruiters:10,sub_admins:3,talent_seats:5},usage:{talent_profile_unlock:500,outreach_message:2000},free_capacity:{recruiters:5},limits_approved:false};return {member,setup,policy,members:[member,{...member,user_id:"20000000-0000-4000-8000-000000000002",name:"Synthetic Engineering Lead",email:"lead@example.test",role:"sub_admin",scope:{all:false,departments:["Engineering"],locations:[],job_ids:[]},talent_seat:false}],invitations:[],own:[],reviewResponses:{}};}
export function handleCompanyMock(req,res,url,payload,{state,json,noContent,logRequest}){
 const path=url.pathname;
 if(path==="/__e2e/company"&&req.method==="POST"){state.company={...companyFixture(),...payload};return json(res,200,{ok:true})}
 const isCompany=path.startsWith("/api/v1/company/")||path.startsWith("/api/v1/companies")||path.startsWith("/api/v1/candidate/company-reviews")||path.startsWith("/api/v1/reviews/")||path.startsWith("/api/v1/admin/companies")||path.startsWith("/api/v1/admin/company-reviews");if(!isCompany)return false;
 const v=state.company??companyFixture();logRequest(req,url,payload);
 const e={...v.policy,managed:v.policy.managed,plan_name:v.policy.state==="expired"?"SapienWorx Recruit Free":v.policy.plan_name,state:v.policy.state==="expired"?"free":v.policy.state,features:v.policy.state==="expired"?Object.fromEntries(Object.keys(v.policy.features).map(k=>[k,false])):v.policy.features,data_preserved:true,premium_until:v.policy.period_end};
 const c={id:companyFixtureID,name:"Synthetic QA Company",city:"Pune",country:"IN",profile:v.setup.profile,open_jobs:1,employee_count:1,employee_rating:4,interview_count:0};
 const review={id:"92000000-0000-4000-8000-000000000001",company_id:companyFixtureID,kind:"employee",relationship:"current",job_function:"Engineering",location:"Pune",anonymous:true,public_name:"Anonymous",overall:4,ratings:{work_culture:4,learning:5},title:"A thoughtful place to learn",pros:"Clear expectations and supportive engineering peers make collaboration enjoyable.",cons:"Planning and cross-team communication could become more predictable as the company grows.",advice:"Keep communication open and explain priorities.",interview:{experience:"",difficulty:"",duration:"",offer:""},verified:true,published_at:"2026-10-03T12:00:00Z",helpful:3,response:v.reviewResponses["92000000-0000-4000-8000-000000000001"]??""};
 if(path==="/api/v1/company/access")return json(res,200,{member:state.company?v.member:{...v.member,role:"legacy_recruiter"},entitlements:e});
 if(path==="/api/v1/company/workspace")return json(res,200,{member:v.member,setup:v.member.role==="primary_admin"?v.setup:undefined,jobs:[{id:"60000000-0000-4000-8000-000000000001",title:"Senior Go Platform Engineer",department:"Engineering",city:"Pune",status:"active",applications:4}]});
 if(path==="/api/v1/company/setup"){v.setup=payload;return noContent(res)}
 if(path==="/api/v1/company/owner-talent-seat"){v.member.talent_seat=payload.enabled;v.members.find(m=>m.user_id===ownerID).talent_seat=payload.enabled;return noContent(res)}
 if(path.match(/^\/api\/v1\/company\/jobs\/[^/]+\/hiring$/))return json(res,200,{applications:[{id:"72000000-0000-4000-8000-000000000001",candidate_id:"10000000-0000-4000-8000-000000000001",name:"Synthetic Scoped Applicant",headline:"Platform Engineer",stage:"new_application",applied_at:new Date().toISOString()}],interviews:[]});
 if(path.match(/^\/api\/v1\/company\/jobs\/[^/]+\/interviews$/))return json(res,201,{id:crypto.randomUUID()});
 if(path==="/api/v1/company/plan")return json(res,200,{policy:v.policy,entitlements:e,usage:{talent_profile_unlock:374},capacity_usage:{sub_admins:1,recruiters:3,talent_seats:2,active_jobs:1},overrides:[]});
 if(path==="/api/v1/company/team"){if(req.method==="GET")return json(res,200,{members:v.member.role==="sub_admin"?v.members.filter(m=>["recruiter","collaborator"].includes(m.role)&&(!m.scope.all||v.member.scope.all)&&["departments","locations","job_ids"].every(k=>(m.scope[k]??[]).every(x=>v.member.scope.all||(v.member.scope[k]??[]).includes(x)))):v.members,invitations:v.invitations});const invite={id:crypto.randomUUID(),...payload,expires_at:new Date(Date.now()+7*86400000).toISOString()};v.invitations.push(invite);return json(res,201,{id:invite.id,status:"invitation_queued"})}
 if(path.match(/^\/api\/v1\/company\/team\/[^/]+\/resources$/))return json(res,200,{jobs:3,saved_searches:2,talent_pools:1,sequences:1,campaigns:1});
 if(path.match(/^\/api\/v1\/company\/team\/[^/]+$/)){const id=path.split("/").at(-1);const m=v.members.find(m=>m.user_id===id);if(m){m.status=payload.action==="deactivate"?"inactive":payload.action==="inactive_plan"?"inactive_plan":"active";if(payload.role){m.role=payload.role;m.scope=payload.scope;m.talent_seat=payload.talent_seat}}return noContent(res)}
 if(path.startsWith("/api/v1/company/invitations/")){const i=v.invitations.find(i=>i.id===path.split("/").at(-1));if(i)i.revoked_at=new Date().toISOString();return noContent(res)}
 if(path==="/api/v1/company/audit")return json(res,200,{items:[{action:"team.invited",created_at:new Date().toISOString(),details:{reason:"Synthetic scoped team invitation"}}]});
 if(path==="/api/v1/companies")return json(res,200,{items:[c],total:1,page:1,limit:20});
 if(path===`/api/v1/companies/${companyFixtureID}`)return json(res,200,{company:c,jobs:[{id:"60000000-0000-4000-8000-000000000001",title:"Senior Go Platform Engineer",city:"Pune",work_mode:"hybrid"}],category_ratings:{work_culture:{average:4,count:1},learning:{average:5,count:1}}});
 if(path===`/api/v1/companies/${companyFixtureID}/reviews`)return json(res,200,{items:url.searchParams.get("kind")==="interview"?[]:[review],total:url.searchParams.get("kind")==="interview"?0:1,page:1,limit:20});
 if(path==="/api/v1/candidate/company-reviews"){if(req.method==="GET")return json(res,200,{items:v.own});const r={id:crypto.randomUUID(),...payload,interview_details:payload.interview,display_name:c.name,moderation_status:"pending"};v.own.push(r);return json(res,201,{id:r.id,status:"pending_moderation"})}
 if(path.startsWith("/api/v1/candidate/company-reviews/")){const id=path.split("/").at(-1);if(req.method==="DELETE")v.own=v.own.filter(r=>r.id!==id);else {const i=v.own.findIndex(r=>r.id===id);if(i>=0)v.own[i]={...v.own[i],...payload,moderation_status:"pending"}}return noContent(res)}
 if(path.match(/\/reviews\/[^/]+\/response$/)){v.reviewResponses[path.split("/").at(-2)]=payload.body;return noContent(res)}
 if(path.startsWith("/api/v1/reviews/"))return noContent(res);
 if(path==="/api/v1/admin/company-reviews")return json(res,200,{items:[{...review,display_name:c.name,moderation_flags:[],revision:1,moderation_status:"pending",pending_reports:0}]});
 if(path.startsWith("/api/v1/admin/company-reviews/"))return noContent(res);
 if(path===`/api/v1/admin/companies/${companyFixtureID}/subscription`){if(req.method==="PUT")v.policy=payload.policy;return json(res,200,{policy:v.policy,entitlements:e,usage:{},overrides:[]})}
 if(path.startsWith("/api/v1/admin/companies"))return json(res,201,{id:companyFixtureID});
 return json(res,404,{error:{message:"Synthetic company route not found"}});
}
