import {expect,test} from "@playwright/test";
import fs from "node:fs/promises";
import {login,resetE2E,MOCK_API,recordedRequests} from "./helpers";
test.beforeEach(async({request})=>resetE2E(request));
test("bell opens the centre; opening it preserves unread state; row actions are individual",async({page,request})=>{
 await login(page,"recruiter");await page.goto("/recruiter");await page.getByRole("link",{name:"Notifications, 2 unread",exact:true}).click();await expect(page).toHaveURL(/\/recruiter\/notifications$/);await expect(page.getByRole("heading",{name:"Notifications",exact:true})).toBeVisible();
 expect((await recordedRequests(request)).filter(r=>r.method==="PATCH"&&r.path.includes("notifications"))).toHaveLength(0);
 await page.getByLabel("Notification category",{exact:true}).selectOption("messages");await expect(page.getByRole("button",{name:"New candidate message",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Interview panel invitation",exact:true})).toHaveCount(0);
 await page.getByLabel("More actions for New candidate message").click();await page.getByRole("button",{name:"Mark read",exact:true}).click();await page.getByLabel("Unread only",{exact:true}).check();await expect(page.getByRole("heading",{name:"You’re all caught up"})).toBeVisible();
 await page.getByLabel("Unread only",{exact:true}).uncheck();await page.getByRole("button",{name:"Open conversation",exact:true}).click();await expect(page).toHaveURL(/\/recruiter\/messages\?thread=/);
});
test("99+ badge, dismiss, preferences, deleted entity and empty centre",async({page,request})=>{
 const items=Array.from({length:101},(_,i)=>({id:`91000000-0000-4000-8000-${String(i+1).padStart(12,"0")}`,category:"applications",title:`Application update ${i+1}`,message:"An application changed.",created_at:new Date().toISOString(),read:false,href:"/recruiter/pipeline",deleted:i===0}));await request.post(`${MOCK_API}/__e2e/recruiter-notifications`,{data:{items}});
 await login(page,"recruiter");await page.goto("/recruiter/notifications");await expect(page.getByRole("link",{name:"Notifications, 101 unread"})).toContainText("99+");await page.getByRole("button",{name:"Application update 1",exact:true}).click();await expect(page.locator("main").getByRole("alert")).toContainText("no longer available");
 await page.getByLabel("More actions for Application update 2",{exact:true}).click();await page.getByRole("button",{name:"Dismiss Application update 2",exact:true}).click();await expect(page.getByRole("button",{name:"Application update 2",exact:true})).toHaveCount(0);
 await page.getByRole("button",{name:"Mark all as read",exact:true}).click();await expect(page.getByRole("status").first()).toContainText("0 unread");await page.getByRole("button",{name:"Notification settings",exact:true}).click();const d=page.getByRole("dialog",{name:"Notification settings"});await d.getByRole("checkbox",{name:"Applications",exact:true}).uncheck();await d.getByRole("button",{name:"Save preferences"}).click();await expect(page.getByRole("heading",{name:"No notifications yet"})).toBeVisible();
});
test("notification centre remains readable and keyboard accessible across themes and viewports",async({page})=>{
 test.setTimeout(90000);await login(page,"recruiter");await fs.mkdir("visual-artifacts/recruiter-notifications",{recursive:true});const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text());});
 for(const width of[1440,1366,768,360])for(const mode of["light","dark","system"]){await page.setViewportSize({width,height:width<768?800:900});await page.evaluate(mode=>localStorage.setItem("swx-theme",mode),mode);await page.goto("/recruiter/notifications");await expect(page.getByRole("heading",{name:"Notifications",exact:true})).toBeVisible();await page.getByRole("button",{name:"Notification settings",exact:true}).click();const settings=page.getByRole("dialog",{name:"Notification settings"});await expect(settings.getByRole("checkbox",{name:"Applications",exact:true})).toBeVisible();await page.keyboard.press("Escape");await expect(settings).not.toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.screenshot({path:`visual-artifacts/recruiter-notifications/${width}-${mode}.png`,fullPage:true});}
 await page.getByRole("button",{name:"Notification settings",exact:true}).focus();await page.keyboard.press("Enter");const d=page.getByRole("dialog",{name:"Notification settings"});await expect(d).toBeVisible();await page.keyboard.press("Escape");await expect(d).not.toBeVisible();await expect(page.getByRole("button",{name:"Notification settings",exact:true})).toBeFocused();expect(errors).toEqual([]);
});
