import {expect,test} from "@playwright/test";
import fs from "node:fs/promises";
import {login,resetE2E,recordedRequests,waitForRecordedRequest,MOCK_API} from "./helpers";
test.beforeEach(async({request})=>resetE2E(request));
test("Application toolbar, counted stages, private job context and left filter drawer",async({page,request})=>{
 await login(page,"recruiter");await page.goto("/recruiter/pipeline");await expect(page.getByRole("navigation",{name:"Application stages"}).getByRole("link",{name:/New 9/})).toBeVisible();await page.getByLabel("Search applications",{exact:true}).fill("Candidate 001");await expect(page).toHaveURL(/q=Candidate/);await expect(page.getByRole("link",{name:"Candidate 001",exact:true})).toBeVisible();await page.getByRole("button",{name:/^Filters/}).click();const drawer=page.getByRole("dialog",{name:"Application filters",exact:true});await expect(drawer).toBeVisible();expect(await drawer.evaluate(n=>n.getBoundingClientRect().left)).toBe(0);await page.keyboard.press("Shift+Tab");expect(await drawer.evaluate(n=>n.contains(document.activeElement))).toBeTruthy();await page.keyboard.press("Escape");await expect(drawer).not.toBeVisible();await page.goto("/recruiter/pipeline");await page.getByRole("navigation",{name:"Application stages"}).getByRole("link",{name:/Interview/}).click();const call=await waitForRecordedRequest(request,r=>r.path==="/api/v1/recruiter/pipeline"&&r.search.includes("technical_interview"));expect(call.search).toContain("hr_round");expect(call.search).toContain("final_interview");await page.goto("/recruiter/jobs/60000000-0000-4000-8000-000000000001/applicants");await expect(page.getByRole("columnheader",{name:"Job / role"})).toHaveCount(0);
});
test("Jobs filter immediately and selection and sensitive lifecycle changes are governed",async({page,request})=>{
 await login(page,"recruiter");await page.goto("/recruiter/jobs");await expect(page.getByRole("region",{name:"Bulk job actions"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Apply",exact:true})).toHaveCount(0);await page.getByLabel("Work mode",{exact:true}).selectOption("hybrid");await expect(page).toHaveURL(/work_mode=hybrid/);await page.getByRole("checkbox",{name:"Select all jobs on this page"}).check();await expect(page.getByRole("region",{name:"Bulk job actions"})).toBeVisible();await page.getByRole("button",{name:"Clear page"}).click();await expect(page.getByRole("region",{name:"Bulk job actions"})).toHaveCount(0);await page.getByRole("button",{name:"More actions for Senior Go Platform Engineer"}).first().click();const drawer=page.getByRole("dialog",{name:"Senior Go Platform Engineer",exact:true});await expect(drawer.getByRole("button",{name:"Duplicate job as draft"})).toBeVisible();await expect(drawer.getByLabel("Assign recruiter")).toBeVisible();page.once("dialog",d=>d.dismiss());await drawer.getByRole("button",{name:"Closed job",exact:true}).click();expect((await recordedRequests(request)).filter(r=>r.method==="PATCH"&&r.path.endsWith("/status"))).toHaveLength(0);await page.keyboard.press("Escape");
});
test("Interview primary actions and overflow preserve manual meeting and rescheduling",async({page})=>{
 await login(page,"recruiter");await page.goto("/recruiter/interviews");await expect(page.getByRole("button",{name:"Cancel",exact:true})).toHaveCount(0);await expect(page.getByRole("link",{name:/Join meeting/}).first()).toBeVisible();await page.getByRole("button",{name:/More interview actions/}).first().click();const drawer=page.getByRole("dialog",{name:/Interview with/});await expect(drawer.getByRole("button",{name:"Cancel interview",exact:true})).toBeVisible();await drawer.getByRole("button",{name:"Reschedule",exact:true}).click();const edit=page.getByRole("dialog",{name:/Reschedule/});await expect(edit.getByRole("button",{name:"Save new schedule"})).toBeVisible();await expect(edit.locator("footer")).toBeInViewport();await page.keyboard.press("Escape");await page.getByLabel("Search interviews").fill("does-not-exist");await expect(page).toHaveURL(/q=does-not-exist/);await expect(page.getByRole("link",{name:/Join meeting/})).toHaveCount(0);
});
test("Named pool creation and read-only Smart Pool membership are distinct from bookmarks",async({page,request})=>{
 await login(page,"recruiter");await page.goto("/recruiter/talent-pool");await page.getByLabel("Location",{exact:true}).fill("Pune");await expect(page).toHaveURL(/location=Pune/);await page.getByLabel("Availability",{exact:true}).selectOption("30");await expect(page).toHaveURL(/max_notice_days=30/);await page.getByRole("navigation",{name:"Talent pool types"}).getByRole("link",{name:"Smart Pools",exact:true}).click();await expect(page.getByRole("heading",{name:"Choose a Smart Pool"})).toBeVisible();await page.locator("section").filter({has:page.getByRole("heading",{name:"Choose a Smart Pool"})}).getByRole("link").last().click();await expect(page).not.toHaveURL(/location=|max_notice_days=|q=/);await page.goto("/recruiter/talent-pool");await page.getByRole("button",{name:"+ Create pool"}).click();const drawer=page.getByRole("dialog",{name:"Create talent pool"});await drawer.getByLabel("Pool name",{exact:true}).fill("Leadership hiring");await drawer.getByLabel("Visibility",{exact:true}).selectOption("company");await drawer.getByRole("button",{name:"Create pool",exact:true}).click();const create=await waitForRecordedRequest(request,r=>r.method==="POST"&&r.path==="/api/v1/recruiter/talent-pools");expect(create.body).toMatchObject({name:"Leadership hiring",visibility:"company",kind:"manual",criteria:{},team_ids:[]});await expect(page).toHaveURL(/pool_id=/);await page.goto("/recruiter/talent-pool?pool_id=81000000-0000-4000-8000-000000000002");await expect(page.getByText(/Live membership based on current criteria and consent/)).toBeVisible();await expect(page.getByRole("button",{name:/Edit tags/})).toHaveCount(0);
});
test("Recruiters track referrals without an intake action",async({page})=>{
 await login(page,"recruiter");await page.goto("/recruiter/referrals");await expect(page.getByRole("button",{name:/Refer a person|Refer candidate/})).toHaveCount(0);await expect(page.getByRole("link",{name:"View referred applicants"})).toBeVisible();
});
test("Verified candidate accepts separately from explicit consented Apply",async({page,request})=>{
 await login(page,"candidate");await page.goto("/referrals#token=qa-referral-token");await expect(page.getByRole("button",{name:"Accept invitation"})).toBeVisible();expect(page.url()).not.toContain("token");await page.getByRole("button",{name:"Accept invitation"}).click();await expect(page.getByRole("button",{name:"Apply to this job"})).toBeDisabled();expect((await recordedRequests(request)).filter(r=>r.path==="/api/v1/candidate/referrals"&&r.body.action==="apply")).toHaveLength(0);await page.getByRole("checkbox",{name:/I choose to apply/}).check();await page.getByRole("button",{name:"Apply to this job"}).click();await expect(page.getByRole("heading",{name:"Your application was submitted."})).toBeVisible();await waitForRecordedRequest(request,r=>r.path==="/api/v1/candidate/referrals"&&r.body.action==="apply"&&r.body.consent===true);
});
test("Finished pages and drawers fit seven viewports in System Light and Dark",async({page})=>{
 test.setTimeout(300000);await login(page,"recruiter");const root="visual-artifacts/recruiter-refinements";await fs.mkdir(root,{recursive:true});const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));for(const[width,height]of[[1920,1080],[1440,900],[1366,768],[1024,768],[768,1024],[428,926],[360,800]]){await page.setViewportSize({width,height});for(const colorScheme of["light","dark"]as const){await page.emulateMedia({colorScheme});for(const[name,url]of[["applications","/recruiter/pipeline"],["jobs","/recruiter/jobs"],["interviews","/recruiter/interviews"],["pools","/recruiter/talent-pool"],["smart-pool","/recruiter/talent-pool?pool_id=81000000-0000-4000-8000-000000000002"],["referrals","/recruiter/referrals"]]){await page.goto(url);await expect(page.locator("main h1")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name} ${width} ${colorScheme}`).toBeTruthy();await page.screenshot({path:`${root}/${name}-${width}-${colorScheme}.png`,fullPage:true,caret:"initial",animations:"disabled"});}for(const[name,url,trigger,title]of[["application-filters","/recruiter/pipeline",/^Filters/,"Application filters"],["create-pool","/recruiter/talent-pool","+ Create pool","Create talent pool"]]as const){await page.goto(url);await page.getByRole("button",{name:trigger}).click();const drawer=page.getByRole("dialog",{name:title,exact:true});await expect(drawer).toBeVisible();expect(await drawer.evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBeTruthy();if(name!=="application-filters")await expect(drawer.locator("footer")).toBeInViewport();await page.keyboard.press("Shift+Tab");expect(await drawer.evaluate(n=>n.contains(document.activeElement))).toBeTruthy();await page.screenshot({path:`${root}/${name}-${width}-${colorScheme}.png`,fullPage:true,caret:"initial",animations:"disabled"});await page.keyboard.press("Escape");await expect(drawer).not.toBeVisible();}}}expect(errors).toEqual([]);
});

test("New referral invitee retains the token through registration, verification and first-login setup",async({page,request})=>{
 await request.post(`${MOCK_API}/__e2e/onboarding`,{data:{status:"not_started"}});
 await page.goto("/referrals#token=qa-referral-token");await page.getByRole("link",{name:"Create my account",exact:true}).click();await expect(page).toHaveURL(/signup\?next=%2Freferrals/);
 await page.getByLabel("Full name",{exact:true}).fill("Synthetic Invitee");await page.getByLabel("Email",{exact:true}).fill("synthetic@example.test");await page.getByLabel(/^Mobile number/).fill("+919876543210");await page.getByLabel(/^Password/).fill("Synthetic-test-only-123!");await page.getByRole("checkbox",{name:/reviewed the privacy/}).check();await page.getByRole("checkbox",{name:/18 years/}).check();await page.getByRole("button",{name:"Create account",exact:true}).click();await expect(page).toHaveURL(/verify-email.*next=%2Freferrals/);
 await page.getByLabel("Email verification code",{exact:true}).fill("654321");await page.getByRole("button",{name:"Verify email",exact:true}).click();await expect(page).toHaveURL(/login.*next=%2Freferrals/);
 await page.getByLabel("Email",{exact:true}).fill("synthetic@example.test");await page.getByLabel(/^Password/).fill("Synthetic-test-only-123!");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/welcome\?next=%2Freferrals/);await page.getByRole("button",{name:"Create My Profile",exact:true}).click();await expect(page).toHaveURL(/onboarding\?next=%2Freferrals/);
 await waitForRecordedRequest(request,r=>r.path==="/api/v1/candidate/onboarding"&&r.body.return_to==="/referrals");expect(await page.evaluate(()=>sessionStorage.getItem("swx.pending.referral"))).toBe("qa-referral-token");expect((await recordedRequests(request)).filter(r=>r.path==="/api/v1/candidate/referrals"&&r.body.action==="apply")).toHaveLength(0);
});
test("Unavailable referral links present a controlled error and no application action",async({page})=>{
 await page.route("**/api/v1/referrals/lookup",route=>route.fulfill({status:404,contentType:"application/json",body:JSON.stringify({error:{code:"referral_unavailable",message:"This invitation is unavailable or expired."}})}));
 await page.goto("/referrals#token=qa-invalid-token");await expect(page.locator("main").getByRole("alert")).toContainText("unavailable or expired");await expect(page.getByRole("button",{name:"Apply to this job"})).toHaveCount(0);expect(page.url()).not.toContain("token");
});
