import {expect,test} from "@playwright/test";
import fs from "node:fs/promises";
import {login,resetE2E} from "./helpers";
test.beforeEach(async({request})=>resetE2E(request));
test("final password recovery and employer referral configuration visual review",async({page})=>{
 test.setTimeout(90000);await fs.mkdir("visual-artifacts/recruiter-final-review",{recursive:true});await login(page,"recruiter");const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 for(const width of[1440,360])for(const mode of["light","dark"]){await page.setViewportSize({width,height:width===360?800:900});await page.evaluate(mode=>localStorage.setItem("swx-theme",mode),mode);await page.goto("/forgot-password?returnTo=%2Frecruiter%2Fsettings");await expect(page.getByText("recruiter@example.com",{exact:true})).toBeVisible();await page.screenshot({path:`visual-artifacts/recruiter-final-review/recovery-request-${width}-${mode}.png`,fullPage:true});await page.getByRole("button",{name:"Send reset code",exact:true}).click();await expect(page.getByRole("heading",{name:"Choose a new password"})).toBeVisible();await page.screenshot({path:`visual-artifacts/recruiter-final-review/recovery-code-${width}-${mode}.png`,fullPage:true});
 await page.goto("/recruiter/jobs/new");await page.getByRole("button",{name:/Publish Review/}).click();await page.getByRole("checkbox",{name:/Enable referrals/}).check();await page.getByRole("checkbox",{name:"This job has an employer referral reward programme"}).check();await page.getByLabel("Referral closing date (optional)").fill("2026-12-15");await page.getByLabel("Eligibility rules (required for rewards)").fill("Canonical first referral, successful placement and employer retention review.");await page.getByLabel("Referral terms (required for rewards)").fill("Eligibility is reviewed by the employer. Invitation submission does not guarantee payment.");await expect(page.getByText(/first valid referral wins/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,behavior:"instant"});});await expect.poll(async()=>{await page.evaluate(()=>window.scrollTo({top:0,behavior:"instant"}));return page.evaluate(()=>scrollY)}).toBeLessThanOrEqual(5);await expect.poll(async()=>Math.round((await page.locator(".swx-recruiter-workspace > header").boundingBox())!.y)).toBe(0);await page.screenshot({path:`visual-artifacts/recruiter-final-review/referral-settings-${width}-${mode}.png`,fullPage:true});
 }
 expect(errors).toEqual([]);
});
