import {expect,test} from "@playwright/test";
import fs from "node:fs/promises";
import {login,resetE2E} from "./helpers";
test.beforeEach(async({request})=>resetE2E(request));
test("Referral public, unavailable, readiness and outcome states are readable and governed",async({page,context})=>{
 test.setTimeout(90000);const root="visual-artifacts/recruiter-refinements";await fs.mkdir(root,{recursive:true});let unavailable=false,status="accepted",missing:string[]=["Professional skills"],jobTitle:string|undefined="Senior Go Platform Engineer";
 await page.route("**/api/v1/referrals/lookup",route=>route.fulfill({status:unavailable?404:200,contentType:"application/json",body:JSON.stringify(unavailable?{error:{message:"This invitation is unavailable or expired."}}:{id:"synthetic",company_name:"QA Company",job_title:jobTitle,expires_at:"2026-10-14T00:00:00Z"})}));
 await page.route("**/api/v1/candidate/referrals",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:"synthetic",company_name:"QA Company",job_title:jobTitle,referrer_name:"Synthetic Referrer",status,missing,expires_at:"2026-10-14T00:00:00Z"})}));
 for(const [width,height] of [[1440,900],[360,800]]){await page.setViewportSize({width,height});for(const colorScheme of ["light","dark"] as const){await page.emulateMedia({colorScheme});await context.clearCookies();await page.goto("/");unavailable=false;jobTitle="Senior Go Platform Engineer";await page.goto("/referrals#token=synthetic-token");await expect(page.getByRole("link",{name:"Apply for this job"})).toBeVisible();await page.screenshot({path:`${root}/invitation-public-${width}-${colorScheme}.png`,fullPage:true});unavailable=true;await page.goto("/referrals#token=synthetic-token");await expect(page.locator("main").getByRole("alert")).toContainText("unavailable or expired");await page.screenshot({path:`${root}/invitation-unavailable-${width}-${colorScheme}.png`,fullPage:true});unavailable=false;await login(page,"candidate");for(const [name,nextStatus,nextMissing,title]of[["missing-profile","accepted",["Professional skills"],"Senior Go Platform Engineer"],["general","accepted",["Professional skills"],undefined],["already-applied","already_applied",[],"Senior Go Platform Engineer"],["submitted","application_submitted",[],"Senior Go Platform Engineer"]] as const){status=nextStatus;missing=[...nextMissing];jobTitle=title;await page.goto("/referrals#token=synthetic-token");if(name==="missing-profile")await expect(page.getByRole("link",{name:"Complete my profile"})).toBeVisible();else await expect(page.getByText(name==="general"?"This is a general talent invitation. No job application has been created.":name==="already-applied"?"You already applied to this role. Your existing application and source attribution are retained.":"Your application was submitted.",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Apply to this job",exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.screenshot({path:`${root}/invitation-${name}-${width}-${colorScheme}.png`,fullPage:true});if(name==="missing-profile"){await page.getByRole("link",{name:"Complete my profile"}).click();await expect(page.getByRole("link",{name:"← Return to my referral invitation"})).toHaveAttribute("href","/referrals");}}}}
});
