import {expect,test} from "@playwright/test";
import {login,resetE2E,MOCK_API} from "./helpers";
const job="60000000-0000-4000-8000-000000000001";
test.beforeEach(async({request})=>resetE2E(request));
test("applied and saved candidates can still refer; closing date and disabled programme govern the action",async({page,request})=>{
 await request.post(`${MOCK_API}/__e2e/workspace`,{data:{saved_job_ids:[job]}});await login(page,"candidate");await page.goto(`/candidate/jobs/${job}`);await expect(page.getByRole("button",{name:"Applied ✓",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Refer someone",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Remove from saved jobs",exact:true})).toHaveText("Saved ✓");
 await request.post(`${MOCK_API}/__e2e/public-job`,{data:{job:{referral_enabled:true,referral_deadline:"2020-01-01"}}});await page.reload();await expect(page.getByRole("button",{name:"Refer someone",exact:true})).toHaveCount(0);
 await request.post(`${MOCK_API}/__e2e/public-job`,{data:{job:{referral_enabled:false}}});await page.reload();await expect(page.getByRole("button",{name:"Refer someone",exact:true})).toHaveCount(0);
});
test("reward terms are transparent and progress fields remain independent",async({page,request})=>{
 await request.post(`${MOCK_API}/__e2e/public-job`,{data:{job:{referral_enabled:true,referral_reward_enabled:true,referral_terms:"Placement and employer retention review required.",referral_eligibility:"Only the canonical first referral is eligible."}}});await login(page,"candidate");await page.goto(`/candidate/jobs/${job}`);await expect(page.getByText(/does not guarantee a reward/)).toBeVisible();await page.getByRole("button",{name:"Refer someone",exact:true}).click();const d=page.getByRole("dialog",{name:"Refer someone",exact:true});await d.locator("summary").filter({hasText:"Referral programme terms"}).click();await expect(d.getByText("Only the canonical first referral is eligible.", {exact:true})).toBeVisible();await expect(d.locator('input[type="file"]')).toHaveCount(0);await page.keyboard.press("Escape");
 await request.post(`${MOCK_API}/__e2e/candidate-referrals`,{data:{items:[{id:"83000000-0000-4000-8000-000000000001",candidate_name:"Priya Synthetic",job_id:job,job_title:"Senior Go Platform Engineer",company_name:"QA Company",status:"successful",referral_status:"accepted",hiring_progress:"successful",reward_progress:"pending",reward_programme:true,created_at:new Date().toISOString(),expires_at:"2026-12-01T00:00:00Z"}]}});await page.goto("/candidate/referrals");await expect(page.locator("dl").getByText("Accepted",{exact:true})).toBeVisible();await expect(page.locator("dl").getByText("Successful",{exact:true})).toBeVisible();await expect(page.locator("dl").getByText("Pending",{exact:true})).toBeVisible();await expect(page.getByText(/does not promise or initiate payment/)).toBeVisible();
});
