import { RecruiterShell } from "@/components/recruiter/recruiter-shell";
import { PipelineTable } from "@/components/recruiter/pipeline-table";
import { requireRole } from "@/lib/auth-server";
import { recruiterAPI } from "@/lib/recruiter-server";
import { label, PipelineRow, RecruiterJob, stages } from "@/lib/recruiter";

export const dynamic="force-dynamic";
type Props={searchParams:Promise<{q?:string;stage?:string;job_id?:string}>};
export default async function PipelinePage({searchParams}:Props){await requireRole("recruiter");const params=await searchParams;const query=new URLSearchParams();if(params.q)query.set("q",params.q);if(params.stage)query.set("stage",params.stage);if(params.job_id)query.set("job_id",params.job_id);query.set("limit","100");const [{items},{items:jobs}]=await Promise.all([recruiterAPI<{items:PipelineRow[]}>(`/api/v1/recruiter/pipeline?${query}`),recruiterAPI<{items:RecruiterJob[]}>("/api/v1/recruiter/jobs")]);return <RecruiterShell><div className="grid gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-indigo">Dense candidate pipeline</p><h1 className="mt-1 text-2xl font-bold tracking-[-0.035em] sm:text-3xl">Pipeline</h1><p className="mt-1 text-sm text-ink-muted">One sortable mental model: rows, filters and explicit stage controls. No Kanban.</p></div><form className="grid gap-2 rounded-2xl border border-line/70 bg-white p-3 sm:grid-cols-2 xl:grid-cols-[minmax(14rem,1fr)_12rem_18rem_auto]"><input name="q" defaultValue={params.q} placeholder="Candidate name or headline" className="rounded-lg border border-line px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo"/><select name="stage" defaultValue={params.stage??""} className="rounded-lg border border-line px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo"><option value="">All stages</option>{stages.map(v=><option key={v} value={v}>{label(v)}</option>)}</select><select name="job_id" defaultValue={params.job_id??""} className="rounded-lg border border-line px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo"><option value="">All jobs</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.title}</option>)}</select><button className="rounded-lg bg-indigo px-4 py-2 text-sm font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo focus-visible:ring-offset-2">Filter</button></form><div className="flex items-center justify-between text-xs text-ink-muted"><span>{items.length} candidates shown</span><span>Up to 100 rows per filtered view</span></div><PipelineTable rows={items}/></div></RecruiterShell>}
