import { Badge, Button, Meter, SectionTitle, StatCard, WorkspaceShell } from "./ui";

const registrations = [32, 46, 40, 57, 72, 90, 78, 101, 88, 116, 130, 151];

export function AdminOverview() {
  return <WorkspaceShell workspace="admin" active="dashboard" title="Platform overview" description="Live system and business health across Sapienworx." actions={<><Button variant="secondary">Export report</Button><Button>Platform settings</Button></>}>
    <div className="admin-notice"><span>◉</span><div><strong>All core services are operational</strong><p>Parser processing, notifications, storage and billing are operating within normal thresholds.</p></div></div>
    <section className="stat-grid"><StatCard label="Total users" value="12,482" change="+8.4% this month" icon="♙" tone="blue"/><StatCard label="Active organizations" value="184" change="+12 this month" icon="▦" tone="purple"/><StatCard label="Active jobs" value="638" change="+14.1% this month" icon="▤" tone="green"/><StatCard label="Parser success rate" value="98.6%" change="Last 30 days" icon="◌" tone="amber"/></section>
    <section className="admin-grid" style={{ marginTop: 20 }}><div className="stack"><article className="panel"><SectionTitle eyebrow="Growth" title="New registrations" action={<Button variant="quiet">View analytics →</Button>}/><div className="chart" aria-label="New registrations over twelve months">{registrations.map((value, index) => <span className="chart-bar" key={value}><i style={{ height: `${value / 1.6}%` }}/><span>{["Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"][index]}</span></span>)}</div></article><article className="panel"><SectionTitle eyebrow="Recent activity" title="Platform audit" action={<Button variant="quiet">View audit log →</Button>}/><div className="audit-list"><Audit icon="✓" title="Organization activated" copy="Horizon Collective completed subscription verification." time="6 min ago"/><Audit icon="◌" title="Parser job retried" copy="Document job #PR-1048 succeeded on retry." time="19 min ago"/><Audit icon="♙" title="Admin role assigned" copy="Priya Shah was granted Organization Admin access." time="42 min ago"/><Audit icon="◇" title="Invoice paid" copy="Nexora Technologies · Professional plan." time="1 hr ago"/></div></article></div><aside className="stack"><article className="panel"><SectionTitle eyebrow="System health" title="Core services" action={<Badge tone="green">Healthy</Badge>}/><div className="health-list"><Health name="API & database" detail="99.99% uptime · 42 ms p95" value={98}/><Health name="Parser workers" detail="14 jobs in progress · 2m avg" value={86}/><Health name="Object storage" detail="4.8 TB of 20 TB allocated" value={24}/><Health name="Notification delivery" detail="99.7% delivered today" value={99}/></div></article><article className="panel"><SectionTitle eyebrow="Operations" title="Today at a glance"/><div className="ops-grid"><div className="ops-card"><span>New candidates</span><strong>124</strong><small className="positive">+12%</small></div><div className="ops-card"><span>Applications</span><strong>486</strong><small className="positive">+8%</small></div><div className="ops-card"><span>Failed jobs</span><strong>3</strong><small className="status-warning">Needs review</small></div></div></article></aside></section>
  </WorkspaceShell>;
}

function Audit({ icon, title, copy, time }: { icon: string; title: string; copy: string; time: string }) { return <div className="audit-row"><span className="audit-symbol">{icon}</span><div><strong>{title}</strong><p>{copy}</p></div><time>{time}</time></div>; }
function Health({ name, detail, value }: { name: string; detail: string; value: number }) { return <div className="health-row"><div><strong>{name}</strong><p>{detail}</p><Meter value={value} color={value > 95 ? "green" : value > 50 ? "blue" : "amber"}/></div><Badge tone={value > 90 ? "green" : value > 50 ? "blue" : "amber"}>{value > 90 ? "Healthy" : value > 50 ? "Normal" : "Capacity"}</Badge></div>; }
