"use client";

import { useState } from "react";
import { Button, Logo } from "./ui";

type Portal = "candidate" | "recruiter";

export function LoginPortal({ defaultPortal = "candidate" }: { defaultPortal?: Portal }) {
  const [portal, setPortal] = useState<Portal>(defaultPortal);
  const [step, setStep] = useState<"credentials" | "verify">("credentials");
  const target = portal === "candidate" ? "/candidate" : "/recruiter";
  return <AuthFrame eyebrow={portal === "candidate" ? "Candidate portal" : "Recruiter workspace"} title={step === "credentials" ? `Welcome back` : "Verify it’s you"} copy={step === "credentials" ? "Use the space built for your next career move." : "For your security, enter both verification codes before continuing."}>
    <div className="portal-switch" role="tablist" aria-label="Choose a portal"><button className={portal === "candidate" ? "active" : ""} onClick={() => { setPortal("candidate"); setStep("credentials"); }} role="tab" aria-selected={portal === "candidate"}>Candidate</button><button className={portal === "recruiter" ? "active" : ""} onClick={() => { setPortal("recruiter"); setStep("credentials"); }} role="tab" aria-selected={portal === "recruiter"}>Recruiter</button></div>
    {step === "credentials" ? <form className="auth-form" onSubmit={(event) => { event.preventDefault(); setStep("verify"); }}><AuthField label="Work email" type="email" placeholder={portal === "candidate" ? "you@example.com" : "you@company.com"}/><AuthField label="Password" type="password" placeholder="Enter your password"/><div className="auth-row"><label><input type="checkbox"/> Remember this device</label><a href="#forgot">Forgot password?</a></div><Button type="submit">Continue securely →</Button><p className="auth-microcopy">You’ll verify both your email and mobile before accessing your account.</p></form> : <DualOtp completeHref={target}/>} 
    <p className="auth-footer">New to Sapienworx? <a href={portal === "candidate" ? "/register" : "/recruiter/register"}>Create an account</a></p>
  </AuthFrame>;
}

export function RegistrationPortal({ portal = "candidate" }: { portal?: Portal }) {
  const [step, setStep] = useState<"details" | "verify" | "complete">("details");
  const [terms, setTerms] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [futureAi, setFutureAi] = useState(false);
  const isRecruiter = portal === "recruiter";
  return <AuthFrame eyebrow={isRecruiter ? "Recruiter registration" : "Candidate registration"} title={step === "details" ? (isRecruiter ? "Start your recruitment workspace." : "Create a profile with confidence.") : step === "verify" ? "Verify both contact methods" : "You’re securely verified"} copy={step === "details" ? (isRecruiter ? "Secure your team’s recruitment workspace with clear consent and account controls." : "Your information is yours. Start with clear choices about how Sapienworx uses it.") : step === "verify" ? "Dual-factor verification protects your account and the professional information in it." : (isRecruiter ? "Your secure recruiter workspace is ready for organization setup." : "Next, upload your CV to build a profile that you can review before it is saved.")}>
    {step === "details" && <form className="auth-form" onSubmit={(event) => { event.preventDefault(); if (terms && processing) setStep("verify"); }}><AuthField label="Full name" placeholder="Your full name"/><AuthField label="Email address" type="email" placeholder="you@example.com"/><AuthField label="Mobile number" type="tel" placeholder="+91 00000 00000"/><AuthField label="Password" type="password" placeholder="Create a strong password"/><section className="dpdp-notice"><strong>What we collect and why</strong><ul><li>Your account and contact details to secure your access and communicate about applications.</li><li>Your CV and profile details only to create your profile and connect you to recruitment workflows you choose.</li><li>Activity information to show you application progress and protect the platform.</li></ul><p>We store and process this information for these stated purposes, and record your consent choices.</p></section><label className="consent-row"><input checked={terms} onChange={(event) => setTerms(event.target.checked)} type="checkbox"/><span><b>I agree to the Terms of Service.</b><small>Required to create an account.</small></span></label><label className="consent-row"><input checked={processing} onChange={(event) => setProcessing(event.target.checked)} type="checkbox"/><span><b>I agree to the Data Processing Agreement.</b><small>Required to process my profile and applications.</small></span></label><label className="consent-row optional"><input checked={futureAi} onChange={(event) => setFutureAi(event.target.checked)} type="checkbox"/><span><b>I optionally allow anonymised corrections to improve future automated features.</b><small>This is not required and can be withdrawn in your settings at any time.</small></span></label>{(!terms || !processing) && <p className="consent-error">Accept the two required agreements to continue.</p>}<Button type="submit" disabled={!terms || !processing}>Continue to verification →</Button></form>}
    {step === "verify" && <DualOtp completeHref="#" onComplete={() => setStep("complete")}/>} 
    {step === "complete" && <div className="verified-state"><span>✓</span><h2>Account verified</h2><p>{isRecruiter ? "Your email and mobile have been verified. You can now create your organisation workspace." : "Your email and mobile have been verified. You can now safely continue to your resume intake."}</p><Button href={isRecruiter ? "/recruiter" : "/candidate/onboarding"}>{isRecruiter ? "Open recruiter workspace →" : "Upload your CV →"}</Button></div>}
    <p className="auth-footer">Already registered? <a href={isRecruiter ? "/recruiter/login" : "/login"}>Sign in</a></p>
  </AuthFrame>;
}

export function CandidateOnboarding() {
  const [text, setText] = useState("");
  const [parsed, setParsed] = useState<ReturnType<typeof import("../lib/parser/deterministic").parseResumeText> | null>(null);
  const [fileName, setFileName] = useState("");
  const parse = async () => { const { parseResumeText } = await import("../lib/parser/deterministic"); setParsed(parseResumeText(text)); };
  return <AuthFrame eyebrow="Secure resume intake" title="Build your profile from your CV" copy="Review every detail before it becomes part of your Sapienworx profile. The current preview uses a deterministic, non-AI text parser.">
    <div className="resume-intake"><label className="upload-target"><input type="file" accept=".txt,text/plain" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); const reader = new FileReader(); reader.onload = () => setText(String(reader.result ?? "")); reader.readAsText(file); }}/><span>⇧</span><strong>{fileName || "Choose a plain-text CV"}</strong><small>For this local demo, upload a .txt CV or paste its text below. PDF/DOCX extraction runs in the server-side parser worker.</small></label><label className="form-field"><span>Paste your CV text</span><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Paste a text version of your CV here…"/></label><Button onClick={parse} disabled={!text.trim()}>Extract profile details</Button></div>
    {parsed && <section className="parser-preview"><header><div><span className="eyebrow">Deterministic parser</span><h2>Review extracted details</h2></div><span className="parser-version">{parsed.parserVersion}</span></header><div className="parser-preview-grid"><ParserValue label="Name" value={parsed.name}/><ParserValue label="Email" value={parsed.email}/><ParserValue label="Phone" value={parsed.phone}/><ParserValue label="Headline" value={parsed.headline}/><ParserValue label="Skills" value={parsed.skills.join(", ")}/><ParserValue label="Certifications" value={parsed.certifications.join(", ")}/></div>{parsed.warnings.length > 0 && <div className="parser-warnings"><b>Check before you continue</b>{parsed.warnings.map((warning) => <span key={warning}>• {warning}</span>)}</div>}<Button href="/candidate/review">Review all extracted fields →</Button></section>}
  </AuthFrame>;
}

function ParserValue({ label, value }: { label: string; value?: string }) { return <div><span>{label}</span><strong>{value || "Not found"}</strong></div>; }
function AuthField({ label, placeholder, type = "text" }: { label: string; placeholder?: string; type?: string }) { return <label className="auth-field"><span>{label}</span><input required type={type} placeholder={placeholder}/></label>; }
function AuthFrame({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children: React.ReactNode }) { return <main className="auth-page"><header className="auth-nav"><Logo/><a href="/">Back to home</a></header><section className="auth-layout"><aside className="auth-aside"><span className="auth-aside-kicker">Sapienworx</span><h1>Recruitment that keeps <em>people</em> in control.</h1><p>Clear progress for candidates. Confident decisions for recruitment teams. Privacy built into the journey.</p><div className="auth-benefits"><span>✓ Human-confirmed profile data</span><span>✓ Two-factor account protection</span><span>✓ Clear data choices</span></div></aside><section className="auth-card"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="auth-copy">{copy}</p>{children}</section></section></main>; }

function DualOtp({ completeHref, onComplete }: { completeHref: string; onComplete?: () => void }) { const [complete, setComplete] = useState(false); const finish = () => { setComplete(true); onComplete?.(); }; return <div className="dual-otp"><div className="otp-method"><div><strong>Email code</strong><small>Sent to amara.mensah@email.com</small></div><OtpInputs label="Email verification code"/></div><div className="otp-method"><div><strong>Mobile code</strong><small>Sent to +91 ••••• 1982</small></div><OtpInputs label="Mobile verification code"/></div><Button href={complete ? completeHref : undefined} onClick={complete ? undefined : finish}>{complete ? "Continue →" : "Verify both codes"}</Button><p className="auth-microcopy">Codes expire after 10 minutes. We do not share them or store them as plain text.</p></div>; }
function OtpInputs({ label }: { label: string }) { return <div className="otp-inputs" aria-label={label}>{Array.from({ length: 6 }, (_, index) => <input key={index} inputMode="numeric" maxLength={1} aria-label={`${label} digit ${index + 1}`}/>)}</div>; }
