"use client";

import { useState } from "react";
import { Badge, Button, Meter, SectionTitle, StatCard, WorkspaceShell } from "./ui";

const applications = [
  { company: "Northstar", role: "Product Designer", stage: "Interview", tone: "green" as const, mark: "N", style: "" },
  { company: "Tandem", role: "Senior UX Designer", stage: "Screening", tone: "blue" as const, mark: "T", style: "dark" },
  { company: "Morrow", role: "Product Designer", stage: "Applied", tone: "neutral" as const, mark: "M", style: "orange" },
];

const recommendedJobs = [
  { id: "northstar", company: "Northstar Labs", role: "Product Designer", location: "London · Hybrid", type: "Full-time", salary: "£62k – £76k", posted: "Posted 2d ago", logo: "N", color: "", match: "94% match" },
  { id: "cascade", company: "Cascade", role: "Senior Product Designer", location: "Remote · United Kingdom", type: "Full-time", salary: "£68k – £82k", posted: "Posted 3d ago", logo: "C", color: "blue", match: "91% match" },
  { id: "plume", company: "Plume Health", role: "Product Designer", location: "Manchester · Hybrid", type: "Permanent", salary: "£55k – £68k", posted: "Posted 5d ago", logo: "P", color: "orange", match: "88% match" },
];

export function CandidateDashboard() {
  return <WorkspaceShell workspace="candidate" active="dashboard" title="Good morning, Amara" description="Here’s a clear view of your career journey.">
    <section className="candidate-welcome"><div><span className="eyebrow">Candidate dashboard</span><h2>You&apos;re closer than you think.</h2><p>Track every application, recruiter update and next step from one private workspace.</p></div><Button href="/candidate/jobs" variant="secondary">Explore jobs →</Button></section>
    <section className="candidate-stat-grid"><StatCard label="Active applications" value="3" change="1 interview this week" icon="◫"/><StatCard label="Profile strength" value="82%" change="4 suggested updates" tone="green" icon="✦"/><StatCard label="New recruiter activity" value="2" change="Since your last visit" tone="purple" icon="◌"/></section>
    <div className="page-grid" style={{ marginTop: 25 }}>
      <div className="stack">
        <section className="panel"><SectionTitle eyebrow="Your profile" title="Profile strength" action={<Button href="/candidate/profile" variant="quiet">Complete profile →</Button>} /><div className="completion-layout"><div className="completion-circle" aria-label="Profile completion: 82 percent"/><div><strong style={{ fontSize: 14 }}>A complete profile gets more relevant recruiter attention.</strong><p className="muted" style={{ margin: "4px 0 10px", fontSize: 12 }}>Add a certificate and rate your skills to complete your profile.</p><Meter value={82}/></div></div><div className="action-list"><a className="action-link" href="/candidate/profile"><b>1</b>Add your latest certification <span>→</span></a><a className="action-link" href="/candidate/profile"><b>2</b>Confirm skill ratings and portfolio links <span>→</span></a></div></section>
        <section className="panel"><SectionTitle eyebrow="Your activity" title="Applications" action={<Button href="/candidate/jobs" variant="quiet">Find more jobs →</Button>} /><div className="application-status">{applications.map((application) => <div className="application-row" key={application.company}><span className={`company-mark ${application.style}`}>{application.mark}</span><div><strong>{application.role}</strong><small>{application.company} · Updated today</small></div><Badge tone={application.tone}>{application.stage}</Badge></div>)}</div></section>
      </div>
      <aside className="stack">
        <section className="panel live-updates-card"><SectionTitle eyebrow="Recruiter activity" title="Live notifications" action={<Button href="/candidate/notifications" variant="quiet">View all →</Button>} /><div className="live-update"><span>●</span><div><strong>Northstar viewed your application</strong><small>Just now · Product Designer</small></div></div><div className="live-update"><span>●</span><div><strong>Interview invitation received</strong><small>12 min ago · View your calendar</small></div></div><p className="live-update-note">Only activity related to your applications and profile appears here.</p></section>
        <section className="panel"><SectionTitle eyebrow="Next up" title="Your schedule" action={<Button href="/candidate/notifications" variant="quiet">Calendar →</Button>} /><div className="schedule-mini"><span className="schedule-date"><b>22</b><small>AUG</small></span><div><strong>Northstar portfolio conversation</strong><small>Friday · 10:30 AM · Video call</small></div></div></section>
        <section className="panel"><SectionTitle eyebrow="Recommended for you" title="Matches this week" /><div className="job-mini-list">{recommendedJobs.slice(0, 2).map((job) => <div className="job-mini" key={job.id}><span className="stripe"/><div><strong>{job.role}</strong><small>{job.company} · {job.location}</small></div><a href="/candidate/jobs" className="button button-quiet">View</a></div>)}</div></section>
      </aside>
    </div>
  </WorkspaceShell>;
}

export function ResumeReview() {
  const [confirmed, setConfirmed] = useState(false);
  return <WorkspaceShell workspace="candidate" active="resume" title="Review your CV details" description="Confirm every extracted field before it becomes part of your candidate profile." actions={<Button href="/candidate/profile" variant="secondary">Open profile</Button>}>
    <div className="review-intro"><span>✦</span><div><b>{confirmed ? "Your confirmed details are now in your profile." : "Your profile is unchanged until you confirm the information below."}</b> Field confidence is a guide only. Please check each item against your original CV.</div>{confirmed && <Badge tone="green">Profile updated</Badge>}</div>
    <section className="review-layout"><aside className="document-pane" aria-label="Original uploaded resume"><div className="document-toolbar"><span>Amara_Mensah_Resume.pdf</span><span>− &nbsp; 100% &nbsp; +</span></div><article className="document-paper"><h2>Amara Mensah</h2><div className="document-contact">Product Designer · London, UK · amara.mensah@email.com</div><h3>Profile</h3><p>Product designer with 6+ years creating intuitive digital experiences for people and growing teams.</p><h3>Experience</h3><div className="document-job"><strong>Senior Product Designer · Northstar Labs</strong><p>Jan 2022 – Present · London, UK</p><p>Leading end-to-end experience design for an analytics platform used by 20,000+ customers.</p></div><h3>Education</h3><p><strong>BA Interaction Design</strong> · University of the Arts London · 2016 – 2019</p><h3>Skills</h3><p>Product strategy · Figma · Prototyping · Research · Design systems</p></article></aside><form className="review-form" onSubmit={(event) => { event.preventDefault(); setConfirmed(true); }}><header className="review-form-head"><div><h2>Extracted details</h2><p>Edit, accept or correct the information found in your CV.</p></div><Badge tone="green">5 sections found</Badge></header><div className="review-section"><div className="review-section-title"><h3>Personal information</h3><span className="confidence high">● High confidence</span></div><div className="review-fields"><Field label="Full name" defaultValue="Amara Mensah"/><Field label="Email" defaultValue="amara.mensah@email.com"/><Field label="Phone" defaultValue="+44 7700 900 112"/><Field label="Location" defaultValue="London, United Kingdom"/></div></div><div className="review-section"><div className="review-section-title"><h3>Most recent experience</h3><span className="confidence high">● High confidence</span></div><div className="review-fields"><Field label="Company" defaultValue="Northstar Labs"/><Field label="Role" defaultValue="Senior Product Designer"/><Field label="Start date" defaultValue="January 2022"/><Field label="End date" defaultValue="Present"/><Field label="Roles and responsibilities" defaultValue="Leading end-to-end experience design for an analytics platform used by 20,000+ customers." multiline wide/></div></div><footer className="review-footer"><p>By confirming, you choose which parsed details become part of your Sapienworx profile.</p><div><Button href="/candidate" variant="secondary">Cancel</Button><Button type="submit">{confirmed ? "Confirmed" : "Confirm and update profile"}</Button></div></footer></form></section>
  </WorkspaceShell>;
}

function Field({ label, defaultValue, wide = false, multiline = false }: { label: string; defaultValue: string; wide?: boolean; multiline?: boolean }) { return <div className={`review-field ${wide ? "wide" : ""}`}><label>{label}</label>{multiline ? <textarea defaultValue={defaultValue}/> : <input defaultValue={defaultValue}/>}</div>; }

type CandidateJob = { id: string; company: string; role: string; skills: string[]; location: string; type: string; minimumExperience: number; maximumExperience: number; minimumSalary: number; maximumSalary: number; postedDays: number; logo: string; color: string; match: string };

const jobListings: CandidateJob[] = [
  { id: "northstar", company: "Northstar Labs", role: "Product Designer", skills: ["Figma", "Research", "Design systems"], location: "London", type: "Hybrid", minimumExperience: 5, maximumExperience: 7, minimumSalary: 62, maximumSalary: 76, postedDays: 2, logo: "N", color: "", match: "94% match" },
  { id: "cascade", company: "Cascade", role: "Senior Product Designer", skills: ["Figma", "B2B", "Prototyping"], location: "Remote", type: "Remote", minimumExperience: 5, maximumExperience: 8, minimumSalary: 68, maximumSalary: 82, postedDays: 3, logo: "C", color: "blue", match: "91% match" },
  { id: "plume", company: "Plume Health", role: "Product Designer", skills: ["UX", "Healthcare", "Research"], location: "Manchester", type: "Hybrid", minimumExperience: 3, maximumExperience: 5, minimumSalary: 55, maximumSalary: 68, postedDays: 5, logo: "P", color: "orange", match: "88% match" },
  { id: "kinetic", company: "Kinetic", role: "Product Analyst", skills: ["SQL", "Analytics", "Tableau"], location: "London", type: "Hybrid", minimumExperience: 2, maximumExperience: 4, minimumSalary: 48, maximumSalary: 60, postedDays: 1, logo: "K", color: "purple", match: "86% match" },
  { id: "morrow", company: "Morrow", role: "Product Manager", skills: ["Strategy", "SaaS", "Discovery"], location: "Remote", type: "Remote", minimumExperience: 4, maximumExperience: 6, minimumSalary: 65, maximumSalary: 80, postedDays: 12, logo: "M", color: "orange", match: "81% match" },
  { id: "halcyon", company: "Halcyon", role: "Design Systems Lead", skills: ["Design systems", "Figma", "Accessibility"], location: "Bristol", type: "Hybrid", minimumExperience: 6, maximumExperience: 9, minimumSalary: 72, maximumSalary: 88, postedDays: 20, logo: "H", color: "blue", match: "79% match" },
];

type JobFilters = { query: string; minimumExperience: string; maximumExperience: string; minimumSalary: string; maximumSalary: string; location: string; postedWithin: string; company: string };
const emptyFilters: JobFilters = { query: "", minimumExperience: "", maximumExperience: "", minimumSalary: "", maximumSalary: "", location: "", postedWithin: "", company: "" };

export function CandidateJobs() {
  const [filters, setFilters] = useState<JobFilters>(emptyFilters);
  const [saved, setSaved] = useState<string[]>([]);
  const [applied, setApplied] = useState<string | null>(null);
  const setFilter = (key: keyof JobFilters, value: string) => setFilters({ ...filters, [key]: value });
  const visibleJobs = jobListings.filter((job) => {
    const searchable = `${job.role} ${job.company} ${job.skills.join(" ")}`.toLowerCase();
    return (!filters.query || searchable.includes(filters.query.toLowerCase())) && (!filters.minimumExperience || job.maximumExperience >= Number(filters.minimumExperience)) && (!filters.maximumExperience || job.minimumExperience <= Number(filters.maximumExperience)) && (!filters.minimumSalary || job.maximumSalary >= Number(filters.minimumSalary)) && (!filters.maximumSalary || job.minimumSalary <= Number(filters.maximumSalary)) && (!filters.location || job.location === filters.location) && (!filters.company || job.company === filters.company) && (!filters.postedWithin || job.postedDays <= Number(filters.postedWithin));
  });
  return <WorkspaceShell workspace="candidate" active="jobs" title="Find work that fits" description="Search by title, skills, experience, salary, location, date and company.">
    {applied && <div className="applied-banner">Your application for <strong>{jobListings.find((job) => job.id === applied)?.role}</strong> has been registered. The recruiter&apos;s activity will appear in Notifications.</div>}
    <section className="candidate-job-search panel"><div className="candidate-filter-title"><div><span className="eyebrow">Job board</span><h2>Refine your search</h2></div><Button onClick={() => setFilters(emptyFilters)} variant="quiet">Clear all</Button></div><div className="candidate-filter-grid"><FilterControl label="Job title or keywords" value={filters.query} onChange={(value) => setFilter("query", value)} placeholder="e.g. Product designer, Figma"/><SelectControl label="Min. experience" value={filters.minimumExperience} onChange={(value) => setFilter("minimumExperience", value)} options={[["", "Any"], ["0", "0 years"], ["2", "2 years"], ["4", "4 years"], ["6", "6 years"]]}/><SelectControl label="Max. experience" value={filters.maximumExperience} onChange={(value) => setFilter("maximumExperience", value)} options={[["", "Any"], ["3", "3 years"], ["5", "5 years"], ["7", "7 years"], ["10", "10+ years"]]}/><SelectControl label="Min. salary" value={filters.minimumSalary} onChange={(value) => setFilter("minimumSalary", value)} options={[["", "Any"], ["40", "£40k"], ["60", "£60k"], ["80", "£80k"]]}/><SelectControl label="Max. salary" value={filters.maximumSalary} onChange={(value) => setFilter("maximumSalary", value)} options={[["", "Any"], ["60", "£60k"], ["80", "£80k"], ["100", "£100k+"]]}/><SelectControl label="Location" value={filters.location} onChange={(value) => setFilter("location", value)} options={[["", "All locations"], ["London", "London"], ["Manchester", "Manchester"], ["Bristol", "Bristol"], ["Remote", "Remote"]]}/><SelectControl label="Posted on" value={filters.postedWithin} onChange={(value) => setFilter("postedWithin", value)} options={[["", "Any time"], ["1", "Past 24 hours"], ["3", "Past 3 days"], ["7", "Past 7 days"], ["30", "Past 30 days"]]}/><SelectControl label="Company" value={filters.company} onChange={(value) => setFilter("company", value)} options={[["", "All companies"], ...Array.from(new Set(jobListings.map((job) => job.company))).map((company) => [company, company])]} /></div></section>
    <section className="job-browser job-browser-full"><div><SectionTitle title={`${visibleJobs.length} roles for you`} action={<span className="muted" style={{ fontSize: 11 }}>Sorted by relevance</span>} /><div className="job-list">{visibleJobs.map((job) => <article className="job-card" key={job.id}><span className={`job-logo ${job.color}`}>{job.logo}</span><div><h3>{job.role}</h3><p>{job.company}</p><div className="candidate-job-tags">{job.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="job-meta"><span>{job.minimumExperience}–{job.maximumExperience} years</span><span>{job.location} · {job.type}</span><span>£{job.minimumSalary}k–£{job.maximumSalary}k</span><span>Posted {job.postedDays === 1 ? "today" : `${job.postedDays}d ago`}</span></div></div><div className="job-card-actions"><button aria-label={`Save ${job.role}`} onClick={() => setSaved((current) => current.includes(job.id) ? current.filter((id) => id !== job.id) : [...current, job.id])} className={`save-button ${saved.includes(job.id) ? "saved" : ""}`}>{saved.includes(job.id) ? "♥" : "♡"}</button>{applied === job.id ? <Badge tone="green">Applied</Badge> : <Button onClick={() => setApplied(job.id)}>Quick apply</Button>}<small className="positive">{job.match}</small></div></article>)}{visibleJobs.length === 0 && <div className="empty-inline"><strong>No roles match those filters.</strong><p>Try widening your experience, salary or location range.</p><Button onClick={() => setFilters(emptyFilters)} variant="secondary">Reset filters</Button></div>}</div></div></section>
  </WorkspaceShell>;
}

function FilterControl({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="candidate-filter-control"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder}/></label>; }
function SelectControl({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <label className="candidate-filter-control"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
