"use client";
import { useEffect, useMemo, useState } from "react";
import { apiClient } from "../lib/api-client";
import { Button, Logo } from "./ui";

type Profile = { fullName:string; headline:string|null; location:string|null; currentCompany:string|null; skills:Array<{skill:string}>; preferredLocations:string[]; profileSummary:string|null; cvAvailable:boolean };
type Step = 0|1|2|3;
const steps=["Resume","Review","Preferences","Done"] as const;

export function CandidateOnboardingV1(){
 const [step,setStep]=useState<Step>(0); const [file,setFile]=useState<File|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [skills,setSkills]=useState(""); const [locations,setLocations]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const load=async()=>{try{const value=await apiClient<Profile>("/api/candidate/profile");setProfile(value);setSkills(value.skills.map(s=>s.skill).join(", "));setLocations(value.preferredLocations.join(", "));}catch{/* profile may not exist until onboarding completes */}};
 useEffect(()=>{void load()},[]);
 const fields=useMemo(()=>[{label:"Name",value:profile?.fullName||"",required:true},{label:"Current role",value:profile?.headline||"",required:true},{label:"Current company",value:profile?.currentCompany||"",required:false},{label:"Location",value:profile?.location||"",required:true}], [profile]);
 const upload=async()=>{if(!file){setStep(1);return}setBusy(true);setError("");try{const body=new FormData();body.set("file",file);await apiClient("/api/candidate/cv",{method:"POST",body});await load();setStep(1);}catch(reason){setError(reason instanceof Error?reason.message:"We could not upload this CV. You can continue and complete your profile manually.");}finally{setBusy(false)}};
 const savePrefs=async()=>{setBusy(true);setError("");try{await apiClient("/api/candidate/profile",{method:"PATCH",body:JSON.stringify({skills:skills.split(",").map(skill=>skill.trim()).filter(Boolean).map(skill=>({skill,rating:3})),preferredLocations:locations.split(",").map(v=>v.trim()).filter(Boolean)})});setStep(3);}catch(reason){setError(reason instanceof Error?reason.message:"We could not save those preferences.");}finally{setBusy(false)}};
 const next=()=>{if(step===0)void upload();else if(step===1)setStep(2);else if(step===2)void savePrefs();};
 return <main className="candidate-onboarding-v1"><header><Logo/><nav aria-label="Onboarding progress">{steps.map((label,index)=><span key={label} className={index===step?"current":index<step?"complete":""}><i aria-hidden="true">{index<step?"✓":index+1}</i>{label}</span>)}</nav></header><section className="candidate-onboarding-card">
 {step===0&&<><span className="eyebrow">Step 1 of 4</span><h1>Start with your CV</h1><p>Upload a PDF or document to request profile extraction, or continue without one. You remain in control of every suggested field.</p><label className="candidate-upload-drop"><span>{file?file.name:"Choose your CV"}</span><input type="file" accept=".pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]??null)}/><small>No field is treated as confirmed until you review it.</small></label></>}
 {step===1&&<><span className="eyebrow">Step 2 of 4</span><h1>Review what was detected</h1><p>Confidence is shown as a review state, not a fabricated percentage. Detected fields can still be corrected from your profile.</p><div className="candidate-confidence-list">{fields.map(field=><article className={field.value?"detected":"needs-review"} key={field.label}><div><strong>{field.label}</strong><span>{field.value||"Not detected"}</span></div><b>{field.value?"Detected — review":"Needs confirmation"}</b></article>)}</div><p className="candidate-confidence-note">Green means a usable value was detected. Amber means the field needs your confirmation. This does not represent model certainty.</p></>}
 {step===2&&<><span className="eyebrow">Step 3 of 4</span><h1>Set skills and preferences</h1><p>These professional criteria help relevant jobs and recruiters find you without using protected personal attributes.</p><label className="form-field"><span>Key skills</span><input value={skills} onChange={e=>setSkills(e.target.value)} placeholder="Java, Spring Boot, PostgreSQL"/><small>Separate skills with commas.</small></label><label className="form-field"><span>Preferred locations</span><input value={locations} onChange={e=>setLocations(e.target.value)} placeholder="Mumbai, Pune, Remote"/><small>Separate locations with commas.</small></label></>}
 {step===3&&<><span className="eyebrow">Profile setup</span><h1>You’re ready to continue.</h1><p>Your profile can keep improving over time. Review visibility and contact choices before making it searchable.</p><div className="candidate-onboarding-done"><span aria-hidden="true">✓</span><div><strong>Core setup complete</strong><p>Next, review your full profile or start exploring current roles.</p></div></div><div className="candidate-onboarding-final"><Button href="/candidate/profile" variant="secondary">Review profile</Button><Button href="/candidate/jobs">Find jobs</Button></div></>}
 {error&&<p className="error-state" role="alert">{error}</p>}
 </section>{step<3&&<footer className="candidate-onboarding-actions">{step>0?<button type="button" className="button button-quiet" onClick={()=>setStep((step-1) as Step)}>Back</button>:<span/>}<button type="button" className="button button-primary" disabled={busy} onClick={next}>{busy?"Working…":step===0?(file?"Upload and continue":"Continue without CV"):step===1?"Confirm and continue":"Save and continue"}</button></footer>}</main>;
}
