"use client";
import { useEffect, useState } from "react";
import { apiBaseUrl, apiClient } from "../lib/api-client";
import { Button, SectionTitle, WorkspaceShell } from "./ui";
import { AccountSecurity } from "./account-security";

type CandidatePrivacy={profileSearchable:boolean;automationConsent:boolean;outreachOptOut:boolean;sensitiveDataConsent:boolean;dataExportRequestedAt:string|null;deletionRequestedAt:string|null;updatedAt:string};
type NotificationPrefs={emailApplications:boolean;emailInterviews:boolean;emailMessages:boolean;quietHours:boolean;quietStart:string;quietEnd:string};
const defaults:NotificationPrefs={emailApplications:true,emailInterviews:true,emailMessages:true,quietHours:false,quietStart:"22:00",quietEnd:"08:00"};
const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)):null;

export function CandidateSettings(){
 const [privacy,setPrivacy]=useState<CandidatePrivacy|null>(null);const [loading,setLoading]=useState(true);const [working,setWorking]=useState("");const [notice,setNotice]=useState("");const [error,setError]=useState("");const [reloadToken,setReloadToken]=useState(0);const [notifications,setNotifications]=useState<NotificationPrefs>(defaults);
 useEffect(()=>{try{const stored=window.localStorage.getItem("sapienworx.candidate.notification-preferences");if(stored)setNotifications({...defaults,...JSON.parse(stored)});}catch{}},[]);
 useEffect(()=>{let active=true;setLoading(true);setError("");void apiClient<CandidatePrivacy>("/api/candidate/privacy").then(r=>{if(active)setPrivacy(r)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"We could not load your privacy choices.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reloadToken]);
 const update=async(payload:Partial<Pick<CandidatePrivacy,"profileSearchable"|"automationConsent"|"outreachOptOut"|"sensitiveDataConsent">>,success:string)=>{setWorking("update");setNotice("");setError("");try{setPrivacy(await apiClient<CandidatePrivacy>("/api/candidate/privacy",{method:"PATCH",body:JSON.stringify(payload)}));setNotice(success)}catch(reason){setError(reason instanceof Error?reason.message:"The request could not be completed.")}finally{setWorking("")}};
 const request=async(path:"data-export"|"deletion-request",success:string)=>{setWorking(path);setNotice("");setError("");try{setPrivacy(await apiClient<CandidatePrivacy>(`/api/candidate/privacy/${path}`,{method:"POST"}));setNotice(success)}catch(reason){setError(reason instanceof Error?reason.message:"The request could not be completed.")}finally{setWorking("")}};
 const saveNotifications=(next:NotificationPrefs)=>{setNotifications(next);window.localStorage.setItem("sapienworx.candidate.notification-preferences",JSON.stringify(next));setNotice("Notification preferences saved on this device.")};
 return <WorkspaceShell workspace="candidate" active="settings" title="Settings and privacy" description="Manage account choices, notifications, privacy rights and signed-in sessions."><div className="settings-layout candidate-privacy-live">
   <nav className="settings-anchor-nav" aria-label="Settings sections"><a href="#account">Account</a><a href="#notifications">Notifications</a><a href="#privacy">Privacy & data</a><a href="#sessions">Sessions</a></nav>
   {error&&!privacy&&!loading?<section className="panel settings-recovery" role="alert"><h2>Your privacy choices are safe</h2><p>{error}</p><Button variant="secondary" onClick={()=>setReloadToken(v=>v+1)}>Try again</Button></section>:<>
   <section className="panel" id="account"><SectionTitle eyebrow="Account" title="Account preferences"/>{loading&&<p role="status">Loading your account choices…</p>}{privacy&&<><div className="settings-row"><div><strong>Profile visibility</strong><p>{privacy.profileSearchable?"Recruiters can discover your professional profile. Contact details remain protected.":"Your profile is private in sourcing. You can still apply directly."}</p></div><label className="privacy-toggle"><input type="checkbox" checked={privacy.profileSearchable} disabled={working==="update"} onChange={e=>void update({profileSearchable:e.target.checked},e.target.checked?"Your professional profile is now searchable.":"Your profile is now private in sourcing.")}/><span><b>{privacy.profileSearchable?"Visible in sourcing":"Private in sourcing"}</b><small>Change this at any time.</small></span></label></div><div className="settings-row"><div><strong>Contact details</strong><p>Email and mobile verification protect access to your account.</p></div><Button href="/candidate/profile" variant="quiet">View profile</Button></div></>}</section>
   <section className="panel" id="notifications"><SectionTitle eyebrow="Notifications" title="Channels and quiet hours"/><p className="settings-intro">Choose which non-essential updates you want by email. Essential security messages are always sent. These preferences are device-local until account-level notification storage is enabled.</p>{[["Application updates","emailApplications"],["Interview updates","emailInterviews"],["Recruiter messages","emailMessages"]].map(([label,key])=><label className="privacy-toggle" key={key}><input type="checkbox" checked={notifications[key as keyof NotificationPrefs] as boolean} onChange={e=>saveNotifications({...notifications,[key]:e.target.checked})}/><span><b>{label}</b><small>Email me when this activity changes.</small></span></label>)}<label className="privacy-toggle"><input type="checkbox" checked={notifications.quietHours} onChange={e=>saveNotifications({...notifications,quietHours:e.target.checked})}/><span><b>Quiet hours</b><small>Reduce non-essential notification interruptions during your chosen window.</small></span></label>{notifications.quietHours&&<div className="settings-quiet-hours"><label className="form-field"><span>From</span><input type="time" value={notifications.quietStart} onChange={e=>saveNotifications({...notifications,quietStart:e.target.value})}/></label><label className="form-field"><span>Until</span><input type="time" value={notifications.quietEnd} onChange={e=>saveNotifications({...notifications,quietEnd:e.target.value})}/></label></div>}</section>
   <section className="panel privacy-panel" id="privacy"><SectionTitle eyebrow="Privacy & data" title="Your controls and requests"/><p className="settings-intro">Your account records these choices. Protected personal details are never sourcing or ranking criteria.</p>{error&&<p className="candidate-privacy-error" role="alert">{error}</p>}{notice&&<p className="candidate-privacy-notice" role="status">{notice}</p>}{privacy&&<><label className="privacy-toggle"><input type="checkbox" checked={privacy.sensitiveDataConsent} disabled={working==="update"} onChange={e=>void update({sensitiveDataConsent:e.target.checked},e.target.checked?"Optional personal-data consent recorded.":"Optional personal-data consent withdrawn.")}/><span><b>Optional personal and inclusion details</b><small>{privacy.sensitiveDataConsent?"Enabled by your choice. You can withdraw at any time.":"Disabled."}</small></span></label><label className="privacy-toggle"><input type="checkbox" checked={privacy.outreachOptOut} disabled={working==="update"} onChange={e=>void update({outreachOptOut:e.target.checked},e.target.checked?"Recruiter campaign outreach is off.":"Relevant recruiter campaign outreach is allowed.")}/><span><b>Campaign outreach</b><small>{privacy.outreachOptOut?"Opted out of future campaigns.":"Allowed for relevant opportunities."}</small></span></label><button className="privacy-link" disabled={working==="data-export"} onClick={()=>void request("data-export","Your data export request has been recorded.")}>Request a copy of my data <span>→</span></button>{formatDate(privacy.dataExportRequestedAt)&&<p className="settings-feedback"><b>Export requested</b><br/>Recorded {formatDate(privacy.dataExportRequestedAt)}.<br/><a href={`${apiBaseUrl}/api/candidate/privacy/data-export/download`} target="_blank" rel="noreferrer">Download secure copy →</a></p>}<button className="privacy-link danger" disabled={working==="deletion-request"||Boolean(privacy.deletionRequestedAt)} onClick={()=>void request("deletion-request","Your deletion request has been recorded. Identity confirmation is required before irreversible erasure.")}>Request deletion of my account and data <span>→</span></button><ol className="deletion-status-stepper" aria-label="Account deletion status"><li className={privacy.deletionRequestedAt?"complete":"current"}><span>1</span><div><b>Requested</b><small>{privacy.deletionRequestedAt?formatDate(privacy.deletionRequestedAt):"No request recorded"}</small></div></li><li className={privacy.deletionRequestedAt?"current":""}><span>2</span><div><b>Grace period</b><small>{privacy.deletionRequestedAt?"Awaiting secure confirmation and processing.":"Starts after a verified request."}</small></div></li><li><span>3</span><div><b>Completed</b><small>Shown only after backend confirmation of erasure.</small></div></li></ol></>}</section>
   <div id="sessions"><AccountSecurity candidate/></div></>}
 </div></WorkspaceShell>;
}
