"use client";

import { useState } from "react";
import { Badge, Button, Meter, SectionTitle, WorkspaceShell } from "./ui";

const links = [
  { label: "LinkedIn", value: "linkedin.com/in/amara-mensah", icon: "in" },
  { label: "Portfolio", value: "amaramensah.design", icon: "◌" },
  { label: "GitHub", value: "github.com/amara-mensah", icon: "⌘" },
  { label: "LeetCode", value: "leetcode.com/amara-mensah", icon: "⌁" },
];

export function CandidateProfile() {
  const [aiConsent, setAiConsent] = useState(false);
  const [deletionRequested, setDeletionRequested] = useState(false);
  const [saved, setSaved] = useState(false);
  return <WorkspaceShell workspace="candidate" active="profile" title="Your professional profile" description="The details recruiters see when you choose to apply or share your profile." actions={<Button onClick={() => setSaved(true)}>{saved ? "Changes saved" : "Save changes"}</Button>}>
    {saved && <div className="creation-success">Your profile has been updated. This activity will appear in your profile history.</div>}
    <section className="profile-hero panel"><div className="profile-avatar">AM</div><div><h2>Amara Mensah <Badge tone="green">Profile visible</Badge></h2><p>Senior Product Designer · London, United Kingdom</p><div className="profile-hero-meta"><span>6 years experience</span><span>Open to hybrid roles</span><span>Available in 30 days</span></div></div><div className="profile-completion"><strong>82%</strong><span>Profile complete</span><Meter value={82}/></div></section>
    <div className="profile-layout"><div className="stack"><section className="panel"><SectionTitle eyebrow="Your story" title="Professional summary" action={<Button variant="quiet">Edit</Button>}/><p className="profile-copy">Product designer with 6+ years of experience creating intuitive, inclusive digital products for people and growing teams. I bring product strategy, research and polished interface design together.</p></section><section className="panel"><SectionTitle eyebrow="Experience" title="Work history" action={<Button variant="quiet">+ Add experience</Button>}/><div className="profile-timeline"><Timeline role="Senior Product Designer" company="Northstar Labs" dates="Jan 2022 – Present" copy="Leading end-to-end design for an analytics platform used by more than 20,000 customers."/><Timeline role="Product Designer" company="Halcyon Studio" dates="Jun 2019 – Dec 2021" copy="Designed B2B workflows and a scalable interface library for enterprise teams."/></div></section><section className="panel"><SectionTitle eyebrow="Credentials" title="Education and certifications" action={<Button variant="quiet">+ Add</Button>}/><div className="credentials-grid"><article><span>BA</span><div><strong>BA Interaction Design</strong><p>University of the Arts London · 2016 – 2019</p></div></article><article><span>IxDF</span><div><strong>UX Management</strong><p>Interaction Design Foundation · Issued 2023</p></div></article></div></section></div><aside className="stack"><section className="panel"><SectionTitle eyebrow="Expertise" title="Skills" action={<Button variant="quiet">Edit</Button>}/><div className="skills-cloud">{["Product strategy", "Figma", "Research", "Design systems", "Prototyping", "Accessibility", "Analytics"].map((skill) => <span key={skill}>{skill}</span>)}</div></section><section className="panel"><SectionTitle eyebrow="Your work" title="Technical links" action={<Button variant="quiet">+ Add link</Button>}/><div className="link-list">{links.map((link) => <a href={`https://${link.value}`} target="_blank" rel="noreferrer" key={link.label}><span>{link.icon}</span><div><strong>{link.label}</strong><small>{link.value}</small></div><b>↗</b></a>)}</div></section><PrivacyControls aiConsent={aiConsent} setAiConsent={setAiConsent} deletionRequested={deletionRequested} setDeletionRequested={setDeletionRequested}/></aside></div>
  </WorkspaceShell>;
}

function Timeline({ role, company, dates, copy }: { role: string; company: string; dates: string; copy: string }) { return <article><span className="timeline-dot"/><div><strong>{role}</strong><p>{company} · {dates}</p><small>{copy}</small></div></article>; }
function PrivacyControls({ aiConsent, setAiConsent, deletionRequested, setDeletionRequested }: { aiConsent: boolean; setAiConsent: (value: boolean) => void; deletionRequested: boolean; setDeletionRequested: (value: boolean) => void }) { return <section className="panel privacy-panel"><SectionTitle eyebrow="Your data" title="Privacy controls"/><label className="privacy-toggle"><input type="checkbox" checked={aiConsent} onChange={(event) => setAiConsent(event.target.checked)}/><span><b>Future automation consent</b><small>{aiConsent ? "Optional consent recorded today. You may withdraw this at any time." : "Not enabled. Your data will not be considered for future improvement research."}</small></span></label><a href="#download-data" className="privacy-link">Download my data <span>→</span></a><button className="privacy-link danger" onClick={() => setDeletionRequested(true)}>Delete my account and data <span>→</span></button>{deletionRequested && <div className="deletion-state"><b>Deletion request started</b><p>A secure data-erasure request needs identity confirmation before processing. The completed backend workflow will hard-delete your profile, documents and parser metadata within the legal timeframe and retain only an anonymised audit hash.</p></div>}</section>; }
