import { Button, Logo } from "./ui";

export function Landing() {
  return <div className="landing">
    <header className="landing-nav"><Logo/><nav className="landing-links" aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="/candidate/jobs">Find jobs</a><a href="#employers">For employers</a></nav><div className="landing-nav-actions"><Button href="/login" variant="secondary">Sign in</Button><Button href="/register">Create profile</Button></div></header>
    <main>
      <section className="landing-hero"><div><span className="landing-eyebrow">A clearer way to build your career</span><h1>Find work that feels <span>like you.</span></h1><p className="landing-copy">Sapienworx brings your experience, opportunities and applications together—so you can spend less time filling forms and more time finding the right next move.</p><div className="hero-actions"><Button href="/register">Create your profile</Button><Button href="/candidate/jobs" variant="secondary">Browse jobs</Button></div><p className="hero-footnote"><strong>No pressure, no guesswork.</strong> Start with your resume and stay in control of every detail.</p></div><div className="hero-dashboard" aria-label="Preview of the candidate dashboard"><div className="hero-dash-head"><i className="browser-dot"/><i className="browser-dot"/><i className="browser-dot"/><span className="hero-dash-label">app.sapienworx.com/candidate</span></div><div className="hero-dash-body"><aside className="hero-dash-side"><span/><span/><span/><span/><span/></aside><div className="hero-dash-main"><div className="dash-greeting">Good morning, Amara</div><p className="dash-subtle">Your next opportunity is waiting.</p><div className="dash-progress"><span className="progress-ring"/><div><strong>Your profile is taking shape</strong><p>Review your resume details to reach more teams.</p></div></div><div className="hero-tiny-stats"><div><strong>3</strong><span>Active applications</span></div><div><strong>12</strong><span>New matches</span></div><div><strong>1</strong><span>Interview this week</span></div></div></div></div></div></section>
      <section className="landing-proof"><div className="proof-inner"><p>Built for people and teams who want hiring to feel more human, direct and organised.</p><div className="proof-logos"><span>northstar</span><span>cascade</span><span>HALCYON</span><span>kinetic</span></div></div></section>
      <section className="landing-section" id="how-it-works"><h2>One place for the whole journey.</h2><p>Candidate-first tools for finding your next role, and practical workspace tools for the teams hiring you.</p><div className="feature-grid"><article className="feature-card"><span>▤</span><h3>Your resume, made useful</h3><p>Upload a resume once. Sapienworx extracts the details, then you decide exactly what becomes part of your profile.</p></article><article className="feature-card"><span>⌕</span><h3>Relevant roles, clearly presented</h3><p>Find roles aligned to your skills and preferences, without losing track of the opportunities that matter.</p></article><article className="feature-card" id="employers"><span>⇄</span><h3>Hiring teams stay in sync</h3><p>Jobs, applications, pipeline stages and interviews live in one focused workspace for recruitment teams.</p></article></div></section>
    </main>
    <footer className="landing-footer"><Logo light/><small>© 2026 Sapienworx. Recruitment that works for people.</small><div><a href="/recruiter" style={{ marginRight: 16 }}>Recruiter demo</a><a href="/admin">Admin demo</a></div></footer>
  </div>;
}
