/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useState } from "react";
import { apiClient } from "../lib/api-client";
import { Badge, Button, SectionTitle } from "./ui";

type VerificationStatus = "DRAFT" | "PENDING_VERIFICATION" | "VERIFIED" | "NEEDS_INFORMATION" | "REJECTED" | "SUSPENDED";
type History = { id: string; actorType: string; action: string; decisionNote: string | null; createdAt: string };
type BrandForm = { legalName: string; displayName: string; websiteUrl: string; logoUrl: string; industry: string; companySize: string; headquarters: string; candidateDescription: string; linkedinUrl: string; registrationReference: string; brandColour: string };
export type OrganisationBrand = BrandForm & { organisationId: string; workEmailDomain: string | null; verificationStatus: VerificationStatus; verificationNote: string | null; verifiedAt: string | null; updatedAt: string | null; editable: boolean; history: History[] };

const empty: BrandForm = { legalName: "", displayName: "", websiteUrl: "", logoUrl: "", industry: "", companySize: "", headquarters: "", candidateDescription: "", linkedinUrl: "", registrationReference: "", brandColour: "#144A75" };
const formOf = (value: OrganisationBrand): BrandForm => ({ legalName: value.legalName ?? "", displayName: value.displayName ?? "", websiteUrl: value.websiteUrl ?? "", logoUrl: value.logoUrl ?? "", industry: value.industry ?? "", companySize: value.companySize ?? "", headquarters: value.headquarters ?? "", candidateDescription: value.candidateDescription ?? "", linkedinUrl: value.linkedinUrl ?? "", registrationReference: value.registrationReference ?? "", brandColour: value.brandColour || "#144A75" });
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const tone = (status: VerificationStatus) => status === "VERIFIED" ? "green" : status === "REJECTED" || status === "SUSPENDED" ? "rose" : status === "PENDING_VERIFICATION" || status === "NEEDS_INFORMATION" ? "amber" : "neutral";

function BrandFields({ form, onChange, disabled = false }: { form: BrandForm; onChange: (value: BrandForm) => void; disabled?: boolean }) {
  const field = (key: keyof BrandForm) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => onChange({ ...form, [key]: event.target.value });
  return <div className="brand-kit-fields">
    <label><span>Legal company name *</span><input value={form.legalName} onChange={field("legalName")} disabled={disabled} /></label>
    <label><span>Candidate-facing name *</span><input value={form.displayName} onChange={field("displayName")} disabled={disabled} /></label>
    <label><span>Company website *</span><input type="url" value={form.websiteUrl} onChange={field("websiteUrl")} placeholder="https://company.com" disabled={disabled} /></label>
    <label><span>Industry *</span><input value={form.industry} onChange={field("industry")} placeholder="Software & technology" disabled={disabled} /></label>
    <label><span>Company size *</span><select value={form.companySize} onChange={field("companySize")} disabled={disabled}><option value="">Choose company size</option>{["1–10", "11–50", "51–200", "201–500", "501–1,000", "1,001–5,000", "5,001+"].map((size) => <option key={size}>{size}</option>)}</select></label>
    <label><span>Headquarters *</span><input value={form.headquarters} onChange={field("headquarters")} placeholder="Bengaluru, India" disabled={disabled} /></label>
    <label><span>LinkedIn company page</span><input type="url" value={form.linkedinUrl} onChange={field("linkedinUrl")} placeholder="https://linkedin.com/company/..." disabled={disabled} /></label>
    <label><span>Registration reference</span><input value={form.registrationReference} onChange={field("registrationReference")} placeholder="Verification reference" disabled={disabled} /></label>
    <label className="span-all"><span>Approved logo asset</span><input type="url" value={form.logoUrl} onChange={field("logoUrl")} placeholder="https://company.com/brand/logo.png" disabled={disabled} /><small>Use a public HTTPS image owned by the company. It appears publicly only after verification.</small></label>
    <label><span>Brand colour</span><div className="brand-colour-field"><input type="color" value={form.brandColour} onChange={field("brandColour")} disabled={disabled} /><input value={form.brandColour} onChange={field("brandColour")} pattern="^#[0-9A-Fa-f]{6}$" disabled={disabled} /></div></label>
    <label className="span-all"><span>Candidate-facing company story *</span><textarea value={form.candidateDescription} onChange={field("candidateDescription")} maxLength={2000} placeholder="What does the company build, and why would thoughtful candidates care?" disabled={disabled} /><small>{form.candidateDescription.length}/2,000 characters</small></label>
  </div>;
}

function BrandPreview({ form, verified }: { form: BrandForm; verified: boolean }) {
  const initials = form.displayName.split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase() || "SW";
  return <article className="brand-kit-preview" style={{ "--company-colour": form.brandColour } as React.CSSProperties}><div className="brand-kit-mark">{form.logoUrl ? <><img src={form.logoUrl} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} /><span>{initials}</span></> : <span>{initials}</span>}</div><div><small>Candidate view</small><h3>{form.displayName || "Company name"} {verified && <i title="Verified company">✓</i>}</h3><p>{form.industry || "Industry"} · {form.headquarters || "Headquarters"}</p><blockquote>{form.candidateDescription || "A clear, specific company story will appear across jobs and share cards."}</blockquote></div></article>;
}

function HistoryList({ history }: { history: History[] }) {
  if (!history.length) return null;
  return <details className="brand-history"><summary>Review history ({history.length})</summary>{history.map((item) => <div key={item.id}><b>{pretty(item.action)}</b><span>{new Date(item.createdAt).toLocaleString()} · {pretty(item.actorType)}</span>{item.decisionNote && <p>{item.decisionNote}</p>}</div>)}</details>;
}

export function RecruiterOrganisationBrandKit() {
  const [profile, setProfile] = useState<OrganisationBrand | null>(null); const [form, setForm] = useState<BrandForm>(empty);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { try { setLoading(true); const value = await apiClient<OrganisationBrand>("/api/recruiter/organisation-brand"); setProfile(value); setForm(formOf(value)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Company identity could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const save = async (submitForVerification: boolean) => { try { setSaving(true); setError(""); setNotice(""); const value = await apiClient<OrganisationBrand>("/api/recruiter/organisation-brand", { method: "PUT", body: JSON.stringify({ ...form, submitForVerification }) }); setProfile(value); setForm(formOf(value)); setNotice(submitForVerification ? "Company identity submitted to Master Admin for verification." : "Company identity draft saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Company identity could not be saved."); } finally { setSaving(false); } };
  if (loading) return <section className="panel"><p className="workflow-loading">Loading company identity…</p></section>;
  if (!profile) return <section className="panel"><p className="workflow-error" role="alert">{error || "Company identity is unavailable."}</p><Button variant="secondary" onClick={() => void load()}>Try again</Button></section>;
  return <section className="panel brand-kit-panel"><SectionTitle eyebrow="Identity & Brand Kit" title="The company candidates will recognise" action={<Badge tone={tone(profile.verificationStatus)}>{pretty(profile.verificationStatus)}</Badge>} /><p>One approved identity powers public jobs, social cards, applications, interviews, offers, and recruiter communications.</p>{profile.workEmailDomain && <p className="brand-domain-proof"><b>Domain evidence</b> {profile.workEmailDomain}</p>}{profile.verificationNote && <p className="brand-review-note"><b>Review note</b> {profile.verificationNote}</p>}{error && <p className="workflow-error" role="alert">{error}</p>}{notice && <p className="workflow-notice" role="status">{notice}</p>}<div className="brand-kit-layout"><div><BrandFields form={form} onChange={setForm} disabled={!profile.editable || saving} /><div className="brand-kit-actions"><Button variant="secondary" disabled={!profile.editable || saving} onClick={() => void save(false)}>Save draft</Button><Button disabled={!profile.editable || saving} onClick={() => void save(true)}>{saving ? "Saving…" : "Submit for verification"}</Button></div>{!profile.editable && <p>Only an organisation administrator can propose company identity changes.</p>}</div><BrandPreview form={form} verified={profile.verificationStatus === "VERIFIED"} /></div><HistoryList history={profile.history} /></section>;
}

export function AdminOrganisationBrandReview() {
  const [profiles, setProfiles] = useState<OrganisationBrand[]>([]); const [selectedId, setSelectedId] = useState(""); const [form, setForm] = useState<BrandForm>(empty); const [note, setNote] = useState(""); const [status, setStatus] = useState<VerificationStatus | "ALL">("ALL");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const selected = profiles.find((value) => value.organisationId === selectedId) ?? null; const visible = useMemo(() => profiles.filter((value) => status === "ALL" || value.verificationStatus === status), [profiles, status]);
  const load = async (preserve = "") => { try { setLoading(true); const values = await apiClient<OrganisationBrand[]>("/api/admin/organisation-brands"); setProfiles(values); const id = preserve || selectedId || values[0]?.organisationId || ""; setSelectedId(id); const current = values.find((value) => value.organisationId === id); if (current) setForm(formOf(current)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Organisation reviews could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const select = (value: OrganisationBrand) => { setSelectedId(value.organisationId); setForm(formOf(value)); setNote(""); setError(""); setNotice(""); };
  const assistedSave = async () => { if (!selected) return; try { setSaving(true); setError(""); await apiClient(`/api/admin/organisation-brands/${selected.organisationId}`, { method: "PUT", body: JSON.stringify({ ...form, submitForVerification: true }) }); setNotice("Assisted company details saved and returned to review."); await load(selected.organisationId); } catch (reason) { setError(reason instanceof Error ? reason.message : "Company details could not be saved."); } finally { setSaving(false); } };
  const decide = async (decision: "VERIFIED" | "NEEDS_INFORMATION" | "REJECTED" | "SUSPENDED") => { if (!selected) return; if (note.trim().length < 10) { setError("Add a review note of at least 10 characters so the decision remains auditable."); return; } if (!window.confirm(`${pretty(decision)} ${selected.displayName}? The decision and note will be retained.`)) return; try { setSaving(true); setError(""); await apiClient(`/api/admin/organisation-brands/${selected.organisationId}/decision`, { method: "POST", body: JSON.stringify({ status: decision, note: note.trim() }) }); setNotice(`Company identity marked ${pretty(decision)}.`); setNote(""); await load(selected.organisationId); } catch (reason) { setError(reason instanceof Error ? reason.message : "The review decision could not be recorded."); } finally { setSaving(false); } };
  return <section className="panel brand-admin-panel"><SectionTitle eyebrow="Company trust" title="Organisation identity & brand review" action={<select aria-label="Filter company verification status" value={status} onChange={(event) => setStatus(event.target.value as VerificationStatus | "ALL")}><option value="PENDING_VERIFICATION">Awaiting review</option><option value="NEEDS_INFORMATION">Needs information</option><option value="VERIFIED">Verified</option><option value="DRAFT">Draft</option><option value="REJECTED">Rejected</option><option value="SUSPENDED">Suspended</option><option value="ALL">All companies</option></select>} /><p>Review identity once, then reuse it consistently across every candidate-facing surface.</p>{error && <p className="workflow-error" role="alert">{error}</p>}{notice && <p className="workflow-notice" role="status">{notice}</p>}{loading ? <p className="workflow-loading">Loading company reviews…</p> : <div className="brand-admin-layout"><aside className="brand-review-queue">{visible.map((value) => <button type="button" className={value.organisationId === selectedId ? "selected" : ""} onClick={() => select(value)} key={value.organisationId}><span><b>{value.displayName}</b><small>{value.workEmailDomain || "No verified email domain"}</small></span><Badge tone={tone(value.verificationStatus)}>{pretty(value.verificationStatus)}</Badge></button>)}{!visible.length && <p>No companies match this status.</p>}</aside>{selected && <div className="brand-admin-editor"><BrandPreview form={form} verified={selected.verificationStatus === "VERIFIED"} /><BrandFields form={form} onChange={setForm} disabled={saving} /><div className="brand-review-decision"><label><span>Required review note</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Evidence checked, discrepancies found, or information required" /></label><div><Button variant="secondary" disabled={saving} onClick={() => void assistedSave()}>Save assisted update</Button><Button disabled={saving} onClick={() => void decide("VERIFIED")}>Verify company</Button><Button variant="secondary" disabled={saving} onClick={() => void decide("NEEDS_INFORMATION")}>Request information</Button><Button variant="danger" disabled={saving} onClick={() => void decide("SUSPENDED")}>Suspend identity</Button></div></div><HistoryList history={selected.history} /></div>}</div>}</section>;
}
