import Link from "next/link";
import { Logo } from "./ui";
import { PublicJobSave } from "./public-job-save";
import type { PublicKnowledgePost } from "../lib/backend";

export type PublicJob = { id: string; company: string; companySlug: string; title: string; tags: string[]; experience: string; location: string; department: string; employmentType: string; workplaceModel: string; postedAt: string | null; verifiedEmployer: boolean; publicPath?: string; mark: string; tone: string };

export const publicJobs: PublicJob[] = [
  { id: "senior-product-designer", company: "Northstar Labs", companySlug: "northstar-labs", title: "Senior Product Designer", tags: ["Figma", "Design systems", "Research"], experience: "5–7 years", location: "London · Hybrid", department: "Design", employmentType: "FULL_TIME", workplaceModel: "HYBRID", postedAt: "2026-08-29T09:00:00Z", verifiedEmployer: true, mark: "N", tone: "navy" },
  { id: "frontend-engineer", company: "Cascade", companySlug: "cascade", title: "Frontend Engineer", tags: ["React", "TypeScript", "Next.js"], experience: "3–5 years", location: "Remote · United Kingdom", department: "Engineering", employmentType: "FULL_TIME", workplaceModel: "REMOTE", postedAt: "2026-08-28T09:00:00Z", verifiedEmployer: true, mark: "C", tone: "blue" },
  { id: "growth-marketing-lead", company: "Plume Health", companySlug: "plume-health", title: "Growth Marketing Lead", tags: ["Growth", "B2B", "Analytics"], experience: "6–8 years", location: "Manchester · Hybrid", department: "Marketing", employmentType: "FULL_TIME", workplaceModel: "HYBRID", postedAt: "2026-08-27T09:00:00Z", verifiedEmployer: true, mark: "P", tone: "orange" },
  { id: "data-analyst", company: "Kinetic", companySlug: "kinetic", title: "Data Analyst", tags: ["SQL", "Python", "Tableau"], experience: "2–4 years", location: "London · Hybrid", department: "Analytics", employmentType: "FULL_TIME", workplaceModel: "HYBRID", postedAt: "2026-08-26T09:00:00Z", verifiedEmployer: true, mark: "K", tone: "purple" },
  { id: "people-operations-partner", company: "Halcyon", companySlug: "halcyon", title: "People Operations Partner", tags: ["HRIS", "Employee experience", "Policy"], experience: "4–6 years", location: "Bristol · Hybrid", department: "People", employmentType: "FULL_TIME", workplaceModel: "HYBRID", postedAt: "2026-08-25T09:00:00Z", verifiedEmployer: true, mark: "H", tone: "green" },
  { id: "product-manager", company: "Morrow", companySlug: "morrow", title: "Product Manager", tags: ["Strategy", "SaaS", "Discovery"], experience: "4–6 years", location: "Remote · United Kingdom", department: "Product", employmentType: "FULL_TIME", workplaceModel: "REMOTE", postedAt: "2026-08-24T09:00:00Z", verifiedEmployer: true, mark: "M", tone: "rose" },
];

const companies = [
  { name: "Northstar Labs", slug: "northstar-labs", mark: "N", tone: "navy", industry: "Analytics" }, { name: "Cascade", slug: "cascade", mark: "C", tone: "blue", industry: "Technology" }, { name: "Plume Health", slug: "plume-health", mark: "P", tone: "orange", industry: "Healthtech" }, { name: "Kinetic", slug: "kinetic", mark: "K", tone: "purple", industry: "Climate tech" }, { name: "Halcyon", slug: "halcyon", mark: "H", tone: "green", industry: "Consulting" }, { name: "Morrow", slug: "morrow", mark: "M", tone: "rose", industry: "Fintech" },
];

const features = [
  { icon: "✦", title: "A profile you control", copy: "Build from your CV, review every extracted detail, and decide exactly what recruitment teams can see." },
  { icon: "⌕", title: "Jobs worth your time", copy: "Search roles by job title, skills, experience and location, with every application in one clear timeline." },
  { icon: "⇄", title: "A more human hiring process", copy: "Know where you stand with clear status updates, thoughtful communication and no disappearing applications." },
];

const articles: PublicKnowledgePost[] = [
  { id: "default-1", slug: "make-your-portfolio-tell-a-stronger-product-story", category: "Career growth", title: "How to make your portfolio tell a stronger product story", excerpt: "A practical structure for showing the decisions, trade-offs and outcomes behind your strongest work.", body: "", readingMinutes: 6, heroTone: "blue", featured: true, status: "PUBLISHED", authorName: "Sapienworx Editorial", publishedAt: "" },
  { id: "default-2", slug: "practical-guide-to-finding-the-right-hybrid-role", category: "Job search", title: "A practical guide to finding the right hybrid role", excerpt: "Questions that reveal whether a company’s hybrid policy will genuinely support your best work.", body: "", readingMinutes: 5, heroTone: "purple", featured: true, status: "PUBLISHED", authorName: "Sapienworx Editorial", publishedAt: "" },
  { id: "default-3", slug: "questions-worth-asking-before-you-accept-an-offer", category: "Work life", title: "Questions worth asking before you accept an offer", excerpt: "A concise guide to understanding expectations, growth, management and the realities behind an offer.", body: "", readingMinutes: 4, heroTone: "sage", featured: true, status: "PUBLISHED", authorName: "Sapienworx Editorial", publishedAt: "" },
];

export function PublicNavigation() {
  return <header className="public-nav"><Logo/><nav aria-label="Public navigation"><Link href="/jobs">Find jobs</Link><Link href="/companies">Companies</Link><Link href="/knowledge">Knowledge hub</Link><Link href="/#features">How it works</Link></nav><div className="public-nav-actions"><Link className="text-action" href="/login">Sign in</Link><Link className="button button-primary" href="/register">Create profile</Link><Link className="recruiter-entry" href="/recruiter/login">For recruiters <span>→</span></Link><details className="public-mobile-menu"><summary aria-label="Open navigation menu"><i/><i/><i/></summary><nav aria-label="Mobile public navigation"><Link href="/login">Sign in</Link><Link href="/jobs">Find jobs</Link><Link href="/companies">Companies</Link><Link href="/knowledge">Knowledge hub</Link><Link href="/#features">How it works</Link><Link className="mobile-recruiter-entry" href="/recruiter/login">For recruiters <span>→</span></Link></nav></details></div></header>;
}

export function JobSearch({ compact = false }: { compact?: boolean }) {
  return <form className={compact ? "job-search job-search-compact" : "job-search"} action="/jobs"><label><span>⌕</span><input name="keywords" placeholder="Job title or keywords" aria-label="Job title or keywords"/></label><label><span>↗</span><input name="experience" placeholder="Experience" aria-label="Experience"/></label><label><span>⌖</span><input name="location" placeholder="Location" aria-label="Location"/></label><button type="submit">Search jobs</button></form>;
}

export function JobCard({ job }: { job: PublicJob }) { const jobPath = job.publicPath ?? (job.id.startsWith("SWX_") ? `/jobs/${encodeURIComponent(job.id)}/${jobTitleSlug(job.title)}` : `/jobs?keywords=${encodeURIComponent(job.title)}`); return <article className="public-job-card"><div className={`public-company-mark mark-${job.tone}`}>{job.mark}</div><div className="public-job-content"><p className="public-job-company">{job.company}{job.verifiedEmployer && <span title="Employer work domain verified">✓ Verified employer</span>}</p><h3>{job.title}</h3><div className="public-job-decision-meta"><span>{displayLocation(job.location, job.workplaceModel)}</span><span>{humanJobLabel(job.workplaceModel)}</span><span>{humanJobLabel(job.employmentType)}</span><span>{postedLabel(job.postedAt)}</span></div><div className="public-tags">{job.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><footer><span>{job.experience}</span><span>{job.department}</span></footer><div className="public-job-actions"><Link className="public-job-view" href={jobPath}>View job <span>→</span></Link><PublicJobSave jobId={job.id} jobTitle={job.title}/></div></div></article>; }

function CompanyCard({ company }: { company: typeof companies[number] }) { const jobCount = publicJobs.filter((job) => job.companySlug === company.slug).length; return <Link className="public-company-card" href={`/companies/${company.slug}`}><span className={`public-company-mark mark-${company.tone}`}>{company.mark}</span><div><strong>{company.name}</strong><small>{company.industry}</small></div><span className="company-count">{jobCount || 1} jobs</span><b>→</b></Link>; }
function SectionHead({ eyebrow, title, copy, href, label }: { eyebrow: string; title: string; copy?: string; href: string; label: string }) { return <header className="public-section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div><Link href={href} className="view-all">{label} <span>→</span></Link></header>; }

export function PublicLanding({ jobs = publicJobs, articles: publishedArticles = articles }: { jobs?: PublicJob[]; articles?: PublicKnowledgePost[] }) { const featuredArticles = publishedArticles.filter((article) => article.featured).slice(0, 3); const visibleArticles = featuredArticles.length ? featuredArticles : publishedArticles.slice(0, 3); return <main className="public-page"><PublicNavigation/><section className="landing-search-hero"><div className="public-container"><h1>Work that fits your <em>life</em>, not just your CV.</h1><p className="landing-candidate-promise"><strong>Career-defining roles from verified companies building what’s next.</strong><span>Build a standout profile and connect with employers who recognise your strengths.</span></p><JobSearch/><div className="landing-hero-actions"><div className="popular-searches"><span>Popular:</span><Link href="/jobs?keywords=Product+Designer">Product Designer</Link><Link href="/jobs?keywords=Frontend+Engineer">Frontend Engineer</Link><Link href="/jobs?keywords=Data+Analyst">Data Analyst</Link></div><Link className="landing-profile-action" href="/register">Build my profile from CV <span>→</span></Link></div></div></section><section className="public-section featured-jobs"><SectionHead eyebrow="Opportunities for you" title="Explore featured jobs" copy="Fresh roles from teams building meaningful work." href="/jobs" label="View all jobs"/><div className="public-job-grid">{jobs.slice(0, 6).map((job) => <JobCard job={job} key={job.id}/>)}</div></section><section className="company-strip"><div className="public-section"><SectionHead eyebrow="Discover teams" title="Find your people" href="/companies" label="View all companies"/><div className="public-company-grid">{companies.map((company) => <CompanyCard company={company} key={company.slug}/>)}</div></div></section><section className="public-section feature-section" id="features"><header className="feature-heading"><span className="eyebrow">Built around your next move</span><h2>Sapienworx makes the whole journey clearer.</h2><p>Less repetition. Better visibility. More control over your professional information.</p></header><div className="public-feature-grid">{features.map((feature) => <article key={feature.title}><span>{feature.icon}</span><h3>{feature.title}</h3><p>{feature.copy}</p></article>)}</div></section><section className="knowledge-band"><div className="public-section"><SectionHead eyebrow="The knowledge hub" title="Good advice for real career decisions." href="/knowledge" label="Explore the hub"/><div className="article-grid">{visibleArticles.map((article) => <ArticleCard article={article} key={article.id}/>)}</div>{!visibleArticles.length && <p className="knowledge-empty">Fresh guidance is being prepared by the Sapienworx editorial team.</p>}</div></section><PublicFooter/></main>; }

function ArticleCard({ article, detailed = false }: { article: PublicKnowledgePost; detailed?: boolean }) { return <article className={`article-card article-${article.heroTone}`}><div><span>{article.category}</span><h3>{article.title}</h3>{detailed && <p>{article.excerpt}</p>}</div><footer><small>{article.readingMinutes} min read</small><Link href={`/knowledge/${article.slug}`}>Read article <b>→</b></Link></footer></article>; }
function PublicFooter() { return <footer className="public-footer"><Logo light/><p>Clearer careers. More confident hiring.</p><div><Link href="/jobs">Jobs</Link><Link href="/companies">Companies</Link><Link href="/recruiter/login">Recruiter workspace</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/cookies">Cookies</Link></div></footer>; }

export function PublicJobsPage({ search, jobs = publicJobs }: { search?: { keywords?: string | string[] }, jobs?: PublicJob[] }) {
  const keyword = Array.isArray(search?.keywords) ? search.keywords[0] : search?.keywords;
  return <main className="public-page public-list-page"><PublicNavigation/><section className="public-page-heading"><div className="public-container"><span className="eyebrow">Job search</span><h1>{keyword ? `Roles matching “${keyword}”` : "Find a role that fits"}</h1><p>Use your job title, keywords, experience or preferred location to narrow the field.</p><JobSearch compact/></div></section><section className="public-section public-jobs-layout"><aside className="public-filters"><strong>Refine your search</strong><FilterGroup title="Workplace" values={["Remote", "Hybrid", "On-site"]}/><FilterGroup title="Experience" values={["Entry level", "Mid level", "Senior", "Leadership"]}/><FilterGroup title="Employment type" values={["Full-time", "Contract", "Permanent"]}/></aside><div><div className="listing-summary"><strong>{jobs.length} jobs available</strong><span>Sorted by relevance</span></div>{jobs.length ? <div className="public-job-grid public-job-grid-list">{jobs.map((job) => <JobCard job={job} key={job.id}/>)}</div> : <section className="public-job-zero editorial-empty-state" aria-live="polite"><span className="public-job-zero-sketch" aria-hidden="true">⌕</span><span className="eyebrow">Search reset</span><h2>We’ve scoured the listings, but this exact role is proving elusive.</h2><p>{keyword ? `Try a broader title than “${keyword}”, remove one filter, or let your profile bring relevant opportunities to you.` : "Try one title or skill at a time, or let your profile bring relevant opportunities to you."}</p><div><a className="button button-primary" href="/jobs">Clear search</a><a className="button button-secondary" href="/register">Build my profile</a></div></section>}</div></section></main>;
}
function FilterGroup({ title, values }: { title: string; values: string[] }) { return <section className="public-filter-group"><strong>{title}</strong>{values.map((value) => <label key={value}><input type="checkbox"/> {value}</label>)}</section>; }

export function CompaniesPage() { return <main className="public-page public-list-page"><PublicNavigation/><section className="public-page-heading"><div className="public-container"><span className="eyebrow">Company directory</span><h1>Meet the teams behind the roles.</h1><p>Explore companies, what they do and the opportunities they are currently hiring for.</p></div></section><section className="public-section"><div className="company-directory-grid">{companies.map((company) => <CompanyCard company={company} key={company.slug}/>)}</div></section></main>; }
export function CompanyJobsPage({ slug, jobs = publicJobs }: { slug: string; jobs?: PublicJob[] }) { const staticCompany = companies.find((item) => item.slug === slug); const roles = jobs.filter((job) => job.companySlug === slug); const fallbackJob = roles[0] ?? jobs[0]; const company = staticCompany ?? { slug, name: fallbackJob?.company ?? slug.replace(/-/g, " "), industry: "Hiring on Sapienworx", mark: fallbackJob?.mark ?? "SW", tone: fallbackJob?.tone ?? "teal" }; const displayedRoles = roles.length ? roles : jobs.filter((job) => job.company === company.name); return <main className="public-page public-list-page"><PublicNavigation/><section className="company-detail-hero"><div className="public-container"><span className={`public-company-mark mark-${company.tone}`}>{company.mark}</span><div><span className="eyebrow">{company.industry}</span><h1>{company.name}</h1><p>Browse the roles this team is currently hiring for through Sapienworx.</p></div></div></section><section className="public-section"><SectionHead eyebrow="Open positions" title={`${displayedRoles.length || 1} roles at ${company.name}`} href="/companies" label="All companies"/><div className="public-job-grid">{(displayedRoles.length ? displayedRoles : jobs.slice(0, 1)).map((job) => <JobCard job={job} key={job.id}/>)}</div></section></main>; }
export function KnowledgePage({ articles: publishedArticles = articles }: { articles?: PublicKnowledgePost[] }) { return <main className="public-page public-list-page"><PublicNavigation/><section className="public-page-heading"><div className="public-container"><span className="eyebrow">Sapienworx knowledge hub</span><h1>Useful guidance for every stage of your career.</h1><p>Practical articles for applications, interviews, professional growth and better work decisions.</p></div></section><section className="public-section"><div className="article-grid article-grid-library">{publishedArticles.map((article) => <ArticleCard article={article} detailed key={article.id}/>)}</div>{!publishedArticles.length && <div className="knowledge-library-empty"><span>✎</span><h2>The next edition is taking shape.</h2><p>Our editorial team is preparing practical guidance for your next career decision.</p></div>}</section><PublicFooter/></main>; }

export function KnowledgeArticlePage({ article }: { article: PublicKnowledgePost }) { const paragraphs = article.body.split(/\n\s*\n/).map((paragraph) => paragraph.trim()).filter(Boolean); return <main className="public-page public-list-page"><PublicNavigation/><article className={`knowledge-article article-hero-${article.heroTone}`}><header><Link href="/knowledge">← Knowledge hub</Link><span>{article.category}</span><h1>{article.title}</h1><p>{article.excerpt}</p><footer><b>{article.authorName}</b><span>{article.readingMinutes} min read</span>{article.publishedAt && <span>{new Date(article.publishedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</span>}</footer></header><section>{paragraphs.map((paragraph, index) => <p key={`${article.id}-${index}`}>{paragraph}</p>)}</section></article><PublicFooter/></main>; }
export const companySlugs = companies.map((company) => company.slug);

function humanJobLabel(value: string) {
  const labels: Record<string, string> = { FULL_TIME: "Full-time", PART_TIME: "Part-time", CONTRACT: "Contract", INTERNSHIP: "Internship", TEMPORARY: "Temporary", FREELANCE: "Freelance", ON_SITE: "On-site", HYBRID: "Hybrid", REMOTE: "Remote" };
  return labels[value] ?? value.replace(/_/g, " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
}
function displayLocation(location: string, workplaceModel: string) {
  const workplace = humanJobLabel(workplaceModel).toLowerCase();
  const parts = location.split("·").map((part) => part.trim()).filter(Boolean).filter((part) => part.toLowerCase() !== workplace);
  return parts.join(" · ") || location;
}
function postedLabel(publishedAt: string | null) {
  if (!publishedAt) return "Recently posted";
  const elapsedDays = Math.max(0, Math.floor((Date.now() - new Date(publishedAt).getTime()) / 86_400_000));
  if (elapsedDays === 0) return "Posted today";
  if (elapsedDays === 1) return "Posted yesterday";
  return `Posted ${elapsedDays}d ago`;
}
function jobTitleSlug(title: string) { return title.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
