import Link from "next/link";
import { Logo } from "./ui";

export type PublicJob = { id: string; company: string; companySlug: string; title: string; tags: string[]; experience: string; location: string; type: string; mark: string; tone: string };

export const publicJobs: PublicJob[] = [
  { id: "senior-product-designer", company: "Northstar Labs", companySlug: "northstar-labs", title: "Senior Product Designer", tags: ["Figma", "Design systems", "Research"], experience: "5–7 years", location: "London · Hybrid", type: "Full-time", mark: "N", tone: "navy" },
  { id: "frontend-engineer", company: "Cascade", companySlug: "cascade", title: "Frontend Engineer", tags: ["React", "TypeScript", "Next.js"], experience: "3–5 years", location: "Remote · United Kingdom", type: "Full-time", mark: "C", tone: "blue" },
  { id: "growth-marketing-lead", company: "Plume Health", companySlug: "plume-health", title: "Growth Marketing Lead", tags: ["Growth", "B2B", "Analytics"], experience: "6–8 years", location: "Manchester · Hybrid", type: "Permanent", mark: "P", tone: "orange" },
  { id: "data-analyst", company: "Kinetic", companySlug: "kinetic", title: "Data Analyst", tags: ["SQL", "Python", "Tableau"], experience: "2–4 years", location: "London · Hybrid", type: "Full-time", mark: "K", tone: "purple" },
  { id: "people-operations-partner", company: "Halcyon", companySlug: "halcyon", title: "People Operations Partner", tags: ["HRIS", "Employee experience", "Policy"], experience: "4–6 years", location: "Bristol · Hybrid", type: "Full-time", mark: "H", tone: "green" },
  { id: "product-manager", company: "Morrow", companySlug: "morrow", title: "Product Manager", tags: ["Strategy", "SaaS", "Discovery"], experience: "4–6 years", location: "Remote · United Kingdom", type: "Full-time", mark: "M", tone: "rose" },
];

const companies = [
  { name: "Northstar Labs", slug: "northstar-labs", mark: "N", tone: "navy", industry: "Analytics" }, { name: "Cascade", slug: "cascade", mark: "C", tone: "blue", industry: "Technology" }, { name: "Plume Health", slug: "plume-health", mark: "P", tone: "orange", industry: "Healthtech" }, { name: "Kinetic", slug: "kinetic", mark: "K", tone: "purple", industry: "Climate tech" }, { name: "Halcyon", slug: "halcyon", mark: "H", tone: "green", industry: "Consulting" }, { name: "Morrow", slug: "morrow", mark: "M", tone: "rose", industry: "Fintech" },
];

const features = [
  { icon: "✦", title: "A profile you control", copy: "Build from your CV, review every extracted detail, and decide exactly what recruitment teams can see." },
  { icon: "⌕", title: "Jobs worth your time", copy: "Search roles by job title, skills, experience and location, with every application in one clear timeline." },
  { icon: "⇄", title: "A more human hiring process", copy: "Know where you stand with clear status updates, thoughtful communication and no disappearing applications." },
];

const articles = [
  { category: "Career growth", title: "How to make your portfolio tell a stronger product story", time: "6 min read", colour: "blue" },
  { category: "Job search", title: "A practical guide to finding the right hybrid role", time: "5 min read", colour: "purple" },
  { category: "Work life", title: "Questions worth asking before you accept an offer", time: "4 min read", colour: "green" },
];

export function PublicNavigation() {
  return <header className="public-nav"><Logo/><nav aria-label="Public navigation"><Link href="/jobs">Find jobs</Link><Link href="/companies">Companies</Link><Link href="/knowledge">Knowledge hub</Link><Link href="/#features">How it works</Link></nav><div className="public-nav-actions"><Link className="text-action" href="/login">Sign in</Link><Link className="button button-primary" href="/register">Create profile</Link><Link className="recruiter-entry" href="/recruiter/login">For recruiters <span>→</span></Link></div></header>;
}

export function JobSearch({ compact = false }: { compact?: boolean }) {
  return <form className={compact ? "job-search job-search-compact" : "job-search"} action="/jobs"><label><span>⌕</span><input name="keywords" placeholder="Job title or keywords" aria-label="Job title or keywords"/></label><label><span>↗</span><input name="experience" placeholder="Experience" aria-label="Experience"/></label><label><span>⌖</span><input name="location" placeholder="Location" aria-label="Location"/></label><button type="submit">Search jobs</button></form>;
}

export function JobCard({ job }: { job: PublicJob }) { return <article className="public-job-card"><div className={`public-company-mark mark-${job.tone}`}>{job.mark}</div><div className="public-job-content"><p>{job.company}</p><h3>{job.title}</h3><Link className="public-job-apply" href={`/register?job=${encodeURIComponent(job.id)}`}>Apply now</Link><div className="public-tags">{job.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><footer><span>{job.experience}</span><span>{job.location}</span><span>{job.type}</span></footer></div><Link className="job-card-link" href={`/jobs?keywords=${encodeURIComponent(job.title)}`} aria-label={`View ${job.title} at ${job.company}`}>→</Link></article>; }

function CompanyCard({ company }: { company: typeof companies[number] }) { const jobCount = publicJobs.filter((job) => job.companySlug === company.slug).length; return <Link className="public-company-card" href={`/companies/${company.slug}`}><span className={`public-company-mark mark-${company.tone}`}>{company.mark}</span><div><strong>{company.name}</strong><small>{company.industry}</small></div><span className="company-count">{jobCount || 1} jobs</span><b>→</b></Link>; }
function SectionHead({ eyebrow, title, copy, href, label }: { eyebrow: string; title: string; copy?: string; href: string; label: string }) { return <header className="public-section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div><Link href={href} className="view-all">{label} <span>→</span></Link></header>; }

export function PublicLanding() { return <main className="public-page"><PublicNavigation/><section className="landing-search-hero"><div className="public-container"><span className="landing-pill">A clearer way to find the right work</span><h1>Work that fits your <em>life</em>, not just your CV.</h1><p>Find roles from companies that value the skills, experience and perspective you bring.</p><JobSearch/><div className="popular-searches"><span>Popular:</span><Link href="/jobs?keywords=Product+Designer">Product Designer</Link><Link href="/jobs?keywords=Frontend+Engineer">Frontend Engineer</Link><Link href="/jobs?keywords=Data+Analyst">Data Analyst</Link></div></div></section><section className="public-section featured-jobs"><SectionHead eyebrow="Opportunities for you" title="Explore featured jobs" copy="Fresh roles from teams building meaningful work." href="/jobs" label="View all jobs"/><div className="public-job-grid">{publicJobs.map((job) => <JobCard job={job} key={job.id}/>)}</div></section><section className="company-strip"><div className="public-section"><SectionHead eyebrow="Discover teams" title="Find your people" href="/companies" label="View all companies"/><div className="public-company-grid">{companies.map((company) => <CompanyCard company={company} key={company.slug}/>)}</div></div></section><section className="public-section feature-section" id="features"><header className="feature-heading"><span className="eyebrow">Built around your next move</span><h2>Sapienworx makes the whole journey clearer.</h2><p>Less repetition. Better visibility. More control over your professional information.</p></header><div className="public-feature-grid">{features.map((feature) => <article key={feature.title}><span>{feature.icon}</span><h3>{feature.title}</h3><p>{feature.copy}</p></article>)}</div></section><section className="knowledge-band"><div className="public-section"><SectionHead eyebrow="The knowledge hub" title="Good advice for real career decisions." href="/knowledge" label="Explore the hub"/><div className="article-grid">{articles.map((article) => <ArticleCard article={article} key={article.title}/>)}</div></div></section><PublicFooter/></main>; }

function ArticleCard({ article }: { article: typeof articles[number] }) { return <article className={`article-card article-${article.colour}`}><div><span>{article.category}</span><h3>{article.title}</h3></div><footer><small>{article.time}</small><Link href="/knowledge">Read article <b>→</b></Link></footer></article>; }
function PublicFooter() { return <footer className="public-footer"><Logo light/><p>Clearer careers. More confident hiring.</p><div><Link href="/jobs">Jobs</Link><Link href="/companies">Companies</Link><Link href="/recruiter/login">Recruiter workspace</Link></div></footer>; }

export function PublicJobsPage({ search }: { search?: { keywords?: string | string[] } }) { const keyword = Array.isArray(search?.keywords) ? search?.keywords[0] : search?.keywords; return <main className="public-page public-list-page"><PublicNavigation/><section className="public-page-heading"><div className="public-container"><span className="eyebrow">Job search</span><h1>{keyword ? `Roles matching “${keyword}”` : "Find a role that fits"}</h1><p>Use your job title, keywords, experience or preferred location to narrow the field.</p><JobSearch compact/></div></section><section className="public-section public-jobs-layout"><aside className="public-filters"><strong>Refine your search</strong><FilterGroup title="Workplace" values={["Remote", "Hybrid", "On-site"]}/><FilterGroup title="Experience" values={["Entry level", "Mid level", "Senior", "Leadership"]}/><FilterGroup title="Employment type" values={["Full-time", "Contract", "Permanent"]}/></aside><div><div className="listing-summary"><strong>{publicJobs.length} jobs available</strong><span>Sorted by relevance</span></div><div className="public-job-grid public-job-grid-list">{publicJobs.map((job) => <JobCard job={job} key={job.id}/>)}</div></div></section></main>; }
function FilterGroup({ title, values }: { title: string; values: string[] }) { return <section className="public-filter-group"><strong>{title}</strong>{values.map((value) => <label key={value}><input type="checkbox"/> {value}</label>)}</section>; }

export function CompaniesPage() { return <main className="public-page public-list-page"><PublicNavigation/><section className="public-page-heading"><div className="public-container"><span className="eyebrow">Company directory</span><h1>Meet the teams behind the roles.</h1><p>Explore companies, what they do and the opportunities they are currently hiring for.</p></div></section><section className="public-section"><div className="company-directory-grid">{companies.map((company) => <CompanyCard company={company} key={company.slug}/>)}</div></section></main>; }
export function CompanyJobsPage({ slug }: { slug: string }) { const company = companies.find((item) => item.slug === slug) ?? companies[0]; const roles = publicJobs.filter((job) => job.companySlug === company.slug); return <main className="public-page public-list-page"><PublicNavigation/><section className="company-detail-hero"><div className="public-container"><span className={`public-company-mark mark-${company.tone}`}>{company.mark}</span><div><span className="eyebrow">{company.industry}</span><h1>{company.name}</h1><p>Browse the roles this team is currently hiring for through Sapienworx.</p></div></div></section><section className="public-section"><SectionHead eyebrow="Open positions" title={`${roles.length || 1} roles at ${company.name}`} href="/companies" label="All companies"/><div className="public-job-grid">{(roles.length ? roles : publicJobs.slice(0, 1)).map((job) => <JobCard job={job} key={job.id}/>)}</div></section></main>; }
export function KnowledgePage() { return <main className="public-page public-list-page"><PublicNavigation/><section className="public-page-heading"><div className="public-container"><span className="eyebrow">Sapienworx knowledge hub</span><h1>Useful guidance for every stage of your career.</h1><p>Practical articles for applications, interviews, professional growth and better work decisions.</p></div></section><section className="public-section"><div className="article-grid">{articles.concat(articles).map((article, index) => <ArticleCard article={article} key={`${article.title}-${index}`}/>)}</div></section></main>; }
export const companySlugs = companies.map((company) => company.slug);
