"use client";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { apiClient } from "../lib/api-client";
import { Button, WorkspaceShell } from "./ui";
import type { Analytics, Campaign, Interview, OrganisationControls, SavedSearch, TalentPool } from "./recruiter-workbench/types";

const SavedSearchesPanel=dynamic(()=>import("./recruiter-workbench/saved-searches-panel"),{loading:()=> <div className="loading-state">Loading saved searches…</div>});
const TalentPoolsPanel=dynamic(()=>import("./recruiter-workbench/talent-pools-panel"),{loading:()=> <div className="loading-state">Loading talent pools…</div>});
const CampaignsPanel=dynamic(()=>import("./recruiter-workbench/campaigns-panel"),{loading:()=> <div className="loading-state">Loading campaigns…</div>});
const InterviewsPanel=dynamic(()=>import("./recruiter-workbench/interviews-panel"),{loading:()=> <div className="loading-state">Loading interviews…</div>});
type Tab="searches"|"pools"|"campaigns"|"interviews"|"controls";

export function RecruiterWorkbench(){
 const [tab,setTab]=useState<Tab>("searches");const [savedSearches,setSavedSearches]=useState<SavedSearch[]>([]);const [pools,setPools]=useState<TalentPool[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [interviews,setInterviews]=useState<Interview[]>([]);const [analytics,setAnalytics]=useState<Analytics|null>(null);const [controls,setControls]=useState<OrganisationControls|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [searches,nextPools,nextCampaigns,nextInterviews,nextAnalytics,nextControls]=await Promise.all([apiClient<SavedSearch[]>("/api/recruiter/workflow/saved-searches"),apiClient<TalentPool[]>("/api/recruiter/workflow/talent-pools"),apiClient<Campaign[]>("/api/recruiter/workflow/campaigns"),apiClient<Interview[]>("/api/recruiter/workflow/interviews"),apiClient<Analytics>("/api/recruiter/workflow/analytics"),apiClient<OrganisationControls>("/api/recruiter/workflow/organisation-controls")]);setSavedSearches(searches);setPools(nextPools);setCampaigns(nextCampaigns);setInterviews(nextInterviews);setAnalytics(nextAnalytics);setControls(nextControls);}catch(reason){setError(reason instanceof Error?reason.message:"We could not load your recruitment workspace.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 return <WorkspaceShell workspace="recruiter" active="workbench" title="Recruitment workspace" description="Needs-attention work, reusable sourcing and hiring operations without one oversized page bundle." actions={<Button variant="secondary" onClick={()=>void load()}>Refresh</Button>}><main className="workflow-page"><section className="workflow-journey panel"><div><span className="eyebrow">Hiring flow</span><h2>Source → Engage → Assess → Hire → Measure</h2><p>Each operational area loads independently so the workbench stays focused and maintainable.</p></div></section><section className="workflow-metrics" aria-label="Recruitment operations metrics"><Metric label="Saved searches" value={analytics?.savedSearches??0}/><Metric label="People in pools" value={analytics?.candidatesInPools??0}/><Metric label="Active campaigns" value={analytics?.activeCampaigns??0}/><Metric label="Interviews this week" value={analytics?.interviewsThisWeek??0}/></section><section className="workflow-tabs" role="tablist" aria-label="Recruitment workspace sections">{(["searches","pools","campaigns","interviews","controls"] as Tab[]).map(value=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{value==="searches"?"Saved searches":value==="pools"?"Talent pools":value.charAt(0).toUpperCase()+value.slice(1)}</button>)}</section>{error&&<div className="workflow-error" role="alert"><strong>Workspace unavailable</strong><p>{error}</p><Button variant="secondary" onClick={()=>void load()}>Try again</Button></div>}{loading&&!error&&<div className="loading-state" role="status">Loading live recruitment operations…</div>}{!loading&&!error&&tab==="searches"&&<SavedSearchesPanel items={savedSearches} onChanged={()=>void load()}/>} {!loading&&!error&&tab==="pools"&&<TalentPoolsPanel items={pools}/>} {!loading&&!error&&tab==="campaigns"&&<CampaignsPanel items={campaigns}/>} {!loading&&!error&&tab==="interviews"&&<InterviewsPanel items={interviews}/>} {!loading&&!error&&tab==="controls"&&<section className="panel workflow-list"><header className="section-title"><div><span className="eyebrow">Organisation</span><h2>Workspace controls</h2></div><Button href="/recruiter/settings" variant="secondary">Open settings</Button></header>{controls?<><article><div><strong>Your role</strong><p>{controls.currentUserRole.replaceAll("_"," ").toLowerCase()}</p></div></article><article><div><strong>Candidate retention</strong><p>{controls.candidateRetentionDays} days</p></div></article><article><div><strong>Audit retention</strong><p>{controls.auditRetentionDays} days</p></div></article><article><div><strong>Team</strong><p>{controls.members.length} workspace members</p></div></article></>:<div className="empty-state">Organisation controls are unavailable.</div>}</section>}</main></WorkspaceShell>;
}
function Metric({label,value}:{label:string;value:number}){return <article><span>{label}</span><strong>{value}</strong></article>}
