"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { apiClient } from "../lib/api-client";
import { Button, WorkspaceShell } from "./ui";
import styles from "./recruiter-communications.module.css";

type Template = { id: string; name: string; subject: string; bodyHtml: string; updatedAt: string };
type Conversation = { candidateId: string; candidateName: string; applicationId: string; jobTitle: string; applicationStage: string; lastMessageBody: string | null; unreadCount: number };
type Message = { id: string; recipientId: string; body: string; sentAt: string };
type MessagePage = { content: Message[] };
type Draft = { id: string | null; name: string; subject: string; bodyHtml: string };
const EMPTY: Draft = { id: null, name: "", subject: "", bodyHtml: "" };

function merge(value: string, conversation: Conversation | null) {
  const fields: Record<string, string> = { candidate_name: conversation?.candidateName ?? "Candidate name", job_title: conversation?.jobTitle ?? "Job title", application_stage: conversation?.applicationStage?.replaceAll("_", " ") ?? "Application stage" };
  return value.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (token, key: string) => fields[key] ?? token);
}

export function RecruiterCommunicationsWorkspace() {
  const params = useSearchParams(); const pipelineCandidateId = params.get("candidate") ?? ""; const jobId = params.get("job") ?? "";
  const [templates, setTemplates] = useState<Template[]>([]); const [draft, setDraft] = useState<Draft>(EMPTY); const [selectedTemplateId, setSelectedTemplateId] = useState("");
  const [conversations, setConversations] = useState<Conversation[]>([]); const [activeId, setActiveId] = useState<string | null>(pipelineCandidateId || null); const [messages, setMessages] = useState<Message[]>([]); const [reply, setReply] = useState("");
  const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const active = conversations.find((item) => item.candidateId === activeId) ?? null;
  const preview = useMemo(() => ({ subject: merge(draft.subject, active), body: merge(draft.bodyHtml, active) }), [draft.subject, draft.bodyHtml, active]);
  const deliveryPreview = useMemo(() => ({ subject: merge(subject, active), body: merge(body, active) }), [subject, body, active]);

  const loadTemplates = async () => { const value = await apiClient<Template[]>("/api/recruiter/communications/templates"); setTemplates(value); if (!selectedTemplateId && value[0]) setSelectedTemplateId(value[0].id); };
  useEffect(() => { void loadTemplates().catch((reason) => setError(reason instanceof Error ? reason.message : "Templates could not be loaded.")); }, []);
  useEffect(() => { void apiClient<Conversation[]>("/api/recruiter/communications/messages/conversations").then((value) => { setConversations(value); setActiveId((current) => value.some((item) => item.candidateId === current) ? current : value[0]?.candidateId ?? null); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Conversations could not be loaded.")); }, [pipelineCandidateId]);
  useEffect(() => { if (!activeId) { setMessages([]); return; } void apiClient<MessagePage>(`/api/recruiter/communications/messages?with=${encodeURIComponent(activeId)}`).then((page) => setMessages(page.content)).catch((reason) => setError(reason instanceof Error ? reason.message : "Conversation could not be loaded.")); }, [activeId]);
  useEffect(() => { const selected = templates.find((item) => item.id === selectedTemplateId); if (selected) { setSubject(selected.subject); setBody(selected.bodyHtml); } }, [selectedTemplateId, templates]);

  const saveTemplate = async () => { if (!draft.name.trim() || !draft.subject.trim() || !draft.bodyHtml.trim()) { setError("Template name, subject and message are required."); return; } setBusy(true); setError(""); try { const saved = await apiClient<Template>(draft.id ? `/api/recruiter/communications/templates/${draft.id}` : "/api/recruiter/communications/templates", { method: draft.id ? "PUT" : "POST", body: JSON.stringify({ name: draft.name.trim(), subject: draft.subject.trim(), bodyHtml: draft.bodyHtml.trim() }) }); setDraft(EMPTY); setSelectedTemplateId(saved.id); await loadTemplates(); setNotice("Template saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Template could not be saved."); } finally { setBusy(false); } };
  const removeTemplate = async (id: string) => { setBusy(true); setError(""); try { await apiClient(`/api/recruiter/communications/templates/${id}`, { method: "DELETE" }); await loadTemplates(); setNotice("Template deleted."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Template could not be deleted."); } finally { setBusy(false); } };
  const sendReply = async () => { if (!active || !reply.trim()) return; setBusy(true); setError(""); try { const sent = await apiClient<Message>("/api/recruiter/communications/messages", { method: "POST", body: JSON.stringify({ recipientId: active.candidateId, applicationId: active.applicationId, body: reply.trim() }) }); setMessages((current) => [...current, sent]); setReply(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Reply could not be sent."); } finally { setBusy(false); } };
  const queueEmail = async () => { if (!pipelineCandidateId || !subject.trim() || !body.trim()) return; setBusy(true); setError(""); try { await apiClient("/api/recruiter/communications/bulk-email", { method: "POST", body: JSON.stringify({ candidateIds: [pipelineCandidateId], jobId: jobId || null, subject: subject.trim(), htmlContent: body.trim() }) }); setNotice("Candidate email queued for protected delivery."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Candidate email could not be queued."); } finally { setBusy(false); } };

  return <WorkspaceShell workspace="recruiter" active="communications" title="Communications" description="Application-linked messages, reusable templates and protected candidate email.">
    {notice && <p className={styles.success} role="status">{notice}</p>}{error && <p className={styles.error} role="alert">{error}</p>}
    <section className={styles.section}><header className={styles.sectionHeader}><div><span className={styles.eyebrow}>Direct replies</span><h2>Candidate inbox</h2></div></header><div className={styles.inbox}><aside className={styles.conversationList}>{conversations.length === 0 && <p className={styles.state}>No candidate conversations yet.</p>}{conversations.map((item) => <button key={item.candidateId} className={`${styles.conversation} ${item.candidateId === activeId ? styles.active : ""}`} onClick={() => setActiveId(item.candidateId)}><span><strong>{item.candidateName}</strong><small>{item.jobTitle}</small><em>{item.lastMessageBody || "No message yet"}</em></span>{item.unreadCount > 0 && <b className={styles.unread}>{item.unreadCount}</b>}</button>)}</aside><article className={styles.thread}>{active ? <><header><strong>{active.candidateName}</strong><small>{active.jobTitle} · {active.applicationStage.replaceAll("_", " ")}</small></header><div className={styles.messages}>{messages.length === 0 ? <p className={styles.state}>No messages yet.</p> : messages.map((message) => <div className={`${styles.message} ${message.recipientId === active.candidateId ? styles.mine : ""}`} key={message.id}><p>{message.body}</p><small>{new Date(message.sentAt).toLocaleString()}</small></div>)}</div><footer><label><span className={styles.label}>Reply</span><textarea value={reply} onChange={(event) => setReply(event.target.value)}/></label><Button onClick={() => void sendReply()} disabled={busy || !reply.trim()}>Send reply</Button></footer></> : <p className={styles.state}>Select a candidate conversation.</p>}</article></div></section>
    <section className={styles.section}><header className={styles.sectionHeader}><div><span className={styles.eyebrow}>Template library</span><h2>Editor + live merge preview</h2><p>Supported fields are previewed with real selected-conversation context.</p></div><Button variant="secondary" onClick={() => setDraft(EMPTY)}>New template</Button></header><div className={styles.templateLayout}><div className={styles.templateList}>{templates.map((template) => <article className={styles.templateCard} key={template.id}><button onClick={() => setSelectedTemplateId(template.id)}><strong>{template.name}</strong><span>{template.subject}</span></button><div><button onClick={() => setDraft({ id: template.id, name: template.name, subject: template.subject, bodyHtml: template.bodyHtml })}>Edit</button><button className={styles.danger} disabled={busy} onClick={() => void removeTemplate(template.id)}>Delete</button></div></article>)}</div><div className={styles.studio}><form className={styles.editor} onSubmit={(event) => { event.preventDefault(); void saveTemplate(); }}><label><span className={styles.label}>Name</span><input value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))}/></label><label><span className={styles.label}>Subject</span><input value={draft.subject} onChange={(event) => setDraft((current) => ({ ...current, subject: event.target.value }))}/></label><label><span className={styles.label}>Message</span><textarea rows={9} value={draft.bodyHtml} onChange={(event) => setDraft((current) => ({ ...current, bodyHtml: event.target.value }))}/></label><div className={styles.mergeFields}><code>{"{{candidate_name}}"}</code><code>{"{{job_title}}"}</code><code>{"{{application_stage}}"}</code></div><p className={styles.help}>Unknown merge fields remain visible; no candidate data is invented and no external AI service is used.</p><Button type="submit" disabled={busy}>Save template</Button></form><aside className={styles.preview}><span className={styles.eyebrow}>Live preview</span><strong>{preview.subject || "Subject preview"}</strong><p>{preview.body || "Start writing to preview the template."}</p></aside></div></div></section>
    <section className={styles.section}><header className={styles.sectionHeader}><div><span className={styles.eyebrow}>Protected delivery</span><h2>Candidate email</h2><p>{pipelineCandidateId ? "Recipient context came from Pipeline." : "Open Communications from a Pipeline candidate before sending."}</p></div></header><div className={styles.composeGrid}><div className={styles.editor}><label><span className={styles.label}>Template</span><select value={selectedTemplateId} onChange={(event) => setSelectedTemplateId(event.target.value)}><option value="">No template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label><span className={styles.label}>Subject</span><input value={subject} onChange={(event) => setSubject(event.target.value)}/></label><label><span className={styles.label}>Message</span><textarea rows={9} value={body} onChange={(event) => setBody(event.target.value)}/></label><Button disabled={busy || !pipelineCandidateId || !subject.trim() || !body.trim()} onClick={() => void queueEmail()}>Queue candidate email</Button></div><aside className={styles.preview}><span className={styles.eyebrow}>Delivery preview</span><strong>{deliveryPreview.subject || "Subject preview"}</strong><p>{deliveryPreview.body || "Message preview"}</p></aside></div></section>
  </WorkspaceShell>;
}
