"use client";

import { useMemo, useState } from "react";
import { Badge, Button, Meter, SectionTitle, WorkspaceShell } from "./ui";

type CandidateRecord = { id: number; name: string; initials: string; role: string; location: string; experience: number; notice: string; salary: string; education: "Bachelors" | "Masters"; activeDays: number; skills: string[]; lastUpdated: string; lastActive: string };

const candidateRecords: CandidateRecord[] = [
  { id: 1, name: "Amara Mensah", initials: "AM", role: "Senior Product Designer", location: "London · Hybrid", experience: 6, notice: "30 days", salary: "£72k", education: "Masters", activeDays: 1, skills: ["Figma", "Design systems", "Research"], lastUpdated: "Today, 10:42", lastActive: "18 min ago" },
  { id: 2, name: "Nia Okafor", initials: "NO", role: "Product Designer", location: "London · Remote", experience: 5, notice: "15 days", salary: "£64k", education: "Bachelors", activeDays: 1, skills: ["Figma", "Prototyping", "B2B SaaS"], lastUpdated: "Today, 09:18", lastActive: "1 hr ago" },
  { id: 3, name: "Eleanor Chen", initials: "EC", role: "Senior Product Designer", location: "Manchester · Hybrid", experience: 7, notice: "30 days", salary: "£76k", education: "Masters", activeDays: 3, skills: ["Design systems", "Accessibility", "Figma"], lastUpdated: "Yesterday", lastActive: "2 days ago" },
  { id: 4, name: "Lina Patel", initials: "LP", role: "UX Designer", location: "Bristol · Remote", experience: 4, notice: "Immediate", salary: "£58k", education: "Bachelors", activeDays: 3, skills: ["User research", "Figma", "Workshops"], lastUpdated: "Yesterday", lastActive: "2 days ago" },
  { id: 5, name: "Aarav Mehta", initials: "AM", role: "Product Designer", location: "London · Hybrid", experience: 6, notice: "60 days", salary: "£70k", education: "Masters", activeDays: 7, skills: ["Figma", "Product strategy", "Analytics"], lastUpdated: "2 days ago", lastActive: "5 days ago" },
  { id: 6, name: "Sofia Martin", initials: "SM", role: "Senior UX Designer", location: "Leeds · Remote", experience: 8, notice: "30 days", salary: "£78k", education: "Bachelors", activeDays: 7, skills: ["Accessibility", "Research", "Prototyping"], lastUpdated: "2 days ago", lastActive: "6 days ago" },
  { id: 7, name: "David Okoro", initials: "DO", role: "Design Lead", location: "London · On-site", experience: 9, notice: "90 days", salary: "£88k", education: "Masters", activeDays: 15, skills: ["Design systems", "Leadership", "Figma"], lastUpdated: "3 days ago", lastActive: "12 days ago" },
  { id: 8, name: "Ivy Williams", initials: "IW", role: "Product Designer", location: "Birmingham · Hybrid", experience: 5, notice: "30 days", salary: "£63k", education: "Bachelors", activeDays: 15, skills: ["Prototyping", "Research", "Mobile"], lastUpdated: "4 days ago", lastActive: "13 days ago" },
  { id: 9, name: "Maya Singh", initials: "MS", role: "UX Researcher", location: "London · Hybrid", experience: 5, notice: "15 days", salary: "£66k", education: "Masters", activeDays: 30, skills: ["Research", "Figma", "Analytics"], lastUpdated: "1 week ago", lastActive: "24 days ago" },
  { id: 10, name: "Jon Bell", initials: "JB", role: "Product Designer", location: "Remote · UK", experience: 3, notice: "Immediate", salary: "£50k", education: "Bachelors", activeDays: 30, skills: ["Figma", "UI design", "HTML"], lastUpdated: "1 week ago", lastActive: "28 days ago" },
  { id: 11, name: "Priya Shah", initials: "PS", role: "Senior Product Designer", location: "London · Hybrid", experience: 7, notice: "30 days", salary: "£77k", education: "Masters", activeDays: 60, skills: ["Figma", "Research", "Leadership"], lastUpdated: "9 days ago", lastActive: "45 days ago" },
  { id: 12, name: "Tom Russell", initials: "TR", role: "Interaction Designer", location: "Cardiff · Hybrid", experience: 4, notice: "60 days", salary: "£56k", education: "Bachelors", activeDays: 60, skills: ["Prototyping", "Figma", "Motion"], lastUpdated: "10 days ago", lastActive: "56 days ago" },
  { id: 13, name: "Zoë Brown", initials: "ZB", role: "Product Designer", location: "Remote · UK", experience: 6, notice: "30 days", salary: "£71k", education: "Masters", activeDays: 90, skills: ["Design systems", "Figma", "B2B SaaS"], lastUpdated: "2 weeks ago", lastActive: "75 days ago" },
  { id: 14, name: "Karan Kapoor", initials: "KK", role: "UX Designer", location: "London · On-site", experience: 5, notice: "90 days", salary: "£65k", education: "Bachelors", activeDays: 90, skills: ["Research", "Accessibility", "Figma"], lastUpdated: "2 weeks ago", lastActive: "80 days ago" },
  { id: 15, name: "Oliver Reed", initials: "OR", role: "Design Systems Designer", location: "Cambridge · Hybrid", experience: 8, notice: "60 days", salary: "£82k", education: "Masters", activeDays: 365, skills: ["Design systems", "Figma", "Tokens"], lastUpdated: "1 month ago", lastActive: "6 months ago" },
  { id: 16, name: "Saanvi Nair", initials: "SN", role: "Product Designer", location: "London · Hybrid", experience: 4, notice: "15 days", salary: "£60k", education: "Bachelors", activeDays: 365, skills: ["Figma", "Mobile", "Research"], lastUpdated: "1 month ago", lastActive: "9 months ago" },
  { id: 17, name: "Morris Cole", initials: "MC", role: "UX Designer", location: "Remote · UK", experience: 6, notice: "30 days", salary: "£68k", education: "Bachelors", activeDays: 365, skills: ["UI design", "Figma", "HTML"], lastUpdated: "2 months ago", lastActive: "11 months ago" },
  { id: 18, name: "Aisha Khan", initials: "AK", role: "Senior Product Designer", location: "London · Hybrid", experience: 7, notice: "30 days", salary: "£80k", education: "Masters", activeDays: 365, skills: ["Strategy", "Figma", "Research"], lastUpdated: "3 months ago", lastActive: "1 year ago" },
  { id: 19, name: "Ben Harris", initials: "BH", role: "Product Designer", location: "Oxford · Hybrid", experience: 5, notice: "60 days", salary: "£66k", education: "Bachelors", activeDays: 365, skills: ["Figma", "Prototyping", "Design systems"], lastUpdated: "3 months ago", lastActive: "1 year ago" },
  { id: 20, name: "Chloe Grant", initials: "CG", role: "UX Researcher", location: "London · Remote", experience: 6, notice: "90 days", salary: "£70k", education: "Masters", activeDays: 365, skills: ["Research", "Analytics", "Workshops"], lastUpdated: "4 months ago", lastActive: "1 year ago" },
];

const activeOptions = [{ label: "1 day", days: 1 }, { label: "3 days", days: 3 }, { label: "7 days", days: 7 }, { label: "15 days", days: 15 }, { label: "30 days", days: 30 }, { label: "60 days", days: 60 }, { label: "90 days", days: 90 }, { label: "1 year", days: 365 }, { label: "All", days: Infinity }];

export function RecruiterSourcing() {
  const [mandatory, setMandatory] = useState("Figma");
  const [exclude, setExclude] = useState("");
  const [minimumExperience, setMinimumExperience] = useState("0");
  const [education, setEducation] = useState("All");
  const [activeRange, setActiveRange] = useState("Infinity");
  const [page, setPage] = useState(1);
  const [searched, setSearched] = useState(false);
  const filtered = useMemo(() => candidateRecords.filter((candidate) => {
    const omitted = exclude.toLowerCase().split(/[ ,]+/).filter((term) => term.length > 2);
    const haystack = `${candidate.role} ${candidate.skills.join(" ")}`.toLowerCase();
    return candidate.experience >= Number(minimumExperience) && (education === "All" || candidate.education === education) && candidate.activeDays <= Number(activeRange) && matchesBooleanQuery(mandatory, haystack) && !omitted.some((term) => haystack.includes(term));
  }), [mandatory, exclude, minimumExperience, education, activeRange]);
  const current = filtered.slice((page - 1) * 10, page * 10);
  const pages = Math.max(1, Math.ceil(filtered.length / 10));
  return <WorkspaceShell workspace="recruiter" active="sourcing" title="Source candidates" description="Build precise talent searches with Boolean logic and transparent filters." actions={<Button variant="secondary">Save search</Button>}>
    <section className="sourcing-tabs"><button className="active">Manual Boolean search</button><button>Saved searches <Badge tone="neutral">3</Badge></button></section>
      <section className="sourcing-layout"><aside className="panel sourcing-controls"><SectionTitle eyebrow="Query builder" title="Candidate criteria"/><label className="form-field"><span>Mandatory skills or keywords</span><textarea value={mandatory} onChange={(event) => setMandatory(event.target.value)} placeholder={'e.g. Figma AND "design systems"'}/><small>Use AND / OR / NOT and quotation marks for exact phrases.</small></label><label className="form-field"><span>Exclude skills or keywords</span><input value={exclude} onChange={(event) => setExclude(event.target.value)} placeholder="e.g. agency, visual design"/></label><div className="form-grid sourcing-filter-grid"><label className="form-field"><span>Years of experience</span><select value={minimumExperience} onChange={(event) => setMinimumExperience(event.target.value)}>{[0,1,2,3,4,5,6,7,8,9,10].map((value) => <option key={value} value={value}>{value}+ years</option>)}</select></label><label className="form-field"><span>Salary range</span><select><option>Any salary</option><option>£50k – £65k</option><option>£65k – £80k</option><option>£80k+</option></select></label><label className="form-field"><span>Notice period</span><select><option>Any notice period</option><option>Immediate</option><option>15 days</option><option>30 days</option><option>60 days</option><option>90 days</option></select></label><label className="form-field"><span>Education</span><select value={education} onChange={(event) => setEducation(event.target.value)}><option>All</option><option>Bachelors</option><option>Masters</option></select></label></div><label className="form-field"><span>Active status</span><select value={activeRange} onChange={(event) => { setActiveRange(event.target.value); setPage(1); }}>{activeOptions.map((option) => <option value={option.days} key={option.label}>{option.label === "All" ? "All activity" : `Active in last ${option.label}`}</option>)}</select></label><Button onClick={() => { setPage(1); setSearched(true); }}>Search candidates</Button>{searched && <p className="search-confirmation">Search criteria applied. These results refresh as profiles change.</p>}</aside>
      <section className="sourcing-results"><header className="sourcing-results-head"><div><span className="eyebrow">Search results</span><h2>{filtered.length} matching candidates</h2></div><small>Showing {current.length} of {filtered.length} · 10 per page</small></header><div className="candidate-result-list">{current.map((candidate) => <CandidateResult candidate={candidate} key={candidate.id}/>)}</div>{current.length === 0 && <div className="empty-state"><span>⌕</span><h3>No candidates match this search</h3><p>Relax a required term or extend the active-status time window to see more people.</p><Button onClick={() => { setMandatory(""); setExclude(""); setActiveRange("Infinity"); }}>Clear search</Button></div>}<Pagination current={page} pages={pages} onChange={setPage}/></section></section>
  </WorkspaceShell>;
}

function CandidateResult({ candidate }: { candidate: CandidateRecord }) { return <article className="candidate-result"><span className="result-avatar">{candidate.initials}</span><div className="candidate-result-body"><h3>{candidate.name}</h3><p>{candidate.role} · {candidate.location}</p><div className="result-tags">{candidate.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="result-meta"><span>{candidate.experience} years experience</span><span>{candidate.education}</span><span>{candidate.notice} notice</span><span>{candidate.salary} expectation</span></div></div><div className="candidate-result-actions"><Badge tone={candidate.activeDays <= 3 ? "green" : candidate.activeDays <= 30 ? "blue" : "neutral"}>Active {candidate.activeDays <= 1 ? "today" : `${candidate.activeDays}d ago`}</Badge><Button variant="secondary">View profile</Button></div><footer className="candidate-freshness"><span>Profile updated {candidate.lastUpdated}</span><span>Active {candidate.lastActive}</span></footer></article>; }

function matchesBooleanQuery(query: string, haystack: string) {
  const contains = (rawTerm: string) => haystack.includes(rawTerm.replace(/["()]/g, "").trim().toLowerCase());
  const groups = query.split(/\s+AND\s+/i).map((group) => group.trim()).filter(Boolean);
  return groups.every((group) => {
    if (/^NOT\s+/i.test(group)) return !contains(group.replace(/^NOT\s+/i, ""));
    return group.split(/\s+OR\s+/i).some((term) => contains(term));
  });
}

function Pagination({ current, pages, onChange }: { current: number; pages: number; onChange: (page: number) => void }) { return <nav className="pagination" aria-label="Candidate result pages"><button disabled={current === 1} onClick={() => onChange(current - 1)}>← Previous</button>{Array.from({ length: pages }, (_, index) => <button className={current === index + 1 ? "active" : ""} onClick={() => onChange(index + 1)} key={index}>{index + 1}</button>)}<button disabled={current === pages} onClick={() => onChange(current + 1)}>Next →</button></nav>; }

const templates = [{ id: "intro", name: "Initial outreach", subject: "A product design role at {{company}}", content: "Hi {{first_name}},\n\nYour experience in {{top_skill}} stood out. I’m recruiting for a {{job_title}} role with {{company}} in {{location}}.\n\nWould you be open to a short conversation?\n\n{{recruiter_name}}" }, { id: "interview", name: "Interview invitation", subject: "Next step: {{job_title}} at {{company}}", content: "Hi {{first_name}},\n\nWe’d love to invite you to interview for the {{job_title}} role. Please choose a time that works for you.\n\n{{recruiter_name}}" }];

export function RecruiterCommunications() {
  const [templateId, setTemplateId] = useState("intro");
  const [sent, setSent] = useState(false);
  const [selectedCount, setSelectedCount] = useState(3);
  const template = templates.find((item) => item.id === templateId) ?? templates[0];
  const replaceVariables = (copy: string) => copy.replaceAll("{{first_name}}", "Amara").replaceAll("{{company}}", "Nexora Technologies").replaceAll("{{top_skill}}", "Figma and design systems").replaceAll("{{job_title}}", "Senior Product Designer").replaceAll("{{location}}", "London").replaceAll("{{recruiter_name}}", "Jordan Reyes");
  return <WorkspaceShell workspace="recruiter" active="communications" title="Communications" description="Create consistent, thoughtful candidate conversations at scale." actions={<Button variant="secondary">Manage templates</Button>}>
    {sent && <div className="creation-success">Your message is ready for the selected candidates. In production, delivery is queued, rate-limited and audit logged.</div>}
    <section className="communications-grid"><aside className="panel template-list"><SectionTitle eyebrow="Templates" title="Message library" action={<Button variant="quiet">+ New</Button>}/>{templates.map((item) => <button className={item.id === templateId ? "template-item active" : "template-item"} onClick={() => setTemplateId(item.id)} key={item.id}><strong>{item.name}</strong><small>{item.subject}</small></button>)}<div className="template-help"><b>Dynamic variables</b><p>Use {"{{first_name}}"}, {"{{job_title}}"}, {"{{company}}"}, {"{{location}}"}, {"{{top_skill}}"} and {"{{recruiter_name}}"}.</p></div></aside><section className="panel message-editor"><SectionTitle eyebrow="Bulk message" title={template.name}/><div className="selected-candidate-bar"><div><strong>{selectedCount} candidates selected</strong><small>Senior Product Designer pipeline</small></div><button onClick={() => setSelectedCount((value) => value === 3 ? 10 : 3)} className="button button-quiet">Change selection</button></div><label className="form-field"><span>Subject</span><input defaultValue={template.subject}/></label><label className="form-field"><span>Message</span><textarea defaultValue={template.content}/></label><footer className="message-actions"><span>Your message will be sent as individual emails, never as a shared recipient list.</span><Button onClick={() => setSent(true)}>Review {selectedCount} messages →</Button></footer></section><aside className="panel message-preview"><SectionTitle eyebrow="Live preview" title="Candidate view"/><div className="email-preview"><small>To: amara.mensah@email.com</small><strong>{replaceVariables(template.subject)}</strong><p>{replaceVariables(template.content)}</p></div><div className="compliance-callout"><b>Respectful messaging</b><p>Only contact candidates with a lawful purpose and provide a clear way to opt out. Delivery and template changes belong in the audit trail.</p></div></aside></section>
  </WorkspaceShell>;
}

export function RecruiterAnalyticsControls() {
  const [downloaded, setDownloaded] = useState(false);
  const download = () => { const csv = "Metric,Value\nActive jobs,4\nNew applications,31\nInterviews,8\nTime to hire (days),24\n"; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "sapienworx-recruitment-summary.csv"; link.click(); URL.revokeObjectURL(link.href); setDownloaded(true); };
  return <div className="analytics-control"><Button variant="secondary" onClick={download}>↓ Download analytics</Button>{downloaded && <small className="positive">CSV prepared</small>}</div>;
}

export function SocialJobCard() {
  const [shared, setShared] = useState("");
  return <section className="social-card-panel"><div><span className="eyebrow">Social distribution</span><h3>Share this role as a branded card</h3><p>The public card pulls the role details candidates need before they open the job link.</p><div className="social-actions"><button onClick={() => setShared("LinkedIn")}>in LinkedIn</button><button onClick={() => setShared("X")}>𝕏 Share</button><button onClick={() => setShared("link")}>⌁ Copy link</button></div>{shared && <small className="positive">{shared === "link" ? "Public link copied for sharing." : `Ready to share on ${shared}.`}</small>}</div><article className="social-preview"><span className="social-brand">N</span><small>Nexora Technologies is hiring</small><h4>Senior Product Designer</h4><p>6+ years · Figma · Design systems</p><footer>London, UK · Hybrid</footer></article></section>;
}

export function MiniRecruiterAnalytics() { return <section className="analytics-mini"><div><span>Pipeline health</span><strong>82%</strong><Meter value={82} color="green"/></div><div><span>Candidate response rate</span><strong>46%</strong><Meter value={46} color="blue"/></div></section>; }
