"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { apiClient } from "../lib/api-client";
import { Badge, Button, WorkspaceShell } from "./ui";
import styles from "./recruiter-job-management-command.module.css";

type Job={jobId:string;title:string;organisationName:string;location:string;department:string;employmentType:string;workplaceModel:string;minimumExperienceYears:number;maximumExperienceYears:number;minimumSalaryLakhs:number|null;maximumSalaryLakhs:number|null;salaryVisible:boolean;descriptionHtml:string;companyOverview:string;whyJoin:string;responsibilitiesHtml:string;hiringProcess:string;skills:string[];status:string;createdAt:string|null;updatedAt:string|null;publishedAt:string|null;publicPath:string};
type Managed={job:Job;applicants:number;newApplicants:number;screening:number;interviewing:number;finalStage:number;offers:number;onboarded:number;rejected:number;latestApplicationAt:string|null};
type Page={content:Managed[]};
type StatusFilter="ALL"|"DRAFT"|"ACTIVE"|"CLOSED"|"ARCHIVED";
function quality(job:Job){const checks=[Boolean(job.title.trim()),Boolean(job.location?.trim()),job.skills?.length>=3,Boolean(job.descriptionHtml?.trim()),Boolean(job.responsibilitiesHtml?.trim()),Boolean(job.hiringProcess?.trim()),job.minimumExperienceYears!=null&&job.maximumExperienceYears!=null,job.minimumSalaryLakhs!=null&&job.maximumSalaryLakhs!=null,Boolean(job.companyOverview?.trim()),Boolean(job.whyJoin?.trim())];return {score:Math.round(checks.filter(Boolean).length/checks.length*100),missing:checks.length-checks.filter(Boolean).length}}
function nice(value:string){return value.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function date(value:string|null){if(!value)return"—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"—":new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(parsed)}
function tone(status:string):"green"|"amber"|"blue"|"neutral"{return status==="ACTIVE"?"green":status==="DRAFT"?"amber":status==="CLOSED"?"blue":"neutral"}
export function RecruiterJobManagementCommand(){
 const[jobs,setJobs]=useState<Managed[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState<StatusFilter>("ALL"),[pending,setPending]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await apiClient<Page>("/api/recruiter/jobs?page=0&size=100");setJobs(response.content)}catch(reason){setError(reason instanceof Error?reason.message:"Jobs could not be loaded.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>jobs.filter(item=>(status==="ALL"||item.job.status===status)&&(!query.trim()||`${item.job.jobId} ${item.job.title} ${item.job.location} ${item.job.skills.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()))),[jobs,query,status]);
 const totals=useMemo(()=>visible.reduce((a,j)=>({applicants:a.applicants+j.applicants,newApps:a.newApps+j.newApplicants,interviews:a.interviews+j.interviewing+j.finalStage,offers:a.offers+j.offers,hires:a.hires+j.onboarded}),{applicants:0,newApps:0,interviews:0,offers:0,hires:0}),[visible]);
 async function setJobStatus(item:Managed,next:"ACTIVE"|"CLOSED"|"ARCHIVED"){if(!window.confirm(`${nice(next)} ${item.job.title}?`))return;setPending(item.job.jobId);try{const updated=await apiClient<Job>(`/api/recruiter/jobs/${encodeURIComponent(item.job.jobId)}/status/${next}`,{method:"POST"});setJobs(current=>current.map(row=>row.job.jobId===item.job.jobId?{...row,job:updated}:row))}catch(reason){setError(reason instanceof Error?reason.message:"Job status could not be updated.")}finally{setPending("")}}
 return <WorkspaceShell workspace="recruiter" active="my-jobs" title="Job operations" description="Vacancy quality, funnel movement and job controls in one scan-friendly table." actions={<Button href="/recruiter/jobs">+ Post a job</Button>}>
  <div className={styles.page}><section className={styles.summary}>{[["Applicants",totals.applicants],["New",totals.newApps],["Interview",totals.interviews],["Offers",totals.offers],["Hires",totals.hires]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section>
  <section className={styles.controls}><label><span>Search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Job ID, title, location or skill"/></label><label><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value as StatusFilter)}><option value="ALL">All</option><option value="ACTIVE">Published</option><option value="DRAFT">Draft</option><option value="CLOSED">Closed</option><option value="ARCHIVED">Archived</option></select></label><button type="button" onClick={()=>{setQuery("");setStatus("ALL")}}>Reset</button></section>
  {error&&<p className={styles.error} role="alert">{error}</p>}{loading?<p className={styles.state}>Loading job operations…</p>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Vacancy</th><th>Status</th><th>Quality</th><th>Pipeline</th><th>Latest activity</th><th>Actions</th></tr></thead><tbody>{visible.map(item=>{const q=quality(item.job);const stages=[item.newApplicants,item.screening,item.interviewing+item.finalStage,item.offers,item.onboarded];const max=Math.max(1,...stages);return <tr key={item.job.jobId}><td><a className={styles.job} href={`/recruiter/jobs/${encodeURIComponent(item.job.jobId)}`}><strong>{item.job.title}</strong><span><code>{item.job.jobId}</code> · {item.job.location}</span><small>{item.job.skills.slice(0,4).join(" · ")||"Skills pending"}</small></a></td><td><Badge tone={tone(item.job.status)}>{nice(item.job.status)}</Badge><small className={styles.date}>Created {date(item.job.createdAt)}</small></td><td><div className={styles.quality}><strong>{q.score}%</strong><span><i style={{width:`${q.score}%`}}/></span><small>{q.missing?q.missing+" checklist gaps":"Ready to distribute"}</small></div></td><td><div className={styles.pipeline} aria-label={`${item.applicants} applicants`}><strong>{item.applicants}</strong><div>{stages.map((value,index)=><i key={index} title={`${value}`} style={{height:`${Math.max(4,Math.round(value/max*30))}px`}}/>)}</div><small>{item.newApplicants} new · {item.interviewing+item.finalStage} interview · {item.offers} offer</small></div></td><td><span className={styles.activity}>{item.latestApplicationAt?date(item.latestApplicationAt):"No applications"}</span></td><td><div className={styles.actions}><a href={`/recruiter/jobs?jobId=${encodeURIComponent(item.job.jobId)}`}>Edit</a><a href={`/recruiter/jobs/${encodeURIComponent(item.job.jobId)}`}>Open</a>{item.job.status!=="ACTIVE"&&item.job.status!=="ARCHIVED"&&<button disabled={pending===item.job.jobId} onClick={()=>void setJobStatus(item,"ACTIVE")}>Publish</button>}{item.job.status==="ACTIVE"&&<button disabled={pending===item.job.jobId} onClick={()=>void setJobStatus(item,"CLOSED")}>Close</button>}{item.job.status!=="ARCHIVED"&&<button disabled={pending===item.job.jobId} onClick={()=>void setJobStatus(item,"ARCHIVED")}>Archive</button>}</div></td></tr>})}</tbody></table>{!visible.length&&<p className={styles.state}>No jobs match these filters.</p>}</div>}</div>
 </WorkspaceShell>
}
