FROM postgres:17-alpine
COPY migrations /migrations
COPY migrate.sh /usr/local/bin/sapienworx-migrate
RUN chmod 0555 /usr/local/bin/sapienworx-migrate
USER postgres
ENTRYPOINT ["/usr/local/bin/sapienworx-migrate"]
