import { ApprovalDecisionActions, ApprovalRequestForm, CaseCreateForm } from "@/components/admin/control-plane-actions";
import { requireAdminWorkspace } from "@/lib/admin-access-server";
import { adminAPI } from "@/lib/admin-server";

type Approval={id:string;action_type:string;target_type:string;requested_by:string;approval_reference:string;required_approvals:number;approvals:number;rejections:number;status:string;created_at:string};
type Case={id:string;case_type:string;subject_type:string;title:string;status:string;priority:string;assigned_to?:string;updated_at:string};
type OrgReview={id:string;company_id:string;review_type:string;status:string;assigned_to?:string;approval_id?:string;created_at:string};
type Telemetry={id:number;category:string;source:string;operation:string;status:string;latency_ms?:number;retry_count:number;backlog_count?:number;occurred_at:string};
type Evidence={id:string;evidence_type:string;environment:string;component:string;status:string;owner:string;reference:string;observed_at:string};
type Cost={id:string;provider:string;currency:string;period_start:string;period_end:string;actual_cost:number;forecast_cost?:number;budget_amount?:number;observed_at:string};
type Article={id:string;slug:string;title:string;status:string;current_revision:number;updated_at:string};
type Setting={key:string;description:string;high_risk:boolean;approval_id?:string;updated_at:string};
type Release={id:string;release_reference:string;environment:string;commit_sha:string;migration_reference:string;status:string;approval_id?:string;backup_evidence_id?:string;restore_test_evidence_id?:string;updated_at:string};
type ControlPlane={pending_approvals:number;open_cases:number;pending_organization_reviews:number;failed_telemetry_24h:number;open_alerts:number;draft_articles:number;pending_releases:number;approvals:Approval[];cases:Case[];organization_reviews:OrgReview[];telemetry:Telemetry[];operations:Evidence[];costs:Cost[];knowledge:Article[];settings:Setting[];releases:Release[];computed_at:string};\ntype RuntimeSnapshot={computed_at:string;database_status:string;database_total_connections:number;database_idle_connections:number;database_active_connections:number;database_max_connections:number;database_wait_count:number;go_routines:number;heap_alloc_bytes:number;heap_in_use_bytes:number;gc_cycles:number;telemetry_window:string;telemetry:{category:string;events:number;failures:number;average_latency_ms:number;max_backlog:number}[]};

const box="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_28px_rgba(55,65,140,0.05)]";
const dt=(v:string)=>new Date(v).toLocaleString("en-IN",{timeZone:"UTC"});

function Empty({children}:{children:string}){return <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm leading-6 text-slate-500">{children}</p>}
function Status({value}:{value:string}){const warn=["failed","critical","degraded","backlogged","rejected"].includes(value);const ok=["healthy","passed","approved","accepted","published","ok"].includes(value);return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${warn?"bg-red-50 text-red-700":ok?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{value.replaceAll("_"," ")}</span>}

export default async function ControlPlanePage(){
  await requireAdminWorkspace("control_plane.read");
  const [data,runtime]=await Promise.all([adminAPI<ControlPlane>("/api/v1/admin/control-plane"),adminAPI<RuntimeSnapshot>("/api/v1/admin/runtime-snapshot")]);
  const cards=[
    ["Pending approvals",data.pending_approvals],["Open cases",data.open_cases],["Organization reviews",data.pending_organization_reviews],
    ["Telemetry exceptions · 24h",data.failed_telemetry_24h],["Open alerts",data.open_alerts],["Content drafts",data.draft_articles],["Release checkpoints",data.pending_releases],
  ] as const;
  return <section className="min-w-0 space-y-6">
    <header className={box}>
      <p className="text-xs font-bold uppercase tracking-[.16em] text-[#5262c9]">Master Admin · governed operations</p>
      <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Control plane</h1>
      <p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">One review surface for high-risk approvals, moderation/privacy casework, organization governance, metadata-only delivery/parser telemetry, production evidence, AWS cost snapshots, Knowledge Hub revisions, controlled settings and release acceptance.</p>
      <p className="mt-2 text-xs leading-5 text-slate-500">Empty evidence feeds are intentionally shown as unconnected—not healthy. Message bodies, CV text, secrets and attachments are excluded by schema.</p>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value.toLocaleString("en-IN")}</p></div>)}</div>
    </header>

    <section className={box}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-slate-950">Live application runtime</h2><p className="mt-1 text-xs text-slate-500">Direct process and PostgreSQL pool measurements from this API instance.</p></div><Status value={runtime.database_status}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["DB active",runtime.database_active_connections],["DB idle",runtime.database_idle_connections],["DB max",runtime.database_max_connections],["Go routines",runtime.go_routines],["Heap MB",Math.round(runtime.heap_in_use_bytes/1048576)]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{Number(value).toLocaleString("en-IN")}</p></div>)}</div>{runtime.telemetry.length>0&&<div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{runtime.telemetry.map(item=><div key={item.category} className="rounded-xl border border-slate-100 p-3"><div className="flex justify-between gap-2"><p className="text-sm font-semibold text-slate-800">{item.category}</p><p className="text-xs text-slate-500">{runtime.telemetry_window}</p></div><p className="mt-1 text-xs text-slate-500">{item.events} events · {item.failures} exceptions · avg {Math.round(item.average_latency_ms)} ms · backlog {item.max_backlog}</p></div>)}</div>}</section>

    <div className="grid gap-5 xl:grid-cols-2">
      <section className={box}><h2 className="font-bold text-slate-950">Dual-approval queue</h2><div className="mt-4"><ApprovalRequestForm/></div><p className="mt-1 text-xs leading-5 text-slate-500">A requester cannot approve their own action; high-risk workflows retain separate reviewer evidence.</p><div className="mt-4 space-y-3">{data.approvals.length===0?<Empty>No approval requests recorded.</Empty>:data.approvals.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-slate-900">{v.action_type}</p><Status value={v.status}/></div><p className="mt-1 text-xs text-slate-500">{v.target_type} · ref {v.approval_reference}</p><p className="mt-2 text-sm text-slate-600">{v.approvals}/{v.required_approvals} approvals · {v.rejections} rejection(s)</p><p className="mt-2 text-[11px] text-slate-400">{dt(v.created_at)} UTC</p><ApprovalDecisionActions approval={v}/></article>)}</div></section>
      <section className={box}><h2 className="font-bold text-slate-950">Assigned moderation & privacy cases</h2><div className="mt-4"><CaseCreateForm/></div><p className="mt-1 text-xs leading-5 text-slate-500">Investigation state is recorded without copying private message or CV contents.</p><div className="mt-4 space-y-3">{data.cases.length===0?<Empty>No casework recorded.</Empty>:data.cases.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-slate-900">{v.title}</p><Status value={v.status}/></div><p className="mt-1 text-xs text-slate-500">{v.case_type} · {v.subject_type} · {v.priority}</p><p className="mt-2 text-xs text-slate-500">Reviewer: {v.assigned_to||"unassigned"} · updated {dt(v.updated_at)} UTC</p></article>)}</div></section>
    </div>

    <section className={box}><h2 className="font-bold text-slate-950">Organization governance</h2><p className="mt-1 text-xs leading-5 text-slate-500">Restriction, invitation, reassignment and duplicate/merge reviews are separate governed requests and can carry dual-approval evidence.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.organization_reviews.length===0?<div className="md:col-span-2"><Empty>No organization governance reviews recorded.</Empty></div>:data.organization_reviews.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-2"><p className="font-semibold text-slate-900">{v.review_type.replaceAll("_"," ")}</p><Status value={v.status}/></div><p className="mt-2 break-all font-mono text-[11px] text-slate-500">{v.company_id}</p><p className="mt-2 text-xs text-slate-500">Reviewer: {v.assigned_to||"unassigned"}</p></article>)}</div></section>

    <section className={box}><h2 className="font-bold text-slate-950">InMail, SES, notifications, WebSockets & CV parser</h2><p className="mt-1 text-xs leading-5 text-slate-500">Metadata only: failures, retries, backlog and latency. No message content or CV contents are exposed.</p>{data.telemetry.length===0?<div className="mt-4"><Empty>No telemetry collector evidence is connected yet.</Empty></div>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="py-2">Category</th><th>Operation</th><th>Status</th><th>Latency</th><th>Retries</th><th>Backlog</th><th>Observed</th></tr></thead><tbody>{data.telemetry.map(v=><tr key={v.id} className="border-t border-slate-100"><td className="py-3 font-semibold">{v.category}</td><td>{v.operation}</td><td><Status value={v.status}/></td><td>{v.latency_ms??"—"} ms</td><td>{v.retry_count}</td><td>{v.backlog_count??"—"}</td><td className="text-xs text-slate-500">{dt(v.occurred_at)} UTC</td></tr>)}</tbody></table></div>}</section>

    <div className="grid gap-5 xl:grid-cols-2">
      <section className={box}><h2 className="font-bold text-slate-950">Live operations, alerts & recovery evidence</h2><div className="mt-4 space-y-3">{data.operations.length===0?<Empty>No service/database, alert, release, migration, backup or restore-test evidence has been ingested.</Empty>:data.operations.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-2"><p className="font-semibold text-slate-900">{v.component}</p><Status value={v.status}/></div><p className="mt-1 text-xs text-slate-500">{v.evidence_type} · {v.environment} · owner {v.owner||"unassigned"}</p><p className="mt-2 text-[11px] text-slate-400">{dt(v.observed_at)} UTC</p></article>)}</div></section>
      <section className={box}><h2 className="font-bold text-slate-950">Actual AWS cost evidence</h2><div className="mt-4 space-y-3">{data.costs.length===0?<Empty>No Cost Explorer/budget snapshot is connected; no spend estimate is fabricated.</Empty>:data.costs.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><p className="text-2xl font-black text-slate-950">{v.currency} {v.actual_cost.toLocaleString("en-IN",{maximumFractionDigits:2})}</p><p className="mt-1 text-xs text-slate-500">{v.provider.toUpperCase()} · {new Date(v.period_start).toLocaleDateString("en-IN")}–{new Date(v.period_end).toLocaleDateString("en-IN")}</p><p className="mt-2 text-xs text-slate-500">Budget {v.budget_amount==null?"not supplied":v.currency+" "+v.budget_amount.toLocaleString("en-IN")}</p></article>)}</div></section>
    </div>

    <div className="grid gap-5 xl:grid-cols-2">
      <section className={box}><h2 className="font-bold text-slate-950">Knowledge Hub & controlled settings</h2><div className="mt-4 space-y-3">{data.knowledge.length===0?<Empty>No Knowledge Hub articles recorded.</Empty>:data.knowledge.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-2"><p className="font-semibold text-slate-900">{v.title}</p><Status value={v.status}/></div><p className="mt-1 text-xs text-slate-500">/{v.slug} · revision {v.current_revision}</p></article>)}</div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Operational settings</p>{data.settings.length===0?<p className="mt-2 text-sm text-slate-500">No controlled settings recorded.</p>:<div className="mt-2 space-y-2">{data.settings.map(v=><p key={v.key} className="text-sm text-slate-700"><span className="font-mono text-xs">{v.key}</span>{v.high_risk?" · dual approval required":""}</p>)}</div>}</div></section>
      <section className={box}><h2 className="font-bold text-slate-950">Release & production acceptance</h2><p className="mt-1 text-xs leading-5 text-slate-500">Acceptance is evidence-driven. Local green tests alone never mark a deployment accepted.</p><div className="mt-4 space-y-3">{data.releases.length===0?<Empty>No release acceptance checkpoint recorded.</Empty>:data.releases.map(v=><article key={v.id} className="rounded-xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-slate-900">{v.release_reference}</p><Status value={v.status}/></div><p className="mt-1 font-mono text-[11px] text-slate-500">{v.commit_sha}</p><p className="mt-2 text-xs text-slate-500">{v.environment} · migration {v.migration_reference||"not recorded"}</p><p className="mt-2 text-xs text-slate-500">Approval {v.approval_id?"recorded":"missing"} · backup {v.backup_evidence_id?"recorded":"missing"} · restore test {v.restore_test_evidence_id?"recorded":"missing"}</p></article>)}</div></section>
    </div>
    <p className="text-xs text-slate-400">Snapshot computed {dt(data.computed_at)} UTC.</p>
  </section>
}
