Foreground yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LeaveTemporaryFiles no
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 1
MaxQueue 2
StreamMaxLength 1536000
MaxFileSize 1536000
MaxScanSize 12M
MaxRecursion 8
MaxFiles 100
MaxScanTime 4000
CommandReadTimeout 5
ReadTimeout 5
SendBufTimeout 1000
ConcurrentDatabaseReload no
SelfCheck 60
LogFile /dev/null
LogSyslog no
LogVerbose no
LogClean no
AlertExceedsMax yes
AlertEncrypted yes
