import Link from "next/link";
import { Wordmark } from "@/components/brand/wordmark";
import { ThemeModeControl } from "@/components/theme/theme-mode-control";
import { LogoutButton } from "@/components/auth/logout-button";
import type { CompanyMember } from "@/lib/company";
export function CompanyShell({ member, children }: {
    member: CompanyMember;
    children: React.ReactNode;
}) {
    const owner = member.role === "primary_admin";
    return <div className="theme-surface swx-recruiter-workspace min-h-screen bg-[#f5f7fb] text-ink"><a href="#company-main" className="skip-link">Skip to company workspace</a><header className="sticky top-0 z-30 border-b border-line bg-white"><div className="mx-auto flex min-h-16 max-w-[100rem] flex-wrap items-center gap-4 px-4 sm:px-6"><Link href="/company" aria-label="Company workspace"><Wordmark /></Link><span className="hidden text-sm text-ink-muted md:block">{owner ? "Company administration" : "Assigned hiring workspace"}</span><div className="ml-auto flex items-center gap-2"><ThemeModeControl compact/><LogoutButton /></div></div></header><div className="mx-auto grid grid-cols-[minmax(0,1fr)] max-w-[100rem] gap-5 px-4 py-6 sm:px-6 lg:grid-cols-[12rem_minmax(0,1fr)]"><aside className="min-w-0"><nav aria-label="Company navigation" className="flex gap-1 overflow-x-auto rounded-xl border border-line bg-white p-2 lg:sticky lg:top-24 lg:grid">{(owner ? [["Company profile", "/company"], ["Team & invitations", "/company/team"], ["Plan & usage", "/company/plan"], ["Company reviews", "/company/reviews"], ["Audit history", "/company/audit"]] : member.role === "sub_admin" ? [["Assigned jobs", "/company"], ["Team & invitations", "/company/team"]] : [["Assigned jobs", "/company"]]).map(([label, href]) => <Link key={href} href={href} className="min-h-11 shrink-0 content-center rounded-lg px-3 text-sm font-medium hover:bg-indigo-soft focus-visible:ring-2 focus-visible:ring-indigo">{label}</Link>)}</nav><div className="mt-4 hidden gap-2 text-sm lg:grid text-ink-muted"><p>{member.name}</p><p>{owner ? "Primary Company Admin" : member.role.replaceAll("_", " ")}</p>{member.scope.all && member.role !== "collaborator" && <Link href="/recruiter" className="min-h-11 content-center font-semibold text-indigo">Open Recruit →</Link>}<Link href={`/companies/${member.company_id}`} className="min-h-11 content-center text-indigo">Public company page →</Link></div><div className="mt-3 flex flex-wrap gap-4 text-sm lg:hidden">{member.scope.all && member.role !== "collaborator" && <Link href="/recruiter" className="min-h-11 content-center text-indigo">Open Recruit →</Link>}<Link href={`/companies/${member.company_id}`} className="min-h-11 content-center text-indigo">Public company page →</Link></div></aside><main id="company-main" tabIndex={-1} className="min-w-0 space-y-5 outline-none">{children}</main></div></div>;
}
