"use client";
import Link from "next/link";
import { useState } from "react";
import { apiRequest } from "@/lib/api";
import { emptySetup, type CompanySetup } from "@/lib/company";
import { recruiterInput, recruiterPrimary, recruiterSecondary } from "@/components/recruiter/workspace-ui";
const steps = [["profile", "Company profile"], ["structure", "Organisation structure"], ["team", "Invite your team"], ["hiring", "Hiring settings"], ["privacy", "Privacy & compliance"], ["review", "Review setup"]];
export function CompanySetupWizard({ initial }: {
    initial: CompanySetup;
}) {
    const normal = { ...emptySetup, ...initial, profile: { ...emptySetup.profile, ...initial.profile }, structure: { ...emptySetup.structure, ...initial.structure }, hiring: { ...emptySetup.hiring, ...initial.hiring }, privacy: { ...emptySetup.privacy, ...initial.privacy } };
    const [value, setValue] = useState(normal), [saved, setSaved] = useState(normal), [listDraft, setListDraft] = useState<Record<string, string>>({}), [step, setStep] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
    function field(section: "profile" | "structure" | "hiring" | "privacy", key: string, label: string, options: {
        area?: boolean;
        list?: boolean;
        type?: string;
        required?: boolean;
        max?: number;
    } = {}) { const raw = value[section] as unknown as Record<string, unknown>; const current = options.list ? (listDraft[`${section}.${key}`] ?? (raw[key] as string[] ?? []).join(", ")) : String(raw[key] ?? ""); function change(text: string) { if (options.list)
        setListDraft(d => ({ ...d, [`${section}.${key}`]: text })); setValue(v => ({ ...v, [section]: { ...v[section], [key]: options.list ? text.split(",").map(x => x.trim()).filter(Boolean) : options.type === "number" ? Number(text) : text } })); } return <label key={key} className="grid min-w-0 gap-2 text-sm font-medium">{label}{options.area ? <textarea className={`${recruiterInput} min-h-32 resize-y py-3`} value={current} maxLength={options.max ?? 6000} onChange={e => change(e.target.value)} required={options.required}/> : <input className={recruiterInput} type={options.type ?? "text"} value={current} maxLength={options.max ?? 500} min={options.type === "number" ? 0 : undefined} max={options.type === "number" ? 3650 : undefined} onChange={e => change(e.target.value)} required={options.required}/>}</label>; }
    async function save(complete: boolean) { setBusy(true); setError(""); setNotice(""); const next = { ...value, completed_steps: complete ? Array.from(new Set([...value.completed_steps, steps[step][0]])) : value.completed_steps }; try {
        await apiRequest("/api/v1/company/setup", { method: "PUT", body: JSON.stringify(next) });
        setSaved(next);
        setValue(next);
        setNotice(step === 5 && complete ? "Company setup completed." : "Draft saved.");
        if (complete && step < 5)
            setStep(step + 1);
    }
    catch (e) {
        setError(e instanceof Error ? e.message : "Could not save company setup.");
    }
    finally {
        setBusy(false);
    } }
    return <section><header><p className="text-sm font-medium text-indigo">Company administration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-navy">{initial.completed_at ? "Company profile & settings" : "Welcome to your company workspace"}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-ink-muted">Set up your public company profile, team and hiring policies. Drafts stay saved between visits. Organisation structure is optional.</p></header><div className="mt-6 grid grid-cols-[minmax(0,1fr)] gap-5 xl:grid-cols-[14rem_minmax(0,1fr)]"><nav aria-label="Company setup steps" className="flex min-w-0 gap-2 overflow-x-auto xl:sticky xl:top-24 xl:block xl:self-start">{steps.map(([key, label], i) => <button key={key} type="button" aria-current={step === i ? "step" : undefined} disabled={busy} onClick={() => { setStep(i); setError(""); setNotice(""); }} className={`mb-1 flex min-h-12 shrink-0 items-center gap-3 rounded-lg px-3 text-left text-sm xl:w-full ${step === i ? "bg-indigo-soft font-semibold text-indigo" : "text-ink-muted hover:bg-white"}`}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-current text-xs">{value.completed_steps.includes(key) ? "✓" : i + 1}</span>{label}</button>)}</nav><form className="min-w-0 rounded-xl border border-line bg-white p-5 sm:p-6" onFocusCapture={e => { const target = e.target as HTMLElement; if (target.matches("input,textarea,select") && target.getBoundingClientRect().bottom > window.innerHeight - 164)
        target.scrollIntoView({ block: "center", behavior: "auto" }); }} onSubmit={e => { e.preventDefault(); void save(true); }}><h2 className="text-xl font-semibold text-navy">{steps[step][1]}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">
 {step === 0 && <>{field("profile", "industry", "Industry", { required: true, max: 120 })}{field("profile", "size", "Company size", { max: 60 })}{field("profile", "headquarters", "Headquarters", { max: 160 })}{field("profile", "website", "Website", { type: "url" })}<div className="sm:col-span-2">{field("profile", "about", "About your company", { area: true, required: true })}</div>{field("profile", "logo_url", "Public logo URL", { type: "url" })}{field("profile", "banner_url", "Public banner URL", { type: "url" })}{field("profile", "locations", "Locations (comma separated)", { list: true })}{field("profile", "benefits", "Benefits (comma separated)", { list: true })}<div className="sm:col-span-2">{field("profile", "culture", "Work culture", { area: true, max: 3000 })}</div>{field("profile", "social_links", "Social links (HTTPS; comma separated)", { list: true })}<p className="text-sm leading-6 text-ink-muted">Use approved company assets. These fields appear on your public company page.</p></>}
 {step === 1 && <>{field("structure", "departments", "Departments (comma separated)", { list: true })}{field("structure", "locations", "Hiring locations (comma separated)", { list: true })}<p className="sm:col-span-2 text-sm leading-6 text-ink-muted">Access scopes use job departments, locations or selected job IDs. You can keep this simple and configure scopes when inviting each person.</p><button type="button" className={recruiterSecondary} disabled={busy} onClick={() => void save(true)}>Skip organisation structure</button></>}
 {step === 2 && <div className="sm:col-span-2 space-y-4"><p className="text-sm leading-6 text-ink-muted">Invite Sub-admins, Recruiters and hiring collaborators with official work email addresses. Every invite expires after seven days and requires email verification. No existing user is automatically assigned ownership.</p><Link href="/company/team" className={recruiterSecondary}>Open team & invitations</Link><p className="text-sm text-ink-muted">You can invite your team later and continue setup now.</p></div>}
 {step === 3 && <>{field("hiring", "timezone", "Default hiring timezone", { required: true })}{field("hiring", "referral_policy", "Company referral guidance", { area: true, max: 2000 })}{field("hiring", "interview_guidance", "Interview guidance", { area: true, max: 2000 })}<p className="text-sm leading-6 text-ink-muted">Meeting links are entered manually in interview scheduling. Job-specific referral terms continue to control each vacancy.</p></>}
 {step === 4 && <>{field("privacy", "notice_url", "Company privacy notice (HTTPS)", { type: "url" })}<div className="sm:col-span-2"><p className="text-sm leading-6 text-ink-muted">SapienWorx’s existing retention and privacy controls remain in force. Company retention preferences need review before enforcement.</p><label className="mt-4 flex min-h-11 items-start gap-3 text-sm leading-6"><input type="checkbox" className="mt-1.5" checked={value.privacy.acknowledged} onChange={e => setValue(v => ({ ...v, privacy: { ...v.privacy, acknowledged: e.target.checked } }))} required/>I have reviewed our responsibilities for candidate privacy and appropriate access to hiring data.</label></div></>}
 {step === 5 && <div className="sm:col-span-2 space-y-4 text-sm leading-6"><dl className="grid gap-3 sm:grid-cols-2">{[["Industry", value.profile.industry], ["Company size", value.profile.size], ["Headquarters", value.profile.headquarters], ["Timezone", value.hiring.timezone], ["Departments", value.structure.departments?.join(", ") || "Not configured"], ["Privacy acknowledgement", value.privacy.acknowledged ? "Reviewed" : "Required"]].map(([label, data]) => <div key={label}><dt className="text-ink-muted">{label}</dt><dd className="break-words font-medium">{data || "Not provided"}</dd></div>)}</dl><p>Company administration permissions are distinct from platform administration. Subscription expiry preserves hiring records. Reviews remain subject to SapienWorx moderation.</p></div>}
 </div>{error && <p role="alert" className="mt-5 text-sm swx-company-error">{error}</p>}{notice && <p role="status" className="mt-5 text-sm swx-company-success">{notice}</p>}<footer className="sticky bottom-0 -mx-5 -mb-5 mt-8 flex flex-wrap gap-3 border-t border-line bg-white/95 p-4 sm:-mx-6 sm:-mb-6"><button type="submit" disabled={busy} className={recruiterPrimary}>{busy ? "Saving…" : step === 5 ? "Complete setup" : "Save & continue"}</button><button type="button" disabled={busy} className={recruiterSecondary} onClick={() => void save(false)}>Save draft</button><button type="button" disabled={busy} className={recruiterSecondary} onClick={() => { setValue(saved); setListDraft({}); setError(""); setNotice("Unsaved changes discarded."); }}>Cancel changes</button></footer></form></div></section>;
}
