import Link from "next/link";
import { requireAdminWorkspace } from "@/lib/admin-access-server";
import { adminAPI,AdminBackendError } from "@/lib/admin-server";
import type { AdminApplicationHistory } from "@/lib/admin";
import { recruitmentDate } from "@/lib/admin-recruitment";
import { adminSurface,RecruitmentPagination } from "@/components/admin/recruitment-workspace";

export default async function ApplicationHistoryPage({params,searchParams}:{params:Promise<{applicationID:string}>;searchParams:Promise<{page?:string}>}) {
  await requireAdminWorkspace("recruitment.read"); const {applicationID}=await params; const search=await searchParams;
  const query=new URLSearchParams({page:search.page||"1",limit:"25"});
  let data:AdminApplicationHistory;
  try { data=await adminAPI(`/api/v1/admin/applications/${encodeURIComponent(applicationID)}/history?${query}`); } catch(error) { if(error instanceof AdminBackendError&&(error.status===404||error.status===400)) return <section className={adminSurface}><h1 className="text-2xl font-bold">Application record unavailable</h1><p className="mt-3 text-sm text-slate-500">This ID is invalid or no longer exists. No historical data has been invented.</p><Link className="mt-4 inline-block font-bold text-indigo-600" href="/swx-command-centre/applications">Back to applications</Link></section>; throw error; }
  const a=data.application;
  return <section className="min-w-0 space-y-5"><header className={adminSurface+" sm:p-8"}><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Recorded recruitment history</p><h1 className="mt-3 text-3xl font-bold text-slate-950">Application timeline</h1><h2 className="mt-4 text-lg font-bold text-slate-800">{a.job_title}</h2><p className="mt-2 text-sm text-slate-500">{a.company_name} · {a.job_reference} · Current stage: {a.stage.replaceAll("_"," ")}</p><p className="mt-3 break-all font-mono text-xs leading-6 text-slate-500">Application {a.id}<br/>Candidate {a.candidate_id}<br/>Job {a.job_id}</p><Link className="mt-4 inline-block text-sm font-bold text-indigo-600" href={`/swx-command-centre/applications?job_id=${a.job_id}`}>View this job’s applications →</Link></header><p role="note" className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-xs leading-6 text-amber-900">History is limited to records actually retained. Missing events are not evidence that no action occurred. Submitted/interview-created records lack an independently recorded actor; organizer or candidate association is not substituted. Interview creation entries show the current schedule, not a reconstructed original schedule. Offer/hired transitions are stage changes, not proof that an offer was issued or employment started.</p><ol className="space-y-3" aria-label="Recorded application events">{data.items.map(event=><li key={`${event.kind}-${event.id}`} className={adminSurface}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-bold text-slate-900">{event.kind.replaceAll("_"," ")}</h2><time dateTime={event.occurred_at} className="text-xs text-slate-500">{recruitmentDate(event.occurred_at)}</time></div><p className="mt-3 break-all text-xs text-slate-600">{event.actor_id?`Recorded recruiter actor: ${event.actor_id}`:"Actor not independently recorded"}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(event.changes).map(([key,value])=><div key={key} className="min-w-0"><dt className="text-xs font-semibold capitalize text-slate-500">{key.replaceAll("_"," ")}</dt><dd className="mt-1 break-all text-sm text-slate-800">{String(value)}</dd></div>)}</dl></li>)}</ol><RecruitmentPagination data={data} query={query} path={`/swx-command-centre/applications/${a.id}`}/></section>;
}
