"use client";
import {useId,useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {apiRequest} from "@/lib/api";
import {RecruiterDrawer,recruiterInput,recruiterPrimary,recruiterSecondary} from "./workspace-ui";
export type NamedPool={id:string;name:string;kind:"manual"|"smart";visibility:"private"|"team"|"company";owner_name:string;count:number;can_edit:boolean;criteria:Record<string,string>};
export function CreatePool({team}:{team:{user_id:string;full_name:string}[]}){const router=useRouter(),formID=useId();const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[kind,setKind]=useState("manual"),[visibility,setVisibility]=useState("private"),[error,setError]=useState("");
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const criteria:Record<string,string>={};if(kind==="smart")for(const key of ["q","skills","location","min_experience","max_experience","max_notice_days"]){const value=String(f.get(key)||"").trim();if(value)criteria[key]=value;}const p=await apiRequest<NamedPool>("/api/v1/recruiter/talent-pools",{method:"POST",body:JSON.stringify({name:String(f.get("name")||"").trim(),kind,visibility,criteria,team_ids:f.getAll("team_id")})});setOpen(false);router.push(`/recruiter/talent-pool?pool_id=${p.id}`);router.refresh();}catch(c){setError(c instanceof Error?c.message:"Could not create pool.")}finally{setBusy(false)}}
return <><button className={recruiterPrimary} onClick={()=>setOpen(true)}>+ Create pool</button><RecruiterDrawer open={open} onClose={()=>{if(!busy)setOpen(false)}} title="Create talent pool" footer={<><button className={recruiterSecondary} disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button type="submit" form={formID} disabled={busy} className={recruiterPrimary}>{busy?"Creating…":"Create pool"}</button></>}><form id={formID} onSubmit={create} className="grid gap-4"><label className="grid gap-1 text-sm font-semibold text-ink">Pool name<input name="name" required maxLength={120} className={recruiterInput}/></label><label className="grid gap-1 text-sm font-semibold text-ink">Type<select aria-label="Type" className={recruiterInput} value={kind} onChange={e=>setKind(e.target.value)}><option value="manual">Pool — manually saved candidates</option><option value="smart">Smart Pool — live criteria</option></select></label><p className="text-sm leading-6 text-ink-muted">{kind==="smart"?"Membership reflects current profiles and discovery consent whenever this pool is opened. Saved Searches remain separate criteria you run manually.":"Keep a curated group for future roles. Sharing a pool never overrides candidate privacy."}</p><label className="grid gap-1 text-sm font-semibold text-ink">Visibility<select aria-label="Visibility" className={recruiterInput} value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">Private — only me</option><option value="team">Team — selected recruiters can view</option><option value="company">Company — verified company recruiters can view</option></select></label>{visibility==="team"&&<fieldset className="grid gap-2"><legend className="text-sm font-semibold text-ink">Recruiters with viewing access</legend>{team.map(m=><label key={m.user_id} className="flex min-h-11 items-center gap-2 text-sm text-ink"><input type="checkbox" name="team_id" value={m.user_id} className="h-4 w-4 accent-indigo"/>{m.full_name}</label>)}</fieldset>}{kind==="smart"&&<fieldset className="grid gap-3"><legend className="mb-2 text-sm font-semibold text-ink">Live professional criteria</legend>{[["q","Keywords"],["skills","Required skills (comma separated)"],["location","Location"],["min_experience","Experience from (years)"],["max_experience","Experience to (years)"],["max_notice_days","Notice up to (days)"]].map(([name,label])=><label key={name} className="grid gap-1 text-xs font-semibold text-ink-muted">{label}<input name={name} type={name.includes("experience")||name==="max_notice_days"?"number":"text"} min="0" step={name.includes("experience")?"0.5":undefined} className={recruiterInput}/></label>)}</fieldset>}{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}</form></RecruiterDrawer></>}
