"use client";

import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { RecruiterProductHeader } from "@/components/recruiter/recruiter-product-header";
import { DiscoveryCandidateActions } from "@/components/recruiter/discovery-actions";
import { RecruiterDataTable, RecruiterDrawer, WorkspaceSkeleton, WorkspaceState, recruiterInput, recruiterPrimary, recruiterSecondary } from "@/components/recruiter/workspace-ui";
import { TaxonomyInput } from "@/components/workforce/taxonomy-input";
import { apiRequest, APIRequestError } from "@/lib/api";
import { experience } from "@/lib/recruiter";
import { activeDiscovery, cleanDiscovery, discoveryDefaults, discoveryFieldMap, discoverySections, discoverySummary, validateDiscovery, type DiscoveryCandidate, type DiscoveryField, type DiscoveryResults, type DiscoverySection, type DiscoveryValues, type SearchRecord } from "@/lib/discovery";

function ChipsInput({ field, value, onChange, error }: { field: DiscoveryField; value: string; onChange: (value: string) => void; error?: string }) {
  const [draft, setDraft] = useState("");
  const terms = value.split(",").map(v => v.trim()).filter(Boolean);
  function add(raw: string) { const next = [...terms]; for (const term of raw.split(",").map(v => v.trim()).filter(Boolean)) if (!next.some(v => v.toLowerCase() === term.toLowerCase())) next.push(term); onChange(next.join(", ")); setDraft(""); }
  return <div className="grid min-w-0 gap-2"><div className="flex flex-wrap gap-1.5">{terms.map(term => <button type="button" key={term} onClick={() => onChange(terms.filter(v => v !== term).join(", "))} aria-label={`Remove ${term} from ${field.label}`} className="swx-skill-chip inline-flex min-h-9 max-w-full items-center gap-2 rounded-full border border-line bg-slate-50 px-3 text-xs text-ink"><span className="break-words">{term}</span><span aria-hidden="true">×</span></button>)}</div>{field.taxonomy ? <TaxonomyInput id={`discovery-${field.key}`} value={draft} onValueChange={setDraft} onSelect={item => add(item.canonical_name)} onCommit={add} entityTypes={field.taxonomy} ariaLabel={field.label} ariaInvalid={!!error} ariaDescribedBy={error ? `discovery-error-${field.key}` : undefined} placeholder="Type a value and press Enter" className={recruiterInput} maxLength={120} /> : <input id={`discovery-${field.key}`} aria-invalid={!!error} aria-describedby={error ? `discovery-error-${field.key}` : undefined} value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && draft.trim()) { e.preventDefault(); add(draft); } }} onBlur={() => { if (draft.trim()) add(draft); }} placeholder="Type a value and press Enter" className={recruiterInput} maxLength={120} />}</div>;
}

function SearchSection({ section, values, setValue, errors }: { section: DiscoverySection; values: DiscoveryValues; setValue: (key: string, value: string) => void; errors: Record<string, string> }) {
  const [open, setOpen] = useState(Boolean(section.open));
  const configured = section.fields.filter(field => activeDiscovery(values).some(([key]) => key === field.key));
  useEffect(() => { if (section.fields.some(field => errors[field.key])) setOpen(true); }, [errors, section.fields]);
  return <details open={open} onToggle={event => setOpen(event.currentTarget.open)} className="border-b border-line/70 py-1" data-testid={`discovery-section-${section.id}`}>
    <summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-3 py-3"><div className="min-w-0"><h2 className="text-base font-semibold text-navy">{section.title}{configured.length > 0 && <span className="ml-2 rounded-full bg-indigo-soft px-2 py-0.5 text-xs text-indigo">{configured.length}</span>}</h2>{!open && configured.length > 0 && <p className="mt-1 line-clamp-2 text-xs text-ink-muted">{configured.map(field => `${field.label}: ${values[field.key]}`).join(" · ")}</p>}</div><span aria-hidden="true">{open ? "−" : "+"}</span></summary>
    <div className="pb-5">{section.description && <p className="mb-4 text-sm leading-6 text-ink-muted">{section.description}</p>}<div className="grid min-w-0 gap-x-5 gap-y-4 sm:grid-cols-2">{section.fields.map(field => {
      if (field.key === "ug_qualification" && values.ug_mode !== "specific" || field.key === "pg_qualification" && values.pg_mode !== "specific") return null;
      const error = errors[field.key];
      return <div key={field.key} className={`min-w-0 ${field.key === "q" || field.type === "check" ? "sm:col-span-2" : ""}`}>{field.type === "check" ? <label className="flex min-h-11 items-start gap-2 text-sm text-ink"><input type="checkbox" disabled={field.disabled} checked={values[field.key] === "true"} onChange={e => setValue(field.key, e.target.checked ? "true" : "")} className="mt-1 h-4 w-4 shrink-0 accent-indigo" />{field.label}</label> : <><label htmlFor={`discovery-${field.key}`} className="mb-1.5 block text-sm font-medium text-ink">{field.label}</label>{field.type === "chips" ? <ChipsInput error={error} field={field} value={values[field.key] || ""} onChange={value => setValue(field.key, value)} /> : field.type === "select" ? <select id={`discovery-${field.key}`} disabled={field.disabled} value={values[field.key] || field.options?.[0]?.[0] || ""} onChange={e => setValue(field.key, e.target.value)} className={recruiterInput}>{field.options?.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select> : field.taxonomy ? <TaxonomyInput id={`discovery-${field.key}`} value={values[field.key] || ""} onValueChange={value => setValue(field.key, value)} entityTypes={field.taxonomy} className={recruiterInput} ariaLabel={field.label} ariaInvalid={!!error} ariaDescribedBy={error ? `discovery-error-${field.key}` : undefined} /> : <input id={`discovery-${field.key}`} disabled={field.disabled} value={values[field.key] || ""} onChange={e => setValue(field.key, e.target.value)} type={field.type || "text"} min={field.type === "number" ? 0 : undefined} max={field.key.includes("experience") ? 60 : undefined} step={field.type === "number" ? "any" : undefined} maxLength={field.key === "q" ? 300 : 120} aria-invalid={!!error} aria-describedby={error ? `discovery-error-${field.key}` : undefined} className={recruiterInput} />}</>}{field.hint && <p className="mt-1.5 text-xs leading-5 text-ink-muted">{field.hint}</p>}{error && <p id={`discovery-error-${field.key}`} role="alert" className="mt-1.5 text-sm text-rose-700">{error}</p>}</div>;
    })}</div>{configured.length > 0 && <button type="button" onClick={() => section.fields.forEach(field => setValue(field.key, discoveryDefaults[field.key] || ""))} className="mt-4 min-h-11 text-sm font-semibold text-indigo">Clear section</button>}</div>
  </details>;
}

export function DiscoverTalentWorkspace({ userID, companyName, initialValues, initialResults, initialError, saved, recent, editingSearch }: { userID: string; companyName: string; editingSearch?: SearchRecord; initialValues: DiscoveryValues; initialResults: DiscoveryResults | null; initialError: string; saved: SearchRecord[]; recent: SearchRecord[] }) {
  const [values, setValues] = useState<DiscoveryValues>({ ...discoveryDefaults, ...initialValues });
  const [applied, setApplied] = useState<DiscoveryValues>(initialValues);
  const [results, setResults] = useState(initialResults);
  const [resultsMode, setResultsMode] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState(initialError);
  const [errors, setErrors] = useState<Record<string, string>>({}), [ready, setReady] = useState(false);
  const [preview, setPreview] = useState<DiscoveryCandidate | null>(null), [saveOpen, setSaveOpen] = useState(false);
  const [saving, setSaving] = useState(false), [name, setName] = useState(editingSearch?.name || ""), [frequency, setFrequency] = useState(editingSearch?.alert_enabled ? editingSearch.alert_frequency || "daily" : "off");
  const [searchID, setSearchID] = useState(editingSearch?.id ? String(editingSearch.id) : "");
  const [savedItems, setSavedItems] = useState(saved), [recentItems, setRecentItems] = useState(recent), [notice, setNotice] = useState("");
  const abort = useRef<AbortController | null>(null), resultsHeading = useRef<HTMLHeadingElement>(null);
  const storageKey = `swx-talent-search:${userID}`;
  useEffect(() => {
    try { if (!Object.keys(initialValues).length) { const stored = JSON.parse(sessionStorage.getItem(storageKey) || "null"); if (stored && typeof stored === "object" && !Array.isArray(stored) && Object.values(stored).every(v => typeof v === "string")) { setValues({ ...discoveryDefaults, ...cleanDiscovery(stored) }); setResults(null); } } } catch { /* An unavailable draft never blocks search. */ }
    setReady(true); return () => abort.current?.abort();
  }, [storageKey, initialValues]);
  useEffect(() => { if (ready) { try { sessionStorage.setItem(storageKey, JSON.stringify(cleanDiscovery(values))); } catch { /* Search works without browser storage. */ } } }, [values, ready, storageKey]);
  function setValue(key: string, value: string) { setValues(current => ({ ...current, [key]: value })); setErrors(current => { const next = { ...current }; delete next[key]; return next; }); }
  async function run(next = values, page = 1) {
    // Restore the stored draft before accepting a search from the server-rendered controls.
    if (!ready) return;
    const validation = validateDiscovery(next); setErrors(validation); setNotice("");
    if (Object.keys(validation).length) { setResultsMode(false); window.requestAnimationFrame(() => document.getElementById(`discovery-${Object.keys(validation)[0]}`)?.focus()); return; }
    abort.current?.abort(); const controller = new AbortController(); abort.current = controller; setBusy(true); setError(""); setResultsMode(true);
    const filters = { ...cleanDiscovery(next), page: String(page), page_size: next.page_size || "25" };
    try {
      const response = await apiRequest<DiscoveryResults>("/api/v1/recruiter/discover", { method: "POST", body: JSON.stringify({ filters }), signal: controller.signal });
      if (controller.signal.aborted) return; setResults(response); setApplied(filters); setValues(next);
      setRecentItems(current => [{ id: Date.now(), filters }, ...current.filter(item => discoverySummary(item.filters) !== discoverySummary(filters))].slice(0, 8));
      window.requestAnimationFrame(() => resultsHeading.current?.focus());
    } catch (cause) { if (controller.signal.aborted) return; setResults(null); setError(cause instanceof APIRequestError && cause.status === 400 ? "Check the Boolean syntax, experience range and qualification selections, then try again." : cause instanceof APIRequestError && cause.status === 429 ? "Search is temporarily rate limited. Wait before trying again." : cause instanceof Error ? cause.message : "Search is unavailable. Your criteria are retained."); }
    finally { if (!controller.signal.aborted) setBusy(false); }
  }
  async function saveSearch(event: FormEvent) {
    event.preventDefault(); if (saving || !name.trim()) return; const validation = validateDiscovery(values);
    if (Object.keys(validation).length) { setErrors(validation); setNotice("Correct the search criteria before saving."); return; } setSaving(true); setNotice("");
    try {
      if (searchID) {
        const item = await apiRequest<SearchRecord>(`/api/v1/recruiter/saved-searches/${encodeURIComponent(searchID)}`, { method: "PATCH", body: JSON.stringify({ name: name.trim(), filters: cleanDiscovery(values), enabled: frequency !== "off", frequency: frequency === "off" ? "daily" : frequency }) });
        setSavedItems(current => [item, ...current.filter(saved => String(saved.id) !== searchID)]);
        setNotice("Saved search updated. Your alert setting is retained."); setSaveOpen(false); return;
      }
      let item = await apiRequest<SearchRecord>("/api/v1/recruiter/saved-searches", { method: "POST", body: JSON.stringify({ name: name.trim(), filters: cleanDiscovery(values) }) }); setSavedItems(current => [item, ...current]);
      if (frequency !== "off") { try { item = await apiRequest<SearchRecord>(`/api/v1/recruiter/saved-searches/${item.id}`, { method: "PATCH", body: JSON.stringify({ enabled: true, frequency }) }); setSavedItems(current => current.map(saved => saved.id === item.id ? item : saved)); } catch { setNotice("Search saved. Its alert could not be enabled; retry from Saved Searches."); setSaveOpen(false); return; } }
      setNotice("Search saved."); setSaveOpen(false); setName("");
    } catch (cause) { setNotice(cause instanceof Error ? cause.message : "Could not save search. Your criteria are retained."); } finally { setSaving(false); }
  }
  function clear() { setSearchID(""); setName(""); setFrequency("off"); abort.current?.abort(); setBusy(false); setValues({ ...discoveryDefaults }); setApplied({}); setResults(null); setResultsMode(false); setErrors({}); setError(""); }
  const chips = activeDiscovery(resultsMode ? applied : values);
  const profileHref = (candidate: DiscoveryCandidate, compose = false) => `/recruiter/candidates/${candidate.id}?from=discover${compose ? "&compose=1" : ""}`;
  const candidateSummary = (candidate: DiscoveryCandidate) => <div className="min-w-0"><button type="button" onClick={() => setPreview(candidate)} className="min-h-11 break-words text-left font-semibold text-navy hover:text-indigo">{candidate.full_name}</button><p className="text-xs leading-5 text-ink-muted">{candidate.designation || candidate.headline || "Professional profile"}</p><p className="text-xs leading-5 text-ink-muted">{candidate.current_company || "Company not provided"}</p><div className="mt-2 flex flex-wrap gap-1">{(candidate.skills || []).slice(0, 5).map(skill => <span key={skill} className="swx-skill-chip rounded-full bg-mint/40 px-2 py-1 text-xs text-emerald-900">{skill}</span>)}</div></div>;
  const candidateActions = (candidate: DiscoveryCandidate) => <div className="flex flex-wrap items-center gap-1.5"><Link href={profileHref(candidate)} className="inline-flex min-h-11 items-center px-2 text-xs font-semibold text-indigo">View profile</Link><Link href={profileHref(candidate, true)} className="inline-flex min-h-11 items-center px-2 text-xs font-semibold text-indigo">Message</Link><details><summary role="button" className="flex min-h-11 cursor-pointer items-center px-2 text-xs font-semibold text-ink" aria-label={`More actions for ${candidate.full_name}`}>More</summary><div className="mt-1 rounded-lg border border-line bg-white p-2"><DiscoveryCandidateActions candidateID={candidate.id} /></div></details></div>;
  return <div className="grid min-w-0 gap-5 pb-40">
    <RecruiterProductHeader eyebrow="Talent workspace" title={resultsMode ? "Discover Talent Results" : "Discover Talent"} description="Find candidates using skills, experience, employment history, education and availability." actions={<><button type="button" onClick={clear} className={recruiterSecondary}>Clear search</button>{resultsMode && <button type="button" onClick={() => setResultsMode(false)} className={recruiterSecondary}>Edit search</button>}</>} />
    {notice && <p role="status" className="rounded-lg border border-line p-3 text-sm text-ink">{notice}</p>}
    <div className={`grid min-w-0 items-start gap-6 ${resultsMode ? "" : "xl:grid-cols-[minmax(0,3fr)_minmax(14rem,1fr)]"}`}><div className="min-w-0">
      {!resultsMode && <form onSubmit={event => { event.preventDefault(); void run(); }} noValidate className="swx-workspace-surface rounded-xl border border-line px-4 sm:px-6"><div className="border-b border-line py-5"><label className="block text-sm font-medium text-ink" htmlFor="discovery-client">Client you&apos;re hiring for</label><input id="discovery-client" value={companyName} readOnly className={`${recruiterInput} mt-2`} /><p className="mt-1.5 text-xs text-ink-muted">Your authorized company workspace. Client switching requires an assigned company relationship.</p></div><div className="border-b border-line py-5"><h2 className="text-base font-semibold text-navy">SapienWorx Intelligence</h2><p className="mt-2 text-sm leading-6 text-ink-muted">Structured criteria remain the source of truth. Prompt interpretation requires an enabled, approved Intelligence search capability.</p></div>{discoverySections.map(section => <SearchSection key={section.id} section={section} values={values} setValue={setValue} errors={errors} />)}<button type="submit" hidden>Search Talent</button></form>}
      <section aria-label="Candidate search results" className="mt-5 grid min-w-0 gap-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 ref={resultsHeading} tabIndex={-1} className="text-lg font-semibold text-navy outline-none">{results ? `${results.total} discoverable candidates` : "Candidate results"}</h2><p className="mt-1 text-xs text-ink-muted">Only profiles authorized for recruiter discovery appear here.</p></div><label className="grid gap-1 text-xs text-ink-muted">Sort results<select value={values.sort || "recently_updated"} onChange={event => { const next = { ...values, sort: event.target.value }; setValues(next); if (resultsMode) void run(next); }} className={recruiterInput}>{[["recently_updated", "Recently updated"], ["recently_active", "Recently active"], ["most_experienced", "Experience high to low"], ["least_experienced", "Experience low to high"], ["newest", "Newest profiles"], ["relevance", "Relevant skills"]].map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label></div>
        {chips.length > 0 && <div aria-label="Applied search criteria" className="flex flex-wrap gap-2">{chips.map(([key, value]) => <button key={key} type="button" onClick={() => { const next = { ...values, [key]: discoveryDefaults[key] || "" }; setValues(next); if (resultsMode) void run(next); }} aria-label={`Remove ${discoveryFieldMap[key]?.label || key} filter`} className="max-w-full break-words rounded-full border border-line px-3 py-2 text-xs text-ink">{discoveryFieldMap[key]?.label || key}: {value} ×</button>)}</div>}
        {busy ? <WorkspaceSkeleton /> : error ? <WorkspaceState error title="Search could not be completed" description={error} action={<><button className={recruiterSecondary} onClick={() => setResultsMode(false)}>Modify search</button><button className={recruiterPrimary} onClick={() => void run()}>Retry search</button></>} /> : results?.items.length ? <RecruiterDataTable rows={results.items} rowKey={candidate => candidate.id} label="Discover Talent candidates" columns={[
          { key: "candidate", title: "Candidate", width: "34%", render: candidateSummary }, { key: "experience", title: "Experience", width: "12%", render: candidate => experience(candidate.experience_months) },
          { key: "location", title: "Location / notice", width: "23%", render: candidate => <><p>{[candidate.current_city, candidate.current_state].filter(Boolean).join(", ") || "Not provided"}</p><p className="mt-1 text-xs text-ink-muted">{candidate.notice_period_days == null ? "Notice not provided" : candidate.notice_period_days === 0 ? "Immediate" : `${candidate.notice_period_days} days notice`}</p></> }, { key: "actions", title: "Actions", width: "31%", render: candidateActions },
        ]} mobileRow={candidate => <>{candidateSummary(candidate)}<p className="mt-3 text-xs text-ink-muted">{experience(candidate.experience_months)} · {candidate.current_city || "Location not provided"} · {candidate.notice_period_days == null ? "Notice not provided" : `${candidate.notice_period_days} days notice`}</p><div className="mt-3 border-t border-line pt-2">{candidateActions(candidate)}</div></>} /> : <WorkspaceState title={results ? "No candidates match these criteria" : "Build your talent search"} description={results ? "Relax experience, expand locations or remove a required skill. Save this search to configure an alert." : "Choose skills, locations or a role to start. Expand the sections for more precise criteria."} action={<button onClick={() => setResultsMode(false)} className={recruiterSecondary}>Modify search</button>} />}
        {results && !busy && !error && <nav aria-label="Discovery pagination" className="flex flex-wrap items-center justify-between gap-3 text-sm"><span className="text-ink-muted">{results.total ? (results.page - 1) * results.limit + 1 : 0}–{Math.min(results.page * results.limit, results.total)} of {results.total}</span><div className="flex items-center gap-2"><button disabled={results.page <= 1} className={recruiterSecondary} onClick={() => void run(applied, results.page - 1)}>Previous</button><span className="text-xs text-ink-muted">Page {results.page} of {Math.max(1, Math.ceil(results.total / results.limit))}</span><button disabled={results.page * results.limit >= results.total} className={recruiterSecondary} onClick={() => void run(applied, results.page + 1)}>Next</button></div></nav>}
      </section></div>
      {!resultsMode && <aside className="grid gap-6 xl:sticky xl:top-24">{[["Recent searches", recentItems], ["Saved searches", savedItems]].map(([title, list]) => <section key={title as string}><div className="flex items-center justify-between gap-2"><h2 className="text-base font-semibold text-navy">{title as string}</h2>{title === "Saved searches" && <Link href="/recruiter/saved-searches" className="min-h-11 content-center text-sm font-semibold text-indigo">View all</Link>}</div><div className="mt-3 divide-y divide-line">{(list as SearchRecord[]).length ? (list as SearchRecord[]).slice(0, 5).map(item => <div key={item.id} className="py-3">{item.name && <p className="text-sm font-semibold text-navy">{item.name}</p>}<p className="mt-1 line-clamp-3 text-xs leading-6 text-ink-muted">{discoverySummary(item.filters)}</p>{item.name && <p className="text-xs text-ink-muted">Alert {item.alert_enabled ? item.alert_frequency : "off"}</p>}<button className="min-h-11 text-sm font-semibold text-indigo" onClick={() => { setSearchID(item.name ? String(item.id) : ""); setName(item.name || ""); setFrequency(item.alert_enabled ? item.alert_frequency || "daily" : "off"); const next = { ...discoveryDefaults, ...cleanDiscovery(item.filters) }; setValues(next); void run(next); }}>{item.name ? "Run search" : "Run again"}</button></div>) : <p className="py-3 text-sm text-ink-muted">{title === "Recent searches" ? "No recent searches yet." : "Save a useful search to reuse it here."}</p>}</div></section>)}</aside>}
    </div>
    <div className="swx-workspace-surface swx-search-actions z-30 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-line px-3 py-3 shadow-sm"><span className="text-xs font-medium text-ink-muted">{activeDiscovery(values).length} filters configured</span><div className="flex flex-wrap gap-2"><button type="button" disabled={!ready} onClick={() => setSaveOpen(true)} className={recruiterSecondary}>{searchID ? "Update saved search" : "Save search"}</button><button type="button" disabled={!ready || busy} onClick={() => void run()} className={recruiterPrimary}>{busy ? "Searching…" : "Search Talent"}</button></div></div>
    <RecruiterDrawer open={saveOpen} onClose={() => { if (!saving) setSaveOpen(false); }} title="Save search"><form onSubmit={saveSearch} className="grid gap-4"><label className="grid gap-2 text-sm font-medium text-ink">Search name<input required maxLength={120} placeholder="e.g. Mumbai sales leaders" value={name} onChange={event => setName(event.target.value)} className={recruiterInput} /></label>{searchID && <button type="button" className={recruiterSecondary} onClick={() => { setSearchID(""); setName(current => (current + " copy").slice(0,120)); }}>Save as a separate search</button>}<p className="break-words text-sm leading-6 text-ink-muted">{discoverySummary(values)}</p><label className="grid gap-2 text-sm font-medium text-ink">Alert frequency<select value={frequency} onChange={event => setFrequency(event.target.value)} className={recruiterInput}><option value="off">Off</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><p className="text-xs leading-5 text-ink-muted">Alerts use existing email delivery settings; saving does not enable a new service.</p><button disabled={saving} className={recruiterPrimary}>{saving ? "Saving…" : searchID ? "Update this search" : "Save this search"}</button>{notice && <p role="status" className="text-sm text-ink-muted">{notice}</p>}</form></RecruiterDrawer>
    <RecruiterDrawer open={!!preview} onClose={() => setPreview(null)} title="Candidate preview" footer={preview && <><Link href={profileHref(preview, true)} className={recruiterSecondary}>Message</Link><Link href={profileHref(preview)} className={recruiterPrimary}>View Candidate 360</Link></>}>
      {preview && <div className="grid gap-5"><div><h3 className="text-xl font-semibold text-navy">{preview.full_name}</h3><p className="mt-1 text-sm text-ink-muted">{preview.designation || preview.headline}</p><p className="mt-1 text-xs text-ink-muted">Email {preview.email_verified ? "verified" : "verification not provided"}</p></div><dl className="grid grid-cols-2 gap-4 text-sm">{[["Company", preview.current_company], ["Experience", experience(preview.experience_months)], ["Location", [preview.current_city, preview.current_state].filter(Boolean).join(", ")], ["Preferred locations", preview.preferred_locations], ["Notice", preview.notice_period_days == null ? "" : `${preview.notice_period_days} days`], ["Education", preview.education], ["Last active", preview.last_active_at ? new Date(preview.last_active_at).toLocaleDateString() : ""], ["Profile updated", new Date(preview.updated_at).toLocaleDateString()]].map(([label, value]) => <div key={label}><dt className="text-xs text-ink-muted">{label}</dt><dd className="mt-1 break-words text-ink">{value || "Not provided"}</dd></div>)}</dl><section><h3 className="text-sm font-semibold text-navy">Top skills</h3><div className="mt-2 flex flex-wrap gap-2">{preview.skills.map(skill => <span key={skill} className="swx-skill-chip rounded-full bg-mint/40 px-3 py-1 text-xs text-emerald-900">{skill}</span>)}</div></section><section><h3 className="text-sm font-semibold text-navy">Match context</h3><p className="mt-2 text-sm leading-6 text-ink-muted">Select an authorized job in Candidate 360 to see its approved model match and explanation. Search relevance is separate from an AI match score.</p></section><DiscoveryCandidateActions candidateID={preview.id} /><p className="text-xs leading-5 text-ink-muted">Contact, private compensation and CV access remain protected by the candidate-sharing policy.</p></div>}
    </RecruiterDrawer>
  </div>;
}
