"use client";
import Link from "next/link";
import { RecruiterProductHeader } from "./recruiter-product-header";
import { RecruiterDataTable, WorkspaceState, recruiterPrimary, recruiterSecondary } from "./workspace-ui";
import { LocalTimeGreeting } from "@/components/ui/local-time-greeting";
import { label, type RecruiterDashboard, type RecruiterJob } from "@/lib/recruiter";

export function RecruiterHomeWorkspace({ data, jobs, jobsError, firstName }: { data: RecruiterDashboard; jobs: RecruiterJob[]; jobsError: boolean; firstName: string }) {
  const date = (value: string) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(value)) + " IST";
  const jobSummary = (job: RecruiterJob) => <div><Link className="font-semibold text-navy hover:text-indigo" href={`/recruiter/jobs/${job.id}/applicants`}>{job.title}</Link><p className="mt-1 text-xs text-ink-muted">{job.job_reference} · {[job.city, job.state].filter(Boolean).join(", ") || job.country_code}</p></div>;
  const jobActions = (job: RecruiterJob) => <Link className={recruiterSecondary} href={`/recruiter/jobs/${job.id}/applicants`}>View applicants</Link>;
  return <div className="grid min-w-0 gap-6">
    <RecruiterProductHeader eyebrow={data.company_name} title={<><LocalTimeGreeting firstName={firstName} />.</>} description="Your hiring priorities and the next steps that need your attention." actions={<Link className={recruiterPrimary} href="/recruiter/jobs/new">Post a job</Link>} />
    <section aria-labelledby="attention-heading"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 id="attention-heading" className="text-lg font-semibold text-navy">Needs attention</h2><Link className="min-h-11 content-center text-sm font-semibold text-indigo" href="/recruiter/pipeline">Review pipeline</Link></div>{data.needs_attention.length ? <ul className="swx-workspace-surface divide-y divide-line rounded-xl border border-line">{data.needs_attention.map(item => <li key={`${item.kind}-${item.title}`}><Link className="flex min-h-16 items-center justify-between gap-4 px-4 py-3 hover:bg-slate-50/50" href={item.href}><div><p className="text-sm font-semibold text-navy">{item.title}</p><p className="mt-1 text-xs leading-5 text-ink-muted">{item.detail}</p></div><span aria-hidden="true" className="text-indigo">→</span></Link></li>)}</ul> : <WorkspaceState title="Your priority queues are clear" description="No open application, message, offer or deadline queues need attention right now." />}</section>
    <section aria-label="Hiring overview" className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[
      ["Active jobs", data.active_jobs, "/recruiter/jobs?status=active"], ["New applications", data.new_applications, "/recruiter/pipeline?stage=new_application"], ["Upcoming interviews", data.upcoming_interviews, "/recruiter/interviews?status=upcoming"], ["Offers", data.offers, "/recruiter/offers"],
    ].map(([name,value,href]) => <Link key={name} aria-label={`View ${String(name).toLowerCase()}: ${value}`} href={String(href)} className="swx-workspace-surface rounded-xl border border-line px-4 py-4"><p className="text-xs text-ink-muted">{name}</p><p className="mt-2 text-2xl font-semibold text-navy">{value}</p></Link>)}</section>
    <section><div className="mb-3 flex items-center justify-between gap-2"><h2 className="text-lg font-semibold text-navy">Active jobs</h2><Link href="/recruiter/jobs?status=active" className="min-h-11 content-center text-sm font-semibold text-indigo">All active jobs</Link></div>{jobsError ? <WorkspaceState error title="Active jobs are unavailable" description="Try the job workspace to retry. No hiring data has changed." action={<Link href="/recruiter/jobs" className={recruiterSecondary}>Manage jobs</Link>} /> : jobs.length ? <RecruiterDataTable label="Active jobs" rows={jobs} rowKey={job=>job.id} columns={[{key:"job",title:"Job",width:"38%",render:jobSummary},{key:"applications",title:"Applications",width:"19%",render:job=><><p>{job.applications}</p><p className="mt-1 text-xs text-ink-muted">{job.new_applications} new</p></>},{key:"interviews",title:"Interviews",width:"16%",render:job=>job.interviews},{key:"actions",title:"Next action",width:"27%",render:jobActions}]} mobileRow={job=><>{jobSummary(job)}<p className="my-3 text-xs text-ink-muted">{job.applications} applications · {job.new_applications} new · {job.interviews} interviews</p>{jobActions(job)}</>} /> : <WorkspaceState title="No active jobs" description="Publish a role when your hiring requirements are ready." action={<Link className={recruiterPrimary} href="/recruiter/jobs/new">Post a job</Link>} />}</section>
    <section><div className="mb-3 flex items-center justify-between gap-2"><h2 className="text-lg font-semibold text-navy">Upcoming interviews</h2><Link href="/recruiter/interviews" className="min-h-11 content-center text-sm font-semibold text-indigo">All interviews</Link></div>{data.upcoming_items.length ? <RecruiterDataTable label="Upcoming interviews" rows={data.upcoming_items} rowKey={item=>item.id} columns={[{key:"candidate",title:"Candidate",width:"25%",render:item=>item.candidate_name},{key:"role",title:"Role",width:"28%",render:item=>item.job_title},{key:"schedule",title:"Schedule",width:"27%",render:item=><time dateTime={item.scheduled_at}>{date(item.scheduled_at)}</time>},{key:"action",title:"Action",width:"20%",render:item=><Link className={recruiterSecondary} href={`/recruiter/interviews?interview_id=${encodeURIComponent(item.id)}`}>Open interview</Link>}]} mobileRow={item=><div className="grid gap-2"><p className="font-semibold text-navy">{item.candidate_name}</p><p className="text-sm text-ink-muted">{item.job_title}</p><time className="text-sm text-ink" dateTime={item.scheduled_at}>{date(item.scheduled_at)}</time><Link className={recruiterSecondary} href={`/recruiter/interviews?interview_id=${encodeURIComponent(item.id)}`}>Open interview</Link></div>} /> : <WorkspaceState title="No upcoming interviews" description="Schedule an interview from an authorized application when the candidate and team are ready." />}</section>
    <section><div className="mb-3 flex items-center justify-between gap-2"><h2 className="text-lg font-semibold text-navy">Recent applications</h2><Link className="min-h-11 content-center text-sm font-semibold text-indigo" href="/recruiter/pipeline">Full pipeline</Link></div><RecruiterDataTable label="Recent applications" rows={data.recent_applications.slice(0,6)} rowKey={row=>row.application_id} columns={[{key:"candidate",title:"Candidate",width:"28%",render:row=>row.candidate_name},{key:"job",title:"Job",width:"34%",render:row=>row.job_title},{key:"stage",title:"Stage",width:"18%",render:row=>label(row.stage)},{key:"action",title:"Action",width:"20%",render:row=><Link className={recruiterSecondary} href={`/recruiter/candidates/${row.candidate_id}?job_id=${row.job_id}`}>View profile</Link>}]} mobileRow={row=><div className="grid gap-2"><p className="font-semibold text-navy">{row.candidate_name}</p><p className="text-sm text-ink-muted">{row.job_title} · {label(row.stage)}</p><Link className={recruiterSecondary} href={`/recruiter/candidates/${row.candidate_id}?job_id=${row.job_id}`}>View profile</Link></div>} /></section>
  </div>;
}
