"use client";
import Link from "next/link";
import { useEffect, useId, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api";
import type { Interview, InterviewChangeEvent } from "@/lib/recruiter";
import { feedbackLabel } from "@/lib/interview-workspace";
import { RecruiterDrawer, recruiterInput, recruiterPrimary, recruiterSecondary } from "./workspace-ui";
import { InterviewActions } from "./interview-actions";

type Feedback = { user_id: string; name: string; rating: number; recommendation: string; notes: string; submitted_at: string };
export function InterviewDetailDrawer({ interview, onClose, userID, now }: { interview: Interview | null; onClose: () => void; userID: string; now: number }) {
  const router = useRouter(), formID = useId();
  const interviewID = interview?.id;
  const [feedback, setFeedback] = useState<Feedback[]>([]), [history, setHistory] = useState<InterviewChangeEvent[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(false), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false);
  useEffect(() => { if (!interviewID) return; let active = true; setLoading(true); setLoaded(false); setError(""); setFeedback([]); setHistory([]);
    Promise.all([apiRequest<{items:Feedback[]}>(`/api/v1/recruiter/interviews/${interviewID}/feedback`), apiRequest<{items:InterviewChangeEvent[]}>(`/api/v1/recruiter/interviews/${interviewID}/history`)]).then(([scores, changes]) => { if(active) { setFeedback(scores.items); setHistory(changes.items); setLoaded(true); } }).catch(cause=>{if(active)setError(cause instanceof Error ? cause.message : "Interview details are unavailable.");}).finally(()=>{if(active)setLoading(false);});
    return()=>{active=false;};
  }, [interviewID]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(!interview || busy)return;const data=new FormData(event.currentTarget);setBusy(true);setError("");try { await apiRequest(`/api/v1/recruiter/interviews/${interview.id}/feedback`, {method:"PUT", body:JSON.stringify({rating:Number(data.get("rating")), recommendation:data.get("recommendation"), notes:data.get("notes")})});const scores=await apiRequest<{items:Feedback[]}>(`/api/v1/recruiter/interviews/${interview.id}/feedback`);setFeedback(scores.items);router.refresh(); } catch(cause){setError(cause instanceof Error ? cause.message : "Could not save feedback.");}finally{setBusy(false);} }
  async function respond(response: string) { if(!interview || busy)return;setBusy(true);setError("");try{await apiRequest(`/api/v1/recruiter/interviews/${interview.id}/response`,{method:"PUT",body:JSON.stringify({response})});router.refresh();}catch(cause){setError(cause instanceof Error ? cause.message : "Could not update your response.");}finally{setBusy(false);} }
  const own = feedback.find(item=>item.user_id===userID), panelMember=interview?.interviewers?.find(item=>item.user_id===userID);
  const canSubmit=interview && panelMember && panelMember.response!=="declined" && !["cancelled","no_show"].includes(interview.status) && (interview.status==="completed" || Date.parse(interview.scheduled_at)+interview.duration_minutes*60000<=now);
  return <RecruiterDrawer wide open={Boolean(interview)} onClose={onClose} title={interview ? `Interview details · ${interview.candidate_name}` : "Interview details"}>{interview && <div className="grid gap-5">
    <div><h3 className="swx-type-section-title text-navy">{interview.candidate_name}</h3><p className="mt-1 text-sm text-ink-muted">{interview.job_title} · {interview.round_label}</p><p className="mt-2 text-sm text-ink">{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:interview.timezone || "Asia/Kolkata"}).format(new Date(interview.scheduled_at))} · {interview.duration_minutes} min · {interview.timezone || "Asia/Kolkata"}</p><p className="mt-1 text-sm text-ink-muted">{interview.format?.replaceAll("_"," ") || "Video"}{interview.location && ` · ${interview.location}`}</p></div>
    <InterviewActions interview={interview}/><div className="flex flex-wrap gap-2"><Link className={recruiterSecondary} href={`/recruiter/candidates/${interview.candidate_id}?job_id=${interview.job_id}`}>View candidate</Link><Link className={recruiterSecondary} href={`/recruiter/messages?candidate_id=${interview.candidate_id}&job_id=${interview.job_id}`}>Message candidate</Link></div>
    <section><h3 className="swx-type-section-title text-navy">Interviewers</h3><ul className="mt-2 divide-y divide-line">{interview.interviewers?.map(person=><li key={person.user_id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{person.name}</span><span className="capitalize text-ink-muted">{person.response} · {person.feedback_submitted ? "Feedback submitted" : "Feedback pending"}</span></li>)}</ul>{panelMember && interview.status==="scheduled" && <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || panelMember.response==="accepted"} onClick={()=>void respond("accepted")} className={recruiterSecondary}>Accept invitation</button><button disabled={busy || panelMember.response==="declined"} onClick={()=>void respond("declined")} className={recruiterSecondary}>Decline invitation</button></div>}</section>
    {interview.notes && <section><h3 className="swx-type-section-title text-navy">Internal notes</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{interview.notes}</p></section>}
    <section aria-label="Interview feedback"><h3 className="swx-type-section-title text-navy">Structured feedback</h3><p className="mt-1 text-sm text-ink-muted">{feedbackLabel(interview, now)}</p>{loading && <p role="status" className="mt-2 text-sm">Loading feedback and history…</p>}{error && <p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}
      {feedback.map(score=><article key={score.user_id} className="mt-3 rounded-lg border border-line p-3"><h4 className="font-semibold">{score.name} · {score.rating}/5 · {score.recommendation.replaceAll("_"," ")}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{score.notes}</p></article>)}
      {canSubmit && !loading && loaded && <form id={formID} onSubmit={submit} className="mt-4 grid gap-3" key={`${interview.id}-${own?.submitted_at || "new"}`}><label className="grid gap-1 swx-type-label">Overall rating<select aria-label="Overall rating" name="rating" defaultValue={own?.rating || 3} className={recruiterInput}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><label className="grid gap-1 swx-type-label">Recommendation<select aria-label="Recommendation" name="recommendation" defaultValue={own?.recommendation || "hold"} className={recruiterInput}><option value="advance">Advance</option><option value="hold">Hold</option><option value="do_not_advance">Do not advance</option></select></label><label className="grid gap-1 swx-type-label">Evidence and feedback<textarea name="notes" defaultValue={own?.notes || ""} required maxLength={4000} rows={4} className={recruiterInput}/></label><button disabled={busy} className={`${recruiterPrimary} justify-self-start`}>{busy ? "Saving…" : own ? "Update my feedback" : "Submit feedback"}</button></form>}
    </section>
    <section aria-label="Interview history"><h3 className="swx-type-section-title text-navy">Change history</h3>{history.length ? <ol className="mt-2 grid gap-2">{history.map((event,index)=><li key={index} className="text-sm"><span className="capitalize">{event.action}</span> by {event.actor_name} · {new Date(event.changed_at).toLocaleString("en-IN",{timeZone:interview.timezone || "Asia/Kolkata"})}</li>)}</ol> : <p className="mt-2 text-sm text-ink-muted">No changes have been recorded for this interview.</p>}</section>
  </div>}</RecruiterDrawer>;
}
