"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { Interview, PipelineRow, RecruiterTeamMember } from "@/lib/recruiter";
import { feedbackDue, feedbackLabel, interviewConflicts, interviewDay, interviewWeek, interviewZones, shiftInterviewDay } from "@/lib/interview-workspace";
import { RecruiterProductHeader } from "./recruiter-product-header";
import { ScheduleInterviewForm } from "./schedule-interview-form";
import { InterviewCandidateCard } from "./applicant-card-workspace";
import { InterviewActions } from "./interview-actions";
import { InterviewDetailDrawer } from "./interview-detail-drawer";
import { StatusPill } from "./status-menu";
import { WorkspaceState, recruiterInput, recruiterSecondary } from "./workspace-ui";

const statuses=[ ["upcoming","Upcoming"], ["feedback_due","Feedback due"], ["completed","Completed"], ["cancelled","Cancelled"], ["all","All"] ];
export function InterviewsWorkspace({items,applications,team,userID,initialNow}:{items:Interview[];applications:PipelineRow[];team:RecruiterTeamMember[];userID:string;initialNow:number}) {
  const params=useSearchParams(), path=usePathname(), router=useRouter();
  const [mobile,setMobile]=useState(false), [selected,setSelected]=useState<Interview|null>(null), [now,setNow]=useState(initialNow);
  useEffect(()=>{const query=matchMedia("(max-width: 767px)");const sync=()=>setMobile(query.matches);sync();query.addEventListener("change",sync);const timer=setInterval(()=>setNow(Date.now()),60000);return()=>{query.removeEventListener("change",sync);clearInterval(timer);};},[]);
  useEffect(()=>{if(params.get("interview_id"))setSelected(items.find(item=>item.id===params.get("interview_id")) || null);},[params,items]);
  const zone=interviewZones.includes(params.get("timezone") || "") ? params.get("timezone")! : "Asia/Kolkata", today=interviewDay(new Date(now).toISOString(),zone);
  const calendar=params.get("view")==="calendar", mode=params.get("mode") || (mobile ? "day" : "week"), status=params.get("status") || "upcoming";
  const dateParam=params.get("date"), date=dateParam && /^\d{4}-\d{2}-\d{2}$/.test(dateParam) && !Number.isNaN(Date.parse(`${dateParam}T00:00:00Z`)) ? dateParam : today;
  const conflictIDs=useMemo(()=>interviewConflicts(items),[items]);
  const matchesStatus=(item:Interview,value:string)=>value==="all" || value==="upcoming" && item.status==="scheduled" && Date.parse(item.scheduled_at)+item.duration_minutes*60000>now || value==="feedback_due" && feedbackDue(item,now) || item.status===value;
  const counts=Object.fromEntries(statuses.map(([value])=>[value,items.filter(item=>matchesStatus(item,value)).length]));
  const q=(params.get("q") || "").toLowerCase(), from=params.get("from") || "", to=params.get("to") || "", stage=params.get("stage") || "", interviewer=params.get("interviewer") || "";
  const visible=items.filter(item=>matchesStatus(item,status) && (!q || `${item.candidate_name} ${item.job_title} ${item.round_label} ${item.job_reference} ${item.interviewers?.map(person=>person.name).join(" ")}`.toLowerCase().includes(q)) && (!from || interviewDay(item.scheduled_at,zone)>=from) && (!to || interviewDay(item.scheduled_at,zone)<=to) && (!stage || item.round_label===stage) && (!interviewer || item.interviewers?.some(person=>person.user_id===interviewer)) && (params.get("conflicts")!=="1" || conflictIDs.has(item.id)));
  function href(updates:Record<string,string>) {const next=new URLSearchParams(params);next.delete("interview_id");for(const [key,value]of Object.entries(updates)){if(value)next.set(key,value);else next.delete(key);}return `${path}${next.size ? `?${next}` : ""}`;}
  function filter(form:HTMLFormElement) {const data=new FormData(form);router.replace(href(Object.fromEntries(Array.from(data).map(([key,value])=>[key,String(value)]))),{scroll:false});}
  const clock=(item:Interview)=>new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit",timeZone:zone}).format(new Date(item.scheduled_at));
  const schedule=(item:Interview)=><button className="min-h-11 text-left text-sm text-ink hover:text-indigo" onClick={()=>setSelected(item)}><span className="block font-semibold">{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeZone:zone}).format(new Date(item.scheduled_at))}</span><span className="block swx-type-caption">{clock(item)} · {item.duration_minutes} min</span></button>;
  const panel=(item:Interview)=><div className="text-sm" title={item.interviewers?.map(person=>`${person.name} — ${person.response}`).join("\n")}>{item.interviewers?.length ? <><span>{item.interviewers[0].name}{item.interviewers.length>1 && ` +${item.interviewers.length-1}`}</span><span className="mt-1 block swx-type-caption text-ink-muted">{item.interviewers.filter(p=>p.response==="accepted").length}/{item.interviewers.length} accepted</span></> : <span className="text-ink-muted">Not assigned</span>}</div>;
  const feedback=(item:Interview)=><button className={`min-h-11 text-left swx-type-caption ${feedbackDue(item,now) ? "font-semibold text-amber-800" : "text-ink-muted"}`} onClick={()=>setSelected(item)}>{feedbackLabel(item,now)}</button>;
  const start=mode==="week" ? interviewWeek(date) : date, days=Array.from({length:mode==="week"?7:1},(_,i)=>shiftInterviewDay(start,i));
  const emptyTitles:Record<string,string>={upcoming:"No upcoming interviews",feedback_due:"No feedback due",completed:"No completed interviews yet",cancelled:"No cancelled interviews",all:"No interviews scheduled"};
  return <div className="grid min-w-0 gap-4">
    <RecruiterProductHeader eyebrow="Interview operations" title="Interviews" description="Schedule interviews, coordinate interviewers and track candidate feedback." actions={<ScheduleInterviewForm applications={applications} team={team}/>}/>
    <nav aria-label="Interview summary" className="flex flex-wrap gap-x-5 gap-y-1 text-sm">{[[`Today ${items.filter(item=>item.status!=="cancelled"&&interviewDay(item.scheduled_at,zone)===today).length}`,{from:today,to:today,status:"all"}],[`This week ${items.filter(item=>item.status!=="cancelled"&&interviewDay(item.scheduled_at,zone)>=interviewWeek(today)&&interviewDay(item.scheduled_at,zone)<=shiftInterviewDay(interviewWeek(today),6)).length}`,{from:interviewWeek(today),to:shiftInterviewDay(interviewWeek(today),6),status:"all"}],[`Feedback due ${counts.feedback_due}`,{status:"feedback_due",from:"",to:""}],[`Conflicts ${conflictIDs.size}`,{conflicts:"1",status:"all"}]].map(([label,updates])=><Link key={String(label)} href={href(updates as Record<string,string>)} className="min-h-11 content-center font-semibold text-ink hover:text-indigo">{String(label)}</Link>)}</nav>
    <div className="flex flex-wrap items-center gap-3"><nav aria-label="Interview views" className="inline-flex rounded-lg border border-line bg-white p-1">{[["list","List view","M4 6h16M4 12h16M4 18h16"],["calendar","Calendar view","M4 5h16v16H4ZM8 3v4m8-4v4M4 10h16"]].map(([value,label,shape])=><Link key={value} href={href({view:value})} aria-current={(calendar?"calendar":"list")===value?"page":undefined} className={`flex min-h-11 items-center gap-2 rounded-md px-3 text-sm font-semibold ${(calendar?"calendar":"list")===value?"bg-indigo text-white":"text-ink-muted"}`}><svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4 fill-none stroke-current stroke-[1.8]"><path d={shape}/></svg>{label}</Link>)}</nav><label className="ml-auto flex flex-wrap items-center gap-2 swx-type-label">Timezone<select aria-label="Timezone" value={zone} onChange={event=>router.replace(href({timezone:event.target.value}),{scroll:false})} className={`${recruiterInput} !w-auto`}>{interviewZones.map(zone=><option key={zone}>{zone}</option>)}</select></label></div>
    <nav aria-label="Interview status views" className="flex min-w-0 gap-1 overflow-x-auto border-b border-line">{statuses.map(([value,label])=><Link key={value} href={href({status:value,conflicts:""})} aria-current={status===value?"page":undefined} className={`flex min-h-11 shrink-0 items-center gap-2 border-b-2 px-3 text-sm font-semibold ${status===value?"border-indigo text-indigo":"border-transparent text-ink-muted"}`}>{label}<span className="swx-type-caption">{counts[value]}</span></Link>)}</nav>
    <form aria-label="Interview filters" onChange={event=>filter(event.currentTarget)} onSubmit={event=>{event.preventDefault();filter(event.currentTarget);}} className="flex min-w-0 flex-wrap items-end gap-2"><label className="grid min-w-0 flex-[2_1_14rem] gap-1 swx-type-label">Search interviews<input className={recruiterInput} name="q" defaultValue={q} key={q} placeholder="Candidate, job or interviewer" onChange={event=>event.stopPropagation()} onBlur={event=>filter(event.currentTarget.form!)}/></label><details className="relative"><summary className={`${recruiterSecondary} cursor-pointer list-none`}>Date range{from||to?" · Set":""}</summary><div className="swx-workspace-surface absolute left-0 top-full z-10 mt-2 grid w-60 gap-3 rounded-xl border border-line p-3 shadow-sm"><label className="grid gap-1 swx-type-label">From<input className={recruiterInput} type="date" name="from" defaultValue={from}/></label><label className="grid gap-1 swx-type-label">To<input className={recruiterInput} type="date" name="to" min={from||undefined} defaultValue={to}/></label></div></details><label className="grid flex-[1_1_9rem] gap-1 swx-type-label">Stage<select aria-label="Stage" name="stage" value={stage} onChange={()=>{}} className={recruiterInput}><option value="">All stages</option>{Array.from(new Set(items.map(i=>i.round_label))).sort().map(round=><option key={round}>{round}</option>)}</select></label><label className="grid flex-[1_1_10rem] gap-1 swx-type-label">Interviewer<select aria-label="Interviewer" name="interviewer" value={interviewer} onChange={()=>{}} className={recruiterInput}><option value="">All interviewers</option>{team.map(person=><option key={person.user_id} value={person.user_id}>{person.full_name}</option>)}</select></label>{(q||from||to||stage||interviewer||params.get("conflicts"))&&<Link className={recruiterSecondary} href={href({q:"",from:"",to:"",stage:"",interviewer:"",conflicts:""})}>Clear filters</Link>}</form>
    {calendar ? <section aria-label="Interview calendar" className="grid gap-3"><div className="flex flex-wrap items-center gap-3"><nav aria-label="Calendar period" className="inline-flex rounded-lg border border-line bg-white p-1">{["day","week"].map(value=><Link key={value} href={href({mode:value})} aria-current={mode===value?"page":undefined} className={`min-h-11 content-center rounded-md px-3 text-sm font-semibold capitalize ${mode===value?"bg-indigo text-white":"text-ink-muted"}`}>{value[0].toUpperCase()+value.slice(1)}</Link>)}</nav><div className="flex gap-1"><Link className={recruiterSecondary} aria-label={`Previous ${mode}`} href={href({date:shiftInterviewDay(date,mode==="week"?-7:-1)})}>←</Link><Link className={recruiterSecondary} href={href({date:today})}>Today</Link><Link className={recruiterSecondary} aria-label={`Next ${mode}`} href={href({date:shiftInterviewDay(date,mode==="week"?7:1)})}>→</Link></div><p className="text-sm font-semibold">{start}{mode==="week"&&` – ${days[6]}`}</p></div><div className={`grid min-w-0 gap-3 ${mode==="week"?"md:grid-cols-2 2xl:grid-cols-7":"max-w-3xl"}`}>{days.map(day=><section key={day} className="swx-workspace-surface min-w-0 rounded-xl border border-line p-3"><h2 className="text-sm font-semibold">{new Intl.DateTimeFormat("en-IN",{dateStyle:"full",timeZone:"UTC"}).format(new Date(`${day}T00:00:00Z`))}</h2><div className="mt-3 grid gap-3">{visible.filter(i=>interviewDay(i.scheduled_at,zone)===day).map(item=><article key={item.id} className="rounded-lg border border-line p-3"><button className="min-h-11 w-full text-left text-sm" onClick={()=>setSelected(item)}><time className="font-semibold text-indigo">{clock(item)}</time><span className="mt-1 block font-semibold text-navy">{item.candidate_name}</span><span className="mt-1 block text-ink-muted">{item.job_title}</span><span className="mt-1 block swx-type-caption">{item.round_label} · {item.duration_minutes} min · {item.format?.replaceAll("_"," ")||"Video"}</span></button><div className="mt-2">{panel(item)}</div>{item.status==="scheduled"&&item.meeting_url&&<a className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-indigo" href={item.meeting_url} target="_blank" rel="noopener noreferrer">Join meeting ↗</a>}{feedback(item)}</article>)}{!visible.some(i=>interviewDay(i.scheduled_at,zone)===day)&&<p className="text-sm text-ink-muted">No interviews in this view.</p>}</div></section>)}</div></section> : visible.length ? <>
      <div className="grid gap-3 xl:hidden" aria-label="Interview cards">{visible.map(item=><article key={item.id} className="swx-workspace-surface rounded-xl border border-line p-4"><div className="flex flex-wrap justify-between gap-2"><InterviewCandidateCard interview={item}/><StatusPill value={item.status}/></div><p className="mt-3 text-sm font-semibold">{item.job_title}</p><p className="mt-1 text-sm text-ink-muted">{item.round_label} · {item.format?.replaceAll("_"," ")||"Video"}</p><div className="mt-3 grid grid-cols-2 gap-3">{schedule(item)}{panel(item)}</div>{feedback(item)}<InterviewActions interview={item}/></article>)}</div>
      <div className="swx-workspace-surface hidden overflow-x-auto rounded-xl border border-line xl:block"><table aria-label="Interviews" className="w-full text-left text-sm"><thead className="border-b border-line bg-slate-50/60"><tr>{["Candidate","Job & stage","Date & time","Interviewers","Format","Status","Feedback","Action"].map(name=><th key={name} scope="col" className="px-3 py-3">{name}</th>)}</tr></thead><tbody>{visible.map(item=><tr key={item.id} className="border-b border-line align-top last:border-0"><td className="px-3 py-4"><InterviewCandidateCard interview={item}/></td><td className="px-3 py-4"><p className="font-semibold">{item.job_title}</p><p className="mt-1 swx-type-caption text-ink-muted">{item.round_label}</p></td><td className="px-3 py-4">{schedule(item)}</td><td className="px-3 py-4">{panel(item)}</td><td className="px-3 py-4 capitalize">{item.format?.replaceAll("_"," ")||"Video"}</td><td className="px-3 py-4"><StatusPill value={item.status}/></td><td className="px-3 py-4">{feedback(item)}</td><td className="px-3 py-4"><InterviewActions interview={item}/></td></tr>)}</tbody></table></div>
    </> : <WorkspaceState title={q||from||to||stage||interviewer?"No matching interviews":emptyTitles[status]||"No interviews in this view"} description={status==="cancelled"?"There are no cancelled interviews for this period.":status==="completed"?"Completed interviews will appear here with their feedback status.":status==="feedback_due"?"Feedback is up to date for this view.":"You don’t have interviews scheduled in this view. Choose an application when your candidate and team are ready."} action={status!=="upcoming"?<Link className={recruiterSecondary} href={href({status:"upcoming",q:"",from:"",to:"",stage:"",interviewer:"",conflicts:""})}>View upcoming</Link>:<ScheduleInterviewForm applications={applications} team={team}/>}/>}
    <InterviewDetailDrawer interview={selected && items.find(item=>item.id===selected.id) || null} onClose={()=>{setSelected(null);if(params.get("interview_id"))router.replace(href({}),{scroll:false});}} userID={userID} now={now}/>
  </div>;
}
