"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api";
import { RecruiterProductHeader } from "./recruiter-product-header";
import { RecruiterDrawer,recruiterInput,recruiterSecondary,WorkspaceState } from "./workspace-ui";
import {notificationCategories,notificationsChanged,type RecruiterNotificationInbox} from "@/lib/recruiter-notifications";

export function NotificationsWorkspace({initial}:{initial:RecruiterNotificationInbox}){
 const[inbox,setInbox]=useState(initial),[category,setCategory]=useState(""),[unread,setUnread]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[settings,setSettings]=useState(false),[muted,setMuted]=useState<string[]>([]),[settingsReady,setSettingsReady]=useState(false);
 const router=useRouter();
 async function load(nextCategory=category,nextUnread=unread,page=1){return apiRequest<RecruiterNotificationInbox>(`/api/v1/recruiter/notifications?category=${nextCategory}&unread=${nextUnread?1:0}&page=${page}`);}
 async function action(task:()=>Promise<void>){setBusy(true);setError("");try{await task();notificationsChanged();}catch(err){setError(err instanceof Error?err.message:"Could not update notifications.");}finally{setBusy(false);}}
 function filter(nextCategory:string,nextUnread:boolean){const previousCategory=category,previousUnread=unread;setCategory(nextCategory);setUnread(nextUnread);void action(async()=>{try{setInbox(await load(nextCategory,nextUnread));}catch(err){setCategory(previousCategory);setUnread(previousUnread);throw err;}});}
 function change(id:string,type:string){void action(async()=>{await apiRequest(`/api/v1/recruiter/notifications/${id}`,{method:"PATCH",body:JSON.stringify({action:type})});setInbox(await load());});}
 function open(id:string){void action(async()=>{const {href}=await apiRequest<{href:string}>(`/api/v1/recruiter/notifications/${id}/open`,{method:"POST"});if(!href.startsWith("/recruiter/")||href.includes("\\"))throw new Error("This notification has an invalid destination.");router.push(href);});}
 function openSettings(){setSettings(true);setSettingsReady(false);void action(async()=>{const result=await apiRequest<{muted_categories:string[]}>("/api/v1/recruiter/notification-preferences");setMuted(result.muted_categories);setSettingsReady(true);});}
 return <section className="space-y-5">
  <RecruiterProductHeader title="Notifications" eyebrow="Recruit workspace" description="Updates that need your attention, with a direct path to the next action." actions={<><button type="button" disabled={busy||!inbox.unread} className={recruiterSecondary} onClick={()=>change("all","read_all")}>Mark all as read</button><button type="button" onClick={openSettings} className={recruiterSecondary}>Notification settings</button></>}/>
  <div className="flex flex-wrap items-end gap-3"><label className="min-w-48 flex-1 text-sm font-medium">Category<select aria-label="Notification category" className={`${recruiterInput} mt-1`} disabled={busy} value={category} onChange={event=>filter(event.target.value,unread)}><option value="">All updates</option>{notificationCategories.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="flex min-h-11 cursor-pointer items-center gap-2 rounded-lg border border-line bg-white px-3 text-sm"><input type="checkbox" checked={unread} disabled={busy} onChange={event=>filter(category,event.target.checked)}/>Unread only</label><p role="status" className="py-3 text-sm text-ink-muted">{inbox.unread} unread · {inbox.total} updates</p></div>
  {error&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
  {inbox.items.length===0?<WorkspaceState title={unread?"You’re all caught up":"No notifications yet"} description={category?"There are no updates in this category. Your other workflows remain available from navigation.":"Applications, interview updates and messages will appear here when they arrive."}/>:<ol aria-label="Notification updates" className="divide-y divide-line rounded-xl border border-line bg-white">{inbox.items.map(item=><li key={item.id} className={`flex min-w-0 gap-3 p-4 sm:p-5 ${!item.read?"bg-indigo-soft/30":""}`}>
   <span aria-label={item.read?"Read":"Unread"} className={`mt-2 h-2.5 w-2.5 shrink-0 rounded-full ${item.read?"bg-slate-200":"bg-indigo"}`}/>
   <div className="min-w-0 flex-1"><span className="text-[13px] font-medium text-ink-muted">{notificationCategories.find(([key])=>key===item.category)?.[1]??"Update"}</span><button disabled={busy} onClick={()=>open(item.id)} className="mt-1 block min-h-11 w-full rounded-md text-left text-base font-semibold text-navy focus-visible:ring-2 focus-visible:ring-indigo">{item.title}</button><p className="mt-1 text-sm leading-6 text-ink-muted">{item.message}</p><time dateTime={item.created_at} className="mt-2 block text-[13px] text-ink-muted">{new Date(item.created_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"})} IST</time><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} className={recruiterSecondary} onClick={()=>open(item.id)}>{item.category==="interviews"?"View interview":item.category==="messages"?"Open conversation":item.category==="applications"?"Review application":"View update"}</button><details className="relative"><summary aria-label={`More actions for ${item.title}`} className={`${recruiterSecondary} cursor-pointer`}>More</summary><div className="absolute right-0 z-10 mt-1 grid min-w-40 rounded-lg border border-line bg-white p-2 shadow-lg"><button disabled={busy} className="min-h-11 rounded-lg px-3 text-left text-sm font-medium text-indigo focus-visible:ring-2 focus-visible:ring-indigo" onClick={()=>change(item.id,item.read?"unread":"read")}>{item.read?"Mark unread":"Mark read"}</button><button disabled={busy} className="min-h-11 rounded-lg px-3 text-left text-sm text-ink-muted focus-visible:ring-2 focus-visible:ring-indigo" aria-label={`Dismiss ${item.title}`} onClick={()=>change(item.id,"dismiss")}>Dismiss</button></div></details></div></div>
  </li>)}</ol>}
  {inbox.total>inbox.limit&&<nav aria-label="Notification pages" className="flex items-center justify-between gap-3"><button disabled={busy||inbox.page<=1} className={recruiterSecondary} onClick={()=>void action(async()=>setInbox(await load(category,unread,inbox.page-1)))}>Previous</button><span className="text-sm">Page {inbox.page} of {Math.ceil(inbox.total/inbox.limit)}</span><button disabled={busy||inbox.page*inbox.limit>=inbox.total} className={recruiterSecondary} onClick={()=>void action(async()=>setInbox(await load(category,unread,inbox.page+1)))}>Next</button></nav>}
  <RecruiterDrawer open={settings} onClose={()=>setSettings(false)} title="Notification settings" footer={<button disabled={busy||!settingsReady} className={recruiterSecondary} onClick={()=>void action(async()=>{await apiRequest("/api/v1/recruiter/notification-preferences",{method:"PUT",body:JSON.stringify({muted_categories:muted})});setInbox(await load());setSettings(false);})}>Save preferences</button>}><p className="text-sm leading-6 text-ink-muted">Choose which in-app updates appear in your centre. Muting a category does not change the underlying workflow or send messages externally.</p>{error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}{!settingsReady?<p className="mt-4" role="status">Loading preferences…</p>:<div className="mt-5 space-y-2">{notificationCategories.map(([key,label])=><label key={key} className="flex min-h-11 items-center gap-3 rounded-lg border border-line px-3 text-sm"><input type="checkbox" checked={!muted.includes(key)} onChange={event=>setMuted(current=>event.target.checked?current.filter(item=>item!==key):[...current,key])}/>{label}</label>)}</div>}</RecruiterDrawer>
 </section>;
}
