"use client";
import Link from "next/link";
import {useId,useState,useEffect,type FormEvent} from "react";
import {apiRequest} from "@/lib/api";
import {RecruiterDrawer,RecruiterDataTable,WorkspaceState,recruiterInput,recruiterPrimary,recruiterSecondary} from "./workspace-ui";
import {label,compactDate} from "@/lib/recruiter";
export type ReferralInvitation={id:string;candidate_name:string;candidate_id?:string;job_id?:string;job_title?:string;referrer_name:string;source:string;relationship?:string;note?:string;status:string;hiring_stage?:string;reward_status:string;expires_at:string;created_at:string;updated_at:string;application_id?:string;can_view_candidate:boolean};
export function ReferralInvitationsWorkspace({initialItems}:{initialItems:ReferralInvitation[]}){
 const rewardForm=useId();const[items,setItems]=useState(initialItems),[detail,setDetail]=useState<ReferralInvitation|null>(null),[reward,setReward]=useState<ReferralInvitation|null>(null),[view,setView]=useState("referrals"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[events,setEvents]=useState<{action:string;created_at:string}[]>([]),[link,setLink]=useState("");
 useEffect(()=>{const id=new URLSearchParams(location.search).get("referral_id");const item=initialItems.find(x=>x.id===id);if(item)void show(item);},[initialItems]);
 async function refresh(){const r=await apiRequest<{items:ReferralInvitation[]}>("/api/v1/recruiter/referral-invitations");setItems(r.items)}
 async function action(x:ReferralInvitation,action:string){if(busy)return;setBusy(true);setMessage("");try{const r=await apiRequest<{link?:string}>(`/api/v1/recruiter/referral-invitations/${x.id}/actions`,{method:"POST",body:JSON.stringify({action})});if(action==="copy_link"&&r?.link){setLink(r.link);try{await navigator.clipboard.writeText(r.link);setMessage("Invitation link copied. Only the invited verified email can claim it.")}catch{setMessage("Copy the invitation link below.")}}else{setDetail(null);setMessage(action==="resend"?"New invitation queued. The previous link is invalid.":"Invitation cancelled.");await refresh()}}catch(c){setMessage(c instanceof Error?c.message:"Could not update invitation.")}finally{setBusy(false)}}
 async function show(x:ReferralInvitation){setDetail(x);setLink("");setEvents([]);setMessage("");try{const r=await apiRequest<{items:{action:string;created_at:string}[]}>(`/api/v1/recruiter/referral-invitations/${x.id}/events`);setEvents(r.items)}catch{setMessage("Could not load invitation activity.")}}
 async function review(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!reward||busy)return;setBusy(true);const f=new FormData(e.currentTarget);try{await apiRequest(`/api/v1/recruiter/referral-invitations/${reward.id}/actions`,{method:"POST",body:JSON.stringify({action:"reward",reward_status:f.get("reward_status"),review_note:f.get("review_note"),eligibility_reviewed:f.get("eligibility_reviewed")==="on"})});setReward(null);await refresh();setMessage("Reward processing status recorded. No payment was made.")}catch(c){setMessage(c instanceof Error?c.message:"Could not record review.")}finally{setBusy(false)}}
 const referralLabel=(x:ReferralInvitation)=>x.application_id||["accepted","application_submitted"].includes(x.status)?"Accepted":["declined","cancelled","expired"].includes(x.status)?label(x.status):"Invited";
 const actions=(x:ReferralInvitation)=><div className="flex flex-wrap gap-2">{x.can_view_candidate&&x.candidate_id?<Link href={`/recruiter/candidates/${x.candidate_id}${x.job_id?`?job_id=${x.job_id}`:""}`} className={recruiterSecondary}>View candidate</Link>:<button className={recruiterSecondary} onClick={()=>void show(x)}>View invitation</button>}<button className={recruiterSecondary} aria-label={`More referral actions for ${x.candidate_name}`} onClick={()=>void show(x)}>⋯</button></div>;
 return <div className="grid min-w-0 gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><nav aria-label="Referral views" className="flex gap-2">{[["referrals","Referrals"],["rewards","Rewards"]].map(([value,title])=><button key={value} className={`min-h-11 border-b-2 px-3 text-sm font-semibold ${view===value?"border-indigo text-indigo":"border-transparent text-ink-muted"}`} aria-pressed={view===value} onClick={()=>setView(value)}>{title}</button>)}</nav><Link href="/recruiter/pipeline?source=candidate_referral" className={recruiterSecondary}>View referred applicants</Link></div>{message&&!detail&&!reward&&<p role="status" className="text-sm text-ink">{message}</p>}{items.length?<RecruiterDataTable label="Referral invitations" rows={items} rowKey={x=>x.id} columns={[
 {key:"person",title:"Person / role",width:"26%",render:x=><div><p className="font-semibold text-navy">{x.candidate_name}</p><p className="mt-1 text-xs text-ink-muted">{x.job_title||"General talent invitation"}</p><p className="mt-1 text-xs text-ink-muted">Submitted {compactDate(x.created_at)}</p></div>},
 {key:"source",title:"Referrer",width:"20%",render:x=><div><p className="text-sm text-ink">{x.referrer_name}</p><p className="mt-1 text-xs text-ink-muted">{label(x.source)}{x.relationship?` · ${x.relationship}`:""}</p></div>},
 {key:"progress",title:view==="rewards"?"Reward processing":"Referral progress",width:"29%",render:x=><div><p className="font-medium text-navy">{view==="rewards"?label(x.reward_status):referralLabel(x)}</p>{x.hiring_stage&&<p className="mt-1 text-xs text-ink-muted">Hiring: {label(x.hiring_stage)}</p>}{!x.application_id&&<p className="mt-1 text-xs text-ink-muted">Expires {compactDate(x.expires_at)}</p>}{view==="rewards"&&x.hiring_stage==="hired"&&<button className="min-h-11 text-xs font-semibold text-indigo" onClick={()=>setReward(x)}>Record eligibility review</button>}</div>},
 {key:"actions",title:"Actions",width:"25%",render:actions}
 ]} mobileRow={x=><div className="grid gap-3"><p className="font-semibold text-navy">{x.candidate_name}</p><p className="text-sm text-ink-muted">{x.job_title||"General invitation"}</p><p className="text-xs text-ink-muted">Referred by {x.referrer_name}</p><p className="text-sm font-medium text-ink">{view==="rewards"?label(x.reward_status):referralLabel(x)}{x.hiring_stage?` · Hiring: ${label(x.hiring_stage)}`:""}</p>{actions(x)}{view==="rewards"&&x.hiring_stage==="hired"&&<button className={recruiterSecondary} onClick={()=>setReward(x)}>Record eligibility review</button>}</div>}/>:<WorkspaceState title="No referral invitations yet" description="Candidates invite people from Job Details. Consented applications join the normal hiring pipeline with referral attribution."/>}
 <RecruiterDrawer open={!!detail} onClose={()=>setDetail(null)} title="Referral invitation activity">{detail&&<div className="grid gap-3"><h3 className="font-semibold text-navy">{detail.candidate_name}</h3><p className="text-xs text-ink-muted">Referral ID: {detail.id}</p><p className="text-sm text-ink">{label(detail.status)} · {detail.job_title||"General invitation"}</p><p className="text-xs text-ink-muted">Submitted {compactDate(detail.created_at)} · Expires {compactDate(detail.expires_at)}</p><p className="text-sm leading-6 text-ink-muted">Referrer and job attribution are fixed at submission. A referral does not grant access to the candidate’s full profile.</p>{detail.source!=="candidate"&&!detail.application_id&&!["cancelled","declined"].includes(detail.status)&&<><button disabled={busy} className={recruiterSecondary} onClick={()=>void action(detail,"resend")}>Resend invitation</button>{detail.status!=="expired"&&<button disabled={busy} className={recruiterSecondary} onClick={()=>void action(detail,"copy_link")}>Copy invitation link</button>}<button disabled={busy} className={`${recruiterSecondary} text-rose-700`} onClick={()=>{if(window.confirm("Cancel this pending invitation? The person’s account and existing applications are retained."))void action(detail,"cancel")}}>Cancel invitation</button></>}{link&&<label className="grid gap-1 text-xs text-ink-muted">Invitation link<input readOnly value={link} className={recruiterInput} onFocus={e=>e.target.select()}/></label>}{message&&<p role="status" className="text-sm text-ink">{message}</p>}<h4 className="mt-2 font-semibold text-navy">Activity</h4>{events.map((e,i)=><p key={i} className="border-b border-line py-2 text-xs text-ink-muted">{label(e.action)} · {compactDate(e.created_at)}</p>)}</div>}</RecruiterDrawer>
 <RecruiterDrawer open={!!reward} onClose={()=>{if(!busy)setReward(null)}} title="Record referral reward review" footer={<><button className={recruiterSecondary} disabled={busy} onClick={()=>setReward(null)}>Cancel</button><button type="submit" form={rewardForm} disabled={busy} className={recruiterPrimary}>Record review</button></>}><form id={rewardForm} onSubmit={review} className="grid gap-4"><p className="text-sm leading-6 text-ink-muted">Record the employer’s existing eligibility and retention-policy review after a canonical hired application. This does not initiate a payment.</p><label className="grid gap-1 text-sm text-ink">Processing status<select name="reward_status" className={recruiterInput} defaultValue={reward?.reward_status}>{["not_eligible","pending","approved","paid","cancelled"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label className="grid gap-1 text-sm text-ink">Review note<textarea required name="review_note" rows={4} maxLength={5000} className={recruiterInput}/></label><label className="flex gap-2 text-sm leading-6 text-ink"><input required type="checkbox" name="eligibility_reviewed" className="mt-1 h-4 w-4 shrink-0 accent-indigo"/>I verified referral attribution and the company’s eligibility and retention requirements.</label>{message&&<p role="alert" className="text-sm text-rose-700">{message}</p>}</form></RecruiterDrawer>
 </div>
}
