"use client";

import { FormEvent, useState } from "react";
import { apiRequest } from "@/lib/api";

export type ReferralItem={id:string;candidate_name:string;job_title?:string;referrer_name:string;referrer_email?:string;source:string;status:string;reward_status:string;updated_at:string};
export type ReferralCandidate={candidate_id:string;full_name:string};
export type ReferralJob={id:string;job_reference:string;title:string;status:string};

export function ReferralsWorkspace({initialItems,candidates,jobs}:{initialItems:ReferralItem[];candidates:ReferralCandidate[];jobs:ReferralJob[]}) {
 const [items,setItems]=useState(initialItems);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setMessage("");try{const item=await apiRequest<ReferralItem>("/api/v1/recruiter/referrals",{method:"POST",body:JSON.stringify({candidate_id:String(f.get("candidate_id")||""),job_id:String(f.get("job_id")||""),referrer_name:String(f.get("referrer_name")||""),referrer_email:String(f.get("referrer_email")||""),source:String(f.get("source")||"employee"),notes:String(f.get("notes")||"")})});setItems(v=>[item,...v]);e.currentTarget.reset();setMessage("Referral added.");}catch(c){setMessage(c instanceof Error?c.message:"Could not add referral.");}finally{setBusy(false)}}
 async function update(id:string,status:string,reward:string){setBusy(true);setMessage("");try{await apiRequest("/api/v1/recruiter/referrals/"+id,{method:"PATCH",body:JSON.stringify({status,reward_status:reward})});setItems(v=>v.map(x=>x.id===id?{...x,status,reward_status:reward}:x));}catch(c){setMessage(c instanceof Error?c.message:"Could not update referral.");}finally{setBusy(false)}}
 return <div className="grid gap-5 xl:grid-cols-[minmax(20rem,.78fr)_minmax(0,1.22fr)]">
  <form onSubmit={create} className="rounded-2xl border border-line/70 bg-white p-5 shadow-sm"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-indigo">Referral intake</p><h2 className="mt-1 text-xl font-bold text-navy">Add referred candidate</h2><div className="mt-5 grid gap-3">
   <label className="grid gap-1 text-xs font-bold text-ink-muted">Candidate<select required name="candidate_id" className="min-h-11 rounded-xl border border-line bg-white px-3 text-sm"><option value="">Choose saved candidate</option>{candidates.map(c=><option key={c.candidate_id} value={c.candidate_id}>{c.full_name}</option>)}</select></label>
   <label className="grid gap-1 text-xs font-bold text-ink-muted">Job (optional)<select name="job_id" className="min-h-11 rounded-xl border border-line bg-white px-3 text-sm"><option value="">General referral</option>{jobs.filter(j=>j.status==="active").map(j=><option key={j.id} value={j.id}>{j.job_reference} · {j.title}</option>)}</select></label>
   <label className="grid gap-1 text-xs font-bold text-ink-muted">Referrer name<input required name="referrer_name" maxLength={160} className="min-h-11 rounded-xl border border-line px-3 text-sm"/></label>
   <label className="grid gap-1 text-xs font-bold text-ink-muted">Referrer email<input name="referrer_email" type="email" maxLength={320} className="min-h-11 rounded-xl border border-line px-3 text-sm"/></label>
   <label className="grid gap-1 text-xs font-bold text-ink-muted">Source<select name="source" className="min-h-11 rounded-xl border border-line bg-white px-3 text-sm"><option value="employee">Employee</option><option value="partner">Referral partner</option><option value="recruiter">Recruiter</option><option value="other">Other</option></select></label>
   <label className="grid gap-1 text-xs font-bold text-ink-muted">Note<textarea name="notes" rows={3} className="rounded-xl border border-line px-3 py-2 text-sm"/></label>
   <button disabled={busy} className="min-h-11 rounded-xl bg-indigo px-4 text-sm font-extrabold text-white disabled:opacity-50">{busy?"Saving…":"Add referral"}</button>{message&&<p role="status" className="text-xs text-ink-muted">{message}</p>}
  </div></form>
  <section className="rounded-2xl border border-line/70 bg-white p-5 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-indigo">Referral pipeline</p><h2 className="mt-1 text-xl font-bold text-navy">Tracked referrals</h2></div><span className="rounded-full bg-indigo-soft px-3 py-1 text-xs font-bold text-indigo">{items.length}</span></div>
   <div className="mt-4 grid gap-3">{items.length?items.map(item=><article key={item.id} className="rounded-xl border border-line/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-extrabold text-navy">{item.candidate_name}</p><p className="mt-1 text-xs text-ink-muted">{item.job_title||"General talent referral"} · referred by {item.referrer_name}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-extrabold uppercase text-ink-muted">{item.status}</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-ink-muted">Status<select value={item.status} disabled={busy} onChange={e=>update(item.id,e.target.value,item.reward_status)} className="min-h-10 rounded-lg border border-line bg-white px-2 text-sm">{["referred","contacted","applied","interviewing","offered","hired","closed"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label className="grid gap-1 text-xs font-bold text-ink-muted">Reward<select value={item.reward_status} disabled={busy} onChange={e=>update(item.id,item.status,e.target.value)} className="min-h-10 rounded-lg border border-line bg-white px-2 text-sm">{["not_eligible","pending","approved","paid","cancelled"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label></div></article>):<div className="rounded-xl border border-dashed border-line p-6 text-center text-sm text-ink-muted">No referrals tracked yet.</div>}</div>
  </section>
 </div>
}
