"use client";

import { FormEvent, useId, useState } from "react";
import { RecruiterDataTable, RecruiterDrawer, WorkspaceState, recruiterPrimary, recruiterSecondary } from "./workspace-ui";
import { apiRequest } from "@/lib/api";

export type ReferralItem={id:string;candidate_name:string;job_title?:string;referrer_name:string;referrer_email?:string;source:string;status:string;reward_status:string;updated_at:string};
export type ReferralCandidate={candidate_id:string;full_name:string};
export type ReferralJob={id:string;job_reference:string;title:string;status:string};

export function ReferralsWorkspace({initialItems,candidates,jobs}:{initialItems:ReferralItem[];candidates:ReferralCandidate[];jobs:ReferralJob[]}) {
 const formID = useId();
 const [items,setItems]=useState(initialItems);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[open,setOpen]=useState(false);const[view,setView]=useState("recruitment");
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const node=e.currentTarget;const f=new FormData(node);setBusy(true);setMessage("");try{const item=await apiRequest<ReferralItem>("/api/v1/recruiter/referrals",{method:"POST",body:JSON.stringify({candidate_id:String(f.get("candidate_id")||""),job_id:String(f.get("job_id")||""),referrer_name:String(f.get("referrer_name")||""),referrer_email:String(f.get("referrer_email")||""),source:String(f.get("source")||"employee"),notes:String(f.get("notes")||"")})});setItems(v=>[item,...v]);node.reset();setOpen(false);setMessage("Referral added.");}catch(c){setMessage(c instanceof Error?c.message:"Could not add referral.");}finally{setBusy(false)}}
 async function update(id:string,status:string,reward:string){setBusy(true);setMessage("");try{await apiRequest("/api/v1/recruiter/referrals/"+id,{method:"PATCH",body:JSON.stringify({status,reward_status:reward})});setItems(v=>v.map(x=>x.id===id?{...x,status,reward_status:reward}:x));}catch(c){setMessage(c instanceof Error?c.message:"Could not update referral.");}finally{setBusy(false)}}
 return <div className="grid min-w-0 gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><nav aria-label="Referral views" className="flex gap-2"><button aria-pressed={view==="recruitment"} onClick={()=>setView("recruitment")} className={`min-h-11 border-b-2 px-3 text-sm font-semibold ${view==="recruitment"?"border-indigo text-indigo":"border-transparent text-ink-muted"}`}>Recruitment</button><button aria-pressed={view==="rewards"} onClick={()=>setView("rewards")} className={`min-h-11 border-b-2 px-3 text-sm font-semibold ${view==="rewards"?"border-indigo text-indigo":"border-transparent text-ink-muted"}`}>Rewards</button></nav><button className={recruiterPrimary} onClick={()=>setOpen(true)}>Add referral</button></div><RecruiterDrawer open={open} onClose={()=>{if(!busy)setOpen(false);}} title="Add referred candidate" footer={<><button type="button" disabled={busy} onClick={()=>setOpen(false)} className={recruiterSecondary}>Cancel</button><button type="submit" form={formID} disabled={busy} className={recruiterPrimary}>{busy?"Saving…":"Add referral"}</button></>}>  <form id={formID} onSubmit={create} className="min-w-0 max-w-full rounded-2xl border border-line/70 bg-white p-5 shadow-sm"><p className="text-[13px] font-extrabold uppercase tracking-[0.1em] text-indigo">Referral intake</p><h2 className="mt-1 text-xl font-bold text-navy">Add referred candidate</h2><div className="mt-5 grid gap-3">
   <label className="min-w-0 grid gap-1 text-xs font-bold text-ink-muted">Candidate<select required name="candidate_id" className="min-h-11 w-full min-w-0 rounded-xl border border-line bg-white px-3 text-sm"><option value="">Choose saved candidate</option>{candidates.map(c=><option key={c.candidate_id} value={c.candidate_id}>{c.full_name}</option>)}</select></label>
   <label className="min-w-0 grid gap-1 text-xs font-bold text-ink-muted">Job (optional)<select name="job_id" className="min-h-11 w-full min-w-0 rounded-xl border border-line bg-white px-3 text-sm"><option value="">General referral</option>{jobs.filter(j=>j.status==="active").map(j=><option key={j.id} value={j.id}>{j.job_reference} · {j.title}</option>)}</select></label>
   <label className="min-w-0 grid gap-1 text-xs font-bold text-ink-muted">Referrer name<input required name="referrer_name" maxLength={160} className="min-h-11 w-full min-w-0 rounded-xl border border-line px-3 text-sm"/></label>
   <label className="min-w-0 grid gap-1 text-xs font-bold text-ink-muted">Referrer email<input name="referrer_email" type="email" maxLength={320} className="min-h-11 w-full min-w-0 rounded-xl border border-line px-3 text-sm"/></label>
   <label className="min-w-0 grid gap-1 text-xs font-bold text-ink-muted">Source<select name="source" className="min-h-11 w-full min-w-0 rounded-xl border border-line bg-white px-3 text-sm"><option value="employee">Employee</option><option value="partner">Referral partner</option><option value="recruiter">Recruiter</option><option value="other">Other</option></select></label>
   <label className="min-w-0 grid gap-1 text-xs font-bold text-ink-muted">Note<textarea name="notes" rows={3} className="w-full min-w-0 rounded-xl border border-line px-3 py-2 text-sm"/></label>
{message&&<p role="status" className="text-xs text-ink-muted">{message}</p>}
  </div></form></RecruiterDrawer>

  {message&&!open&&<p role="status" className="text-sm text-ink">{message}</p>}
  {items.length ? <RecruiterDataTable label="Tracked referrals" rows={items} rowKey={item=>item.id} columns={[
    {key:"candidate",title:"Candidate / job",width:"30%",render:item=><div><p className="font-semibold text-navy">{item.candidate_name}</p><p className="mt-1 text-xs text-ink-muted">{item.job_title||"General talent referral"}</p></div>},
    {key:"referrer",title:"Referrer / source",width:"27%",render:item=><div><p className="text-sm text-ink">{item.referrer_name}</p><p className="mt-1 break-all text-xs text-ink-muted">{item.referrer_email}</p><p className="mt-1 text-xs capitalize text-ink-muted">{item.source}</p></div>},
    {key:"state",title:view==="recruitment"?"Recruitment status":"Reward status",width:"28%",render:item=><label className="grid gap-1 text-xs text-ink-muted">{view==="recruitment"?"Recruitment status":"Reward status"}<select aria-label={`${view==="recruitment"?"Recruitment":"Reward"} status for ${item.candidate_name}`} value={view==="recruitment"?item.status:item.reward_status} disabled={busy} onChange={event=>update(item.id,view==="recruitment"?event.target.value:item.status,view==="rewards"?event.target.value:item.reward_status)} className="min-h-11 w-full rounded-lg border border-line bg-white px-2 text-sm text-ink">{(view==="recruitment"?["referred","contacted","applied","interviewing","offered","hired","closed"]:["not_eligible","pending","approved","paid","cancelled"]).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label>},
    {key:"updated",title:"Updated",width:"15%",secondary:true,render:item=><span className="text-xs text-ink-muted">{new Date(item.updated_at).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</span>},
  ]} mobileRow={item=><div className="grid gap-3"><p className="font-semibold text-navy">{item.candidate_name}</p><p className="text-sm text-ink-muted">{item.job_title||"General referral"}</p><p className="text-xs text-ink-muted">Referred by {item.referrer_name} · {item.source}</p><label className="grid gap-1 text-xs text-ink-muted">{view==="recruitment"?"Recruitment status":"Reward status"}<select value={view==="recruitment"?item.status:item.reward_status} disabled={busy} onChange={event=>update(item.id,view==="recruitment"?event.target.value:item.status,view==="rewards"?event.target.value:item.reward_status)} className="min-h-11 rounded-lg border border-line bg-white px-2 text-sm text-ink">{(view==="recruitment"?["referred","contacted","applied","interviewing","offered","hired","closed"]:["not_eligible","pending","approved","paid","cancelled"]).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label></div>}/> : <WorkspaceState title="No referrals tracked yet" description="Add a saved candidate and keep recruitment progress separate from reward processing." />}

 </div>
}
