import Link from "next/link";
import { RecruiterShell } from "@/components/recruiter/recruiter-shell";
import { MetricStrip } from "@/components/recruiter/metric-strip";
import { PipelineTable } from "@/components/recruiter/pipeline-table";
import { requireRole } from "@/lib/auth-server";
import { recruiterAPI } from "@/lib/recruiter-server";
import { RecruiterDashboard } from "@/lib/recruiter";

export const dynamic = "force-dynamic";
export default async function RecruiterDashboardPage() {
  await requireRole("recruiter");
  const data = await recruiterAPI<RecruiterDashboard>("/api/v1/recruiter/dashboard");
  return <RecruiterShell><div className="grid gap-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-indigo">{data.company_name}</p><h1 className="font-display mt-1 text-2xl font-bold tracking-[-0.03em] text-ink sm:text-3xl">Good to see you, {data.recruiter_name.split(" ")[0]}.</h1><p className="mt-1 text-sm text-ink-muted">Operational view of hiring activity that needs action now.</p></div><Link href="/recruiter/jobs" className="rounded-xl bg-indigo px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-violet-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo focus-visible:ring-offset-2">Manage jobs</Link></div><MetricStrip items={[{label:"Active jobs",value:data.active_jobs},{label:"Applications",value:data.applications},{label:"Shortlisted",value:data.shortlisted},{label:"Interviews",value:data.upcoming_interviews,hint:"upcoming"},{label:"Offers",value:data.offers},{label:"Hires",value:data.hires},{label:"Placement rate",value:`${data.placement_rate.toFixed(1)}%`}]}/><section className="rounded-2xl border border-line/70 bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-display text-lg font-bold text-ink">Needs attention</h2><p className="text-xs text-ink-muted">Exceptions and ageing items, not generic announcements.</p></div></div>{data.needs_attention.length?<div className="mt-3 grid gap-2 xl:grid-cols-2">{data.needs_attention.map(item=><Link href={item.href} key={`${item.kind}-${item.title}`} className="rounded-xl border border-line/70 bg-[#fafbfe] p-3 hover:border-indigo/30"><p className="text-sm font-bold text-ink">{item.title}</p><p className="mt-1 text-xs leading-5 text-ink-muted">{item.detail}</p></Link>)}</div>:<p className="mt-3 rounded-xl bg-mint/35 px-3 py-3 text-sm text-ink-muted">No ageing candidates or near-term job deadlines need attention right now.</p>}</section><section><div className="mb-2 flex items-end justify-between"><div><h2 className="font-display text-lg font-bold text-ink">Recent applications</h2><p className="text-xs text-ink-muted">Latest candidate movement across company jobs.</p></div><Link href="/recruiter/pipeline" className="text-sm font-bold text-indigo hover:underline">Open full pipeline</Link></div><PipelineTable rows={data.recent_applications}/></section></div></RecruiterShell>;
}
