export const guides = [
  {
    slug: "build-a-resume",
    title: "Build a résumé that sounds like you",
    category: "Your story",
    dek: "Turn your work and experience into a clear, useful introduction.",
    image: "ChatGPT Image Sep 23, 2026, 06_05_56 PM (5).png",
    alt: "Woman looking thoughtfully at a laptop while preparing her résumé",
    intro: "A good résumé helps someone understand what you did, what changed because of your work and what you hope to do next. Start with clarity instead of decoration.",
    steps: [
      { title: "Start with the role", body: "Read the job description and identify the skills and responsibilities that overlap with your actual experience." },
      { title: "Show what you contributed", body: "Use a short action-and-result format. Explain the problem, your contribution and the result; include a number only if you can support it." },
      { title: "Make it easy to scan", body: "Use clear headings for experience, education and skills. Place your most relevant information near the top." },
      { title: "Check before sharing", body: "Review dates, spelling, contact information, links and formatting. Save a readable PDF when an employer requests it." },
    ],
  },
  {
    slug: "prepare-for-an-interview",
    title: "Prepare for an interview, your way",
    category: "Conversations",
    dek: "Walk into the conversation knowing what you want to share and ask.",
    image: "ChatGPT Image Sep 23, 2026, 06_05_56 PM (6).png",
    alt: "Professional having a positive face-to-face interview conversation",
    intro: "Interviews work best as two-way conversations. Preparation helps you explain your experience and understand whether the opportunity fits you.",
    steps: [
      { title: "Know the role", body: "Read the responsibilities, working arrangement and company information. Note what you want to clarify." },
      { title: "Choose three examples", body: "Prepare concise stories about a problem you solved, a time you collaborated and something you learned." },
      { title: "Practice out loud", body: "Explain your examples in your own words, including what you did and what you would do differently." },
      { title: "Ask your questions", body: "Ask about expectations, feedback, team collaboration and next steps. You are evaluating the opportunity too." },
    ],
  },
  {
    slug: "practical-skill-growth-plan",
    title: "Make a practical skill-growth plan",
    category: "Growth",
    dek: "A manageable plan to learn deliberately and build momentum.",
    image: "ChatGPT Image Sep 23, 2026, 06_05_56 PM (7).png",
    alt: "Woman taking handwritten notes beside her laptop",
    intro: "Skill growth does not have to mean collecting endless courses. A smaller plan that you can repeat is often easier to sustain.",
    steps: [
      { title: "Pick a destination", body: "Choose a role or responsibility you want to explore and list the skills that actually appear in relevant postings." },
      { title: "Find one gap", body: "Choose one skill that would make your next step easier. Avoid trying to master everything at once." },
      { title: "Build while learning", body: "Turn your practice into a small project, case study, writing sample or demonstration of your process." },
      { title: "Review and adjust", body: "Set a recurring check-in to see what you can now do, what still feels difficult and what to practice next." },
    ],
  },
  {
    slug: "humans-and-ai-together",
    title: "Humans and AI working better together",
    category: "The future of work",
    dek: "Use emerging tools thoughtfully while keeping your own judgement.",
    image: "ChatGPT Image Sep 23, 2026, 06_05_57 PM (8).png",
    alt: "Digital network connecting two AI-generated faces on a laptop screen",
    intro: "AI can help you explore ideas, structure a draft or practice a conversation. You remain responsible for accuracy, privacy and the final decision.",
    steps: [
      { title: "Start with a clear task", body: "Ask for help with a specific goal, such as outlining a résumé bullet or generating interview practice questions." },
      { title: "Protect personal details", body: "Do not paste confidential work, private candidate information or sensitive personal data into an unfamiliar tool." },
      { title: "Check the output", body: "Verify facts, qualifications and company details against trustworthy original sources." },
      { title: "Keep your voice", body: "Edit suggestions so they reflect your actual work and the way you naturally speak. Never invent achievements." },
    ],
  },
] as const;
