export type RecruiterDashboard = {
  recruiter_name: string;
  company_name: string;
  active_jobs: number;
  applications: number;
  new_applications: number;
  shortlisted: number;
  upcoming_interviews: number;
  upcoming_items: UpcomingInterviewItem[];
  offers: number;
  hires: number;
  placement_rate: number;
  recent_applications: PipelineRow[];
  needs_attention: AttentionItem[];
};

export type AttentionItem = { kind: string; title: string; detail: string; href: string };
export type UpcomingInterviewItem = { id: string; candidate_name: string; job_title: string; scheduled_at: string };
export type RecruiterJob = {
  id: string;
  job_reference: string;
  title: string;
  department?: string;
  role_category?: string;
  status: string;
  employment_type: string;
  work_mode: string;
  city?: string;
  state?: string;
  country_code: string;
  openings: number;
  applications: number;
  new_applications: number;
  shortlisted: number;
  interviews: number;
  published_at?: string;
  application_deadline?: string;
  updated_at: string;
};
export type RecruiterJobWorkspace = {
  items: RecruiterJob[];
  page: number;
  limit: number;
  total: number;
  sort: "updated" | "applications" | "newest" | "deadline";
  summary: {
    total_jobs: number;
    active_jobs: number;
    draft_jobs: number;
    paused_jobs: number;
    applications: number;
    new_applications: number;
  };
};
export type PipelineRow = {
  application_id: string;
  candidate_id: string;
  candidate_name: string;
  headline?: string;
  city?: string;
  experience_months: number;
  notice_period_days?: number;
  job_id: string;
  job_title: string;
  job_reference: string;
  stage: string;
  applied_at: string;
  updated_at: string;
  designation: string;
  current_company: string;
  education: string;
  university: string;
  preferred_location: string;
  previous_company: string;
  key_skills: string;
  photo_data_url?: string;
  cv_filename?: string;
  saved: boolean;
  comment_count: number;
  last_active_at?: string;
  profile_updated_at: string;
};
export type EditableRecruiterJob = {
  id: string;
  job_reference: string;
  status: string;
  title: string;
  department: string;
  employment_type: string;
  work_mode: string;
  role_category: string;
  location: string;
  min_experience_years: number;
  max_experience_years: number | null;
  min_salary_lakhs: number | null;
  max_salary_lakhs: number | null;
  skills: string[];
  description: string;
  responsibilities: string;
  company_overview: string;
  why_join: string;
  hiring_process: string[];
  openings: number;
};
export type PipelineList = { items: PipelineRow[]; page: number; limit: number; total: number };
export type Interview = {
  id: string;
  application_id: string;
  candidate_id: string;
  job_id: string;
  job_reference: string;
  candidate_name: string;
  candidate_headline: string;
  job_title: string;
  scheduled_at: string;
  duration_minutes: number;
  meeting_url: string;
  status: string;
  round_label: string;
  notes?: string;
};
export type InterviewChangeEvent = {
  action: "reschedule" | "cancel" | "complete";
  previous_status: string;
  new_status: string;
  previous_scheduled_at: string;
  new_scheduled_at: string;
  changed_at: string;
  actor_name: string;
};
export type RecruiterCandidateDetail = {
  user_id: string;
  full_name: string;
  headline?: string;
  email: string;
  saved: boolean;
  current_city?: string;
  current_state?: string;
  country_code: string;
  total_experience_months: number;
  notice_period_days?: number;
  profile_completion: number;
  last_active_at?: string;
  profile_updated_at: string;
  photo_data_url?: string;
  details: Record<string, unknown>;
};

export const stages = ["new_application","screening","shortlisted","technical_interview","hr_round","final_interview","offer","hired","rejected","withdrawn"] as const;
export const jobStatuses = ["draft","active","paused","closed","expired","archived"] as const;
export function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()); }
export function experience(months: number) { const years=Math.floor(months/12); const rest=months%12; return years ? `${years}y${rest ? ` ${rest}m` : ""}` : `${rest}m`; }
export function compactDate(value?: string) { if(!value) return "—"; return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value)); }
