"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api";
const input = "min-h-11 rounded-lg border border-slate-200 bg-white px-3 text-sm";
export function CompanyGrantForm({ companyID }: {
    companyID: string;
}) {
    const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
    return <form className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(""); setNotice(""); void apiRequest(`/api/v1/admin/companies/${companyID}/overrides`, { method: "POST", body: JSON.stringify({ key: f.get("key"), additional: Number(f.get("additional")), expires_at: String(f.get("expires_at")) + ":00Z", reason: f.get("reason") }) }).then(() => { setNotice("Temporary allocation granted and audited."); router.refresh(); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}><h2 className="sm:col-span-2 text-xl font-semibold">Temporary allocation</h2><label className="grid gap-2 text-sm font-medium">Resource<select name="key" className={input}>{["sub_admins", "recruiters", "talent_seats", "active_jobs", "saved_searches", "smart_pools", "outreach_sequences", "talent_profile_unlock", "outreach_message"].map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Additional allocation<input name="additional" type="number" min={1} max={1000000000} required className={input}/></label><label className="grid gap-2 text-sm font-medium">Expires at (UTC)<input name="expires_at" type="datetime-local" required className={input}/></label><label className="sm:col-span-2 grid gap-2 text-sm font-medium">Allocation reason<textarea name="reason" minLength={10} maxLength={2000} required className="min-h-24 rounded-lg border border-slate-200 p-3 text-sm"/></label><p className="sm:col-span-2 text-sm leading-6 text-slate-500">This adds to an approved allocation until its expiry. It does not extend the paid period or restore an expired Talent subscription. Existing records are preserved.</p>{error && <p role="alert" className="sm:col-span-2 text-sm swx-company-error">{error}</p>}{notice && <p role="status" className="sm:col-span-2 text-sm swx-company-success">{notice}</p>}<button disabled={busy} className="min-h-11 rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white">{busy ? "Saving…" : "Grant temporary allocation"}</button></form>;
}
