"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api";
import { useAdminPermission } from "@/components/admin/admin-access-provider";

function Message({value}:{value:string}){return value?<p className="text-xs text-slate-500">{value}</p>:null}

export function RunIntelligenceButton(){
  const allowed=useAdminPermission("intelligence.models.evaluate");const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");if(!allowed)return null;
  async function run(){setPending(true);setMessage("");try{await apiRequest("/api/v1/admin/intelligence/run",{method:"POST"});setMessage("Analysis request queued for the separate Intelligence Engine.");router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Analysis request failed.");}finally{setPending(false)}}
  return <div className="flex flex-wrap items-center gap-3"><button type="button" disabled={pending} onClick={()=>void run()} className="rounded-xl bg-[#4656cf] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{pending?"Queueing…":"Queue advisory analysis"}</button><Message value={message}/></div>
}

export function InsightReviewActions({id,status}:{id:string;status:string}){
  const allowed=useAdminPermission("intelligence.feedback.review");const router=useRouter();const[pending,setPending]=useState("");const[message,setMessage]=useState("");if(!allowed||status!=="new")return null;
  async function review(next:"reviewed"|"dismissed",outcome:"accepted"|"rejected"|"needs_more_data"){const note=window.prompt("Review note (optional)")??"";setPending(next);setMessage("");try{await apiRequest("/api/v1/admin/intelligence/insights/"+id,{method:"PATCH",body:JSON.stringify({status:next,outcome,note:note.trim()})});router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Review failed.");}finally{setPending("")}}
  return <div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={!!pending} onClick={()=>void review("reviewed","accepted")} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800">Useful</button><button type="button" disabled={!!pending} onClick={()=>void review("reviewed","needs_more_data")} className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">Needs data</button><button type="button" disabled={!!pending} onClick={()=>void review("dismissed","rejected")} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700">Dismiss</button><Message value={message}/></div>
}

export function IntelligenceSwitchControl({switchKey,enabled,description}:{switchKey:string;enabled:boolean;description:string}){
  const allowed=useAdminPermission("intelligence.kill_switch");const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");if(!allowed)return <p className="text-xs text-slate-500">{enabled?"Enabled":"Disabled"}</p>;
  async function change(){let approvalID="";if(!enabled){approvalID=window.prompt("Approval UUID required to enable this intelligence capability")??"";if(!approvalID.trim())return;}setPending(true);setMessage("");try{await apiRequest("/api/v1/admin/intelligence/switches/"+encodeURIComponent(switchKey),{method:"PATCH",body:JSON.stringify({enabled:!enabled,approval_id:approvalID.trim()})});router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Switch change failed.");}finally{setPending(false)}}
  return <div className="mt-2"><button type="button" disabled={pending} onClick={()=>void change()} className={enabled?"rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs font-bold text-red-700":"rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"}>{pending?"Applying…":enabled?"Disable capability":"Enable with approval"}</button><p className="mt-1 text-[11px] leading-4 text-slate-400">{description}</p><Message value={message}/></div>
}

export function ModelRegistrationForm(){
  const allowed=useAdminPermission("intelligence.config.update");const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");if(!allowed)return null;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);setPending(true);setMessage("");try{const config=JSON.parse(String(data.get("config")??"{}"));await apiRequest("/api/v1/admin/intelligence/models",{method:"POST",body:JSON.stringify({engine_type:data.get("engine_type"),version:String(data.get("version")??"").trim(),provider:String(data.get("provider")??"local").trim(),model_ref:String(data.get("model_ref")??"").trim(),config})});form.reset();setMessage("Candidate model registered. It is not production-active.");router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Model registration failed.");}finally{setPending(false)}}
  return <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4"><p className="text-sm font-bold text-slate-900">Register candidate model/version</p><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-slate-600">Engine<select name="engine_type" className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-normal"><option>matching</option><option>candidate_intelligence</option><option>resume_parser</option><option>recommendation</option><option>evaluation</option><option>platform_intelligence</option><option>ai_gateway</option></select></label><label className="grid gap-1 text-xs font-bold text-slate-600">Version<input required name="version" placeholder="1.1.0" className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-600">Provider<input required name="provider" defaultValue="local" className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-600">Model reference<input required name="model_ref" placeholder="deterministic-weighted-v2" className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-normal"/></label></div><label className="grid gap-1 text-xs font-bold text-slate-600">Config JSON<textarea name="config" defaultValue='{"weights":{"skills":0.45,"experience":0.20,"location":0.10,"availability":0.10,"semantic":0.15}}' rows={4} className="rounded-xl border border-slate-200 p-3 font-mono text-xs font-normal"/></label><div className="flex items-center gap-3"><button disabled={pending} className="rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{pending?"Registering…":"Register candidate version"}</button><Message value={message}/></div></form>
}

export function ModelActions({id,status}:{id:string;status:string}){
  const canEvaluate=useAdminPermission("intelligence.models.evaluate");const canApprove=useAdminPermission("intelligence.models.approve");const router=useRouter();const[pending,setPending]=useState("");const[message,setMessage]=useState("");
  async function evaluate(){setPending("evaluate");setMessage("");try{await apiRequest("/api/v1/admin/intelligence/models/"+id+"/evaluate",{method:"POST"});setMessage("Evaluation requested. The Intelligence Engine will process it.");router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Evaluation request failed.");}finally{setPending("")}}
  async function promote(){const approvalID=window.prompt("Approved governance request UUID")??"";if(!approvalID.trim())return;setPending("promote");setMessage("");try{await apiRequest("/api/v1/admin/intelligence/models/"+id+"/promote",{method:"POST",body:JSON.stringify({approval_id:approvalID.trim()})});router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Promotion failed.");}finally{setPending("")}}
  return <div className="mt-3 flex flex-wrap items-center gap-2">{canEvaluate&&status!=="production"&&<button disabled={!!pending} onClick={()=>void evaluate()} className="rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Evaluate</button>}{canApprove&&status!=="production"&&<button disabled={!!pending} onClick={()=>void promote()} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Promote with approval</button>}<Message value={message}/></div>
}


export function PromptRegistrationForm(){
  const allowed=useAdminPermission("intelligence.config.update");const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");if(!allowed)return null;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const variables=String(data.get("variables")??"").split(",").map(v=>v.trim()).filter(Boolean);setPending(true);setMessage("");try{await apiRequest("/api/v1/admin/intelligence/prompts",{method:"POST",body:JSON.stringify({prompt_key:String(data.get("prompt_key")??"").trim(),template:String(data.get("template")??"").trim(),status:"draft",variables,model_version_id:String(data.get("model_version_id")??"").trim()})});form.reset();setMessage("Prompt version registered.");router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Prompt registration failed.");}finally{setPending(false)}}
  return <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4"><p className="text-sm font-bold text-slate-900">Register prompt version</p><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-slate-600">Prompt key<input required name="prompt_key" placeholder="match.explanation" className="h-10 rounded-xl border border-slate-200 px-3 font-mono text-xs font-normal"/></label><div className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600"><strong>Lifecycle:</strong> new versions are always draft; activation requires separate approval.</div><label className="grid gap-1 text-xs font-bold text-slate-600">Variables<input name="variables" placeholder="match_components,job_title" className="h-10 rounded-xl border border-slate-200 px-3 text-sm font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-600">Model version UUID<input name="model_version_id" className="h-10 rounded-xl border border-slate-200 px-3 font-mono text-xs font-normal"/></label></div><label className="grid gap-1 text-xs font-bold text-slate-600">Prompt template<textarea required name="template" maxLength={20000} rows={5} className="rounded-xl border border-slate-200 p-3 font-mono text-xs font-normal"/></label><div className="flex items-center gap-3"><button disabled={pending} className="rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{pending?"Registering…":"Register prompt version"}</button><Message value={message}/></div></form>
}


export function PromptActions({id,status}:{id:string;status:string}){
  const allowed=useAdminPermission("intelligence.prompts.approve");const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");if(!allowed||status!=="draft")return null;
  async function activate(){const approvalID=window.prompt("Approved governance request UUID for this prompt version")??"";if(!approvalID.trim())return;setPending(true);setMessage("");try{await apiRequest("/api/v1/admin/intelligence/prompts/"+id+"/activate",{method:"POST",body:JSON.stringify({approval_id:approvalID.trim()})});router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Prompt activation failed.");}finally{setPending(false)}}
  return <div className="mt-3 flex flex-wrap items-center gap-2"><button type="button" disabled={pending} onClick={()=>void activate()} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">{pending?"Activating…":"Activate with approval"}</button><Message value={message}/></div>
}


export function HumanReviewActions({id,status}:{id:string;status:string}){
  const allowed=useAdminPermission("intelligence.feedback.review");const router=useRouter();const[pending,setPending]=useState("");const[message,setMessage]=useState("");if(!allowed||!["open","in_review"].includes(status))return null;
  async function review(next:"in_review"|"resolved"|"dismissed"){const note=window.prompt(next==="in_review"?"Review note (optional)":"Resolution note")??"";if((next==="resolved"||next==="dismissed")&&!note.trim())return;setPending(next);setMessage("");try{await apiRequest("/api/v1/admin/intelligence/reviews/"+id,{method:"PATCH",body:JSON.stringify({status:next,note:note.trim()})});router.refresh();}catch(cause){setMessage(cause instanceof Error?cause.message:"Review update failed.");}finally{setPending("")}}
  return <div className="mt-3 flex flex-wrap gap-2">{status==="open"&&<button type="button" disabled={!!pending} onClick={()=>void review("in_review")} className="rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Start review</button>}<button type="button" disabled={!!pending} onClick={()=>void review("resolved")} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800">Resolve</button><button type="button" disabled={!!pending} onClick={()=>void review("dismissed")} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700">Dismiss</button><Message value={message}/></div>
}
