import Link from "next/link";
import type { AdminApplication,AdminInterview,AdminRecruitmentList } from "@/lib/admin";
import { recruitmentStages,interviewStatuses,recruitmentDate,recruitmentHref } from "@/lib/admin-recruitment";

export const adminSurface = "min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const control = "h-11 w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal focus-visible:outline-2 focus-visible:outline-indigo-500";
export function RecruitmentFilters({query,interviews=false}:{query:URLSearchParams;interviews?:boolean}) {
  return <form action={interviews?"/swx-command-centre/interviews":"/swx-command-centre/applications"} className={adminSurface+" grid gap-3 sm:grid-cols-2 xl:grid-cols-4"}>
    <label className="grid min-w-0 gap-1 text-xs font-bold text-slate-600">Search recruitment<input className={control} name="q" maxLength={200} defaultValue={query.get("q")||""} placeholder="Job title/reference, application or candidate ID" /></label>
    <label className="grid min-w-0 gap-1 text-xs font-bold text-slate-600">Organization ID<input className={control} name="company_id" maxLength={36} defaultValue={query.get("company_id")||""} placeholder="Optional organization UUID" /></label>
    <label className="grid min-w-0 gap-1 text-xs font-bold text-slate-600">Organization country<input className={control+" uppercase"} name="country" maxLength={2} pattern="[A-Za-z]{2}" defaultValue={query.get("country")||""} placeholder="e.g. IN" /></label>
    <label className="grid min-w-0 gap-1 text-xs font-bold text-slate-600">Application stage<select aria-label="Application stage" className={control} name="stage" defaultValue={query.get("stage")||""}><option value="">All stages</option>{recruitmentStages.map(stage=><option key={stage} value={stage}>{stage.replaceAll("_"," ")}</option>)}</select></label>
    {query.get("job_id") && <input type="hidden" name="job_id" value={query.get("job_id")!} />}
    {(["from","before"] as const).map(key=>query.get(key)&&<input key={key} type="hidden" name={key} value={query.get(key)!} />)}
    {interviews && <><label className="grid min-w-0 gap-1 text-xs font-bold text-slate-600">Interview status<select aria-label="Interview status" className={control} name="status" defaultValue={query.get("status")||""}><option value="">All statuses</option>{interviewStatuses.map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 self-end text-sm text-slate-600"><input type="checkbox" name="upcoming" value="true" defaultChecked={query.get("upcoming")==="true"} />Upcoming scheduled only</label></>}
    <button className="h-11 self-end rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white">Apply filters</button>
    <Link href={interviews?"/swx-command-centre/interviews":"/swx-command-centre/applications"} className="inline-flex min-h-11 items-center text-sm font-bold text-indigo-600">Clear all filters</Link>
    {(query.get("job_id")||query.get("from")||query.get("before"))&&<p className="break-all text-xs leading-5 text-slate-500 sm:col-span-2 xl:col-span-4">Retained filter: {query.get("job_id")&&`job ${query.get("job_id")}. `}{query.get("from")&&`Applied from ${recruitmentDate(query.get("from")!)}. `}{query.get("before")&&`Applied before ${recruitmentDate(query.get("before")!)}.`}</p>}
  </form>;
}
export function RecruitmentPagination({data,query,path}:{data:AdminRecruitmentList<unknown>;query:URLSearchParams;path:string}) {
  const pages=Math.max(1,Math.ceil(data.total/data.limit));
  return <footer className="flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600"><span>{data.total.toLocaleString("en-IN")} records</span><div className="flex items-center gap-2"><Link aria-disabled={data.page<=1} tabIndex={data.page<=1?-1:undefined} className={`rounded-lg border px-3 py-2 ${data.page<=1?"pointer-events-none opacity-40":""}`} href={recruitmentHref(path,query,Math.max(1,data.page-1))}>Previous</Link><span className="text-xs">Page {data.page} of {pages}</span><Link aria-disabled={data.page>=pages} tabIndex={data.page>=pages?-1:undefined} className={`rounded-lg border px-3 py-2 ${data.page>=pages?"pointer-events-none opacity-40":""}`} href={recruitmentHref(path,query,Math.min(pages,data.page+1))}>Next</Link></div></footer>;
}
function HistoryLink({id}:{id:string}) { return <Link className="inline-flex min-h-10 items-center font-bold text-indigo-600" href={`/swx-command-centre/applications/${id}`}>View recorded history →</Link>; }
export function ApplicationsRecords({items}:{items:AdminApplication[]}) {
  return <><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white lg:block"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Application / candidate","Job / organization","Stage","Submitted (UTC)","History"].map(label=><th scope="col" key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-slate-100 align-top"><td className="px-4 py-4"><p className="font-mono text-xs">{item.id}</p><p className="mt-2 font-mono text-xs text-slate-500">Candidate {item.candidate_id}</p><p className="mt-2 text-xs text-slate-500">Source: {item.source}</p></td><td className="px-4 py-4"><p className="font-bold text-slate-900">{item.job_title}</p><p className="mt-1 text-xs text-indigo-600">{item.job_reference}</p><p className="mt-1 text-slate-500">{item.company_name}</p></td><td className="px-4 py-4"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{item.stage.replaceAll("_"," ")}</span></td><td className="px-4 py-4 text-xs text-slate-600">{recruitmentDate(item.applied_at)}</td><td className="px-4 py-4"><HistoryLink id={item.id} /></td></tr>)}</tbody></table></div><div className="grid gap-3 lg:hidden">{items.map(item=><article key={item.id} className={adminSurface} aria-label={`Application ${item.id}`}><h2 className="text-lg font-bold text-slate-900">{item.job_title}</h2><p className="mt-1 text-sm text-slate-500">{item.company_name} · {item.job_reference}</p><p className="mt-3 text-sm font-bold text-indigo-700">{item.stage.replaceAll("_"," ")}</p><p className="mt-2 break-all font-mono text-xs text-slate-500">Application {item.id}<br/>Candidate {item.candidate_id}</p><p className="mt-2 text-xs text-slate-500">{recruitmentDate(item.applied_at)} · {item.source}</p><HistoryLink id={item.id} /></article>)}</div></>;
}
export function InterviewRecords({items}:{items:AdminInterview[]}) {
  return <div className="grid gap-4 xl:grid-cols-2">{items.map(item=><article key={item.id} className={adminSurface} aria-label={`Interview ${item.id}`}><div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-bold text-slate-900">{item.round_label}</h2><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{item.status.replaceAll("_"," ")}</span></div><p className="mt-2 font-bold text-slate-800">{item.job_title}</p><p className="mt-1 text-sm text-slate-500">{item.company_name} · {item.job_reference}</p><p className="mt-4 text-sm font-bold text-slate-800">{recruitmentDate(item.scheduled_at)} · {item.duration_minutes} min</p><p className="mt-3 break-all font-mono text-xs leading-6 text-slate-500">Interview {item.id}<br/>Candidate {item.candidate_id}<br/>Organizer {item.recruiter_id}</p><HistoryLink id={item.application_id} /></article>)}</div>;
}
